- package-lock.json
- package.json
Update ADF packages version 3.9.0
> Update ADF packages version 3.9.0

- docs/features/search-results.md
> - [ ] Bugfix
add more clarity on precise searches …
> update search docs

- src/app/components/sidenav/directives/action.directive.spec.ts
- src/app/components/sidenav/directives/action.directive.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3595
**Does this PR …
> [ACA-3595] Fix broken extending navbar by using route id reference

- src/app.config.json
- src/assets/i18n/en.json
> [ADF-5178] - add translation for filters

- e2e/suites/actions/new-menu.test.ts
> Enable remaining tests

- e2e/suites/actions/library-actions.test.ts
- package-lock.json
- package.json
- projects/aca-testing-shared/src/configs.ts
- src/app/services/node-actions.service.spec.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3670
**Not a member** will …
> [ACA-3670] Inconsistent empty role value between library views

- package-lock.json
- package.json
- src/app/app.component.spec.ts
- src/app/app.component.ts
> MNT-21595- Fetch all the groups

- protractor.conf.js
- scripts/ci/job_hooks/before_e2e.sh
> Update webdriver version

- e2e/protractor.excludes.json
- e2e/suites/actions-available/files-folders/search-results.ts
- package-lock.json
- package.json
- protractor.conf.js
- src/app.config.json
> - [X] Docs have been added / updated (for bug fixes / features)
> - [X] Bugfix
[ACA-3799] add prefix filter …
> [ACA-3799] add prefix * name filter

- protractor.conf.js
> - [ ] Bugfix
> - [x] Other... Please describe: e2e runtime fix
https://issues.alfresco.com/jira/browse/ACA-3793 …
> [ACA-3793] - Make e2e download folder path OS agnostic

- e2e/suites/actions-available/test-util.ts
- projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.html
- projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.spec.ts
- projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.ts
- projects/aca-testing-shared/src/components/toolbar/toolbar.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3808
**Does this PR …
> [ACA-3808] - fix e2e actionMenu

- projects/aca-shared/src/lib/services/content-api.service.ts
- src/app/directives/document-list.directive.ts
> - [ ] Bugfix
[ACA-3816](https://issues.alfresco.com/jira/browse/ACA-3816)
**Does …
> [ACA-3816] Metadata - get definition field

- e2e/protractor.excludes.json
- src/app/store/effects/viewer.effects.ts
https://issues.alfresco.com/jira/browse/ACA-3394
> [ACA-3394] Fixing wrong rebase for file preview and exclude failing regressive e2es

- src/app/components/page.component.spec.ts
- src/app/components/page.component.ts
> - [x] Bugfix
[ACA-3788](https://issues.alfresco.com/jira/browse/ACA-3788)
**Does …
> [ACA-3788] Viewer - toolbar disappears after refresh

- e2e/tsconfig.e2e.json
- projects/aca-shared/tsconfig.lib.json
- projects/aca-shared/tsconfig.spec.json
- projects/aca-testing-shared/tsconfig.lib.json
- projects/adf-office-services-ext/tsconfig.lib.json
- projects/adf-office-services-ext/tsconfig.spec.json
- scripts/run
- src/tsconfig.app.json
- src/tsconfig.spec.json
- tsconfig.base.json
- tsconfig.json
> - [x] Bugfix
Upgrade to the solution-style tsconfig (see …
> [ACA-3593] fix library builds

- src/app.config.json
- src/app/components/files/files.component.html
- src/app/components/page.component.ts
> Fixed sorting for filters

- e2e/protractor.excludes.json
- e2e/suites/list-views/personal-files.test.ts
- src/app/components/files/files.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3848
**Does this PR …
> [ACA-3848] - change default file sorting

- .travis.yml
- protractor.conf.js
- scripts/ci/job_hooks/after_e2e.sh
- scripts/ci/job_hooks/before_e2e.sh
- scripts/ci/job_hooks/before_install.sh
- scripts/npm/lite-serve.ts
- scripts/run
https://issues.alfresco.com/jira/browse/AAE-3278
> [AAE-3278] Temporary fix for some flakyness: C297638 and C297638

- karma.conf.js
- package-lock.json
- package.json
- projects/aca-shared/karma.conf.js
- projects/adf-office-services-ext/karma.conf.js
- src/app/components/files/files.component.spec.ts
- src/app/components/files/files.component.ts
- src/app/components/shared-files/shared-files.component.spec.ts
- src/app/testing/app-testing.module.ts
> - [x] Bugfix
Fix favorites navigation …
> [ACA-3830] Fix favorites navigation

- src/app/components/files/files.component.html
- src/app/components/files/files.component.spec.ts
- src/app/components/files/files.component.ts
> - [X] Bugfix
Filter doesn't save the status
Filters save status in parameters and …
> [ACA-3506] - added refresh for filters

- src/app/components/favorites/favorites.component.html
- src/app/components/recent-files/recent-files.component.html
- src/app/components/shared-files/shared-files.component.html
- src/app/components/trashcan/trashcan.component.html
> - [x] Bugfix
[ACA-3852](https://issues.alfresco.com/jira/browse/ACA-3852)
**Does …
> [ACA-3852] Document List - sort doesn't work

- src/app/components/files/files.component.spec.ts
- src/app/components/files/files.component.ts
> - [X] Bugfix
fix go home id you are in uuuid root …
> [ACA-3855] fix go home id you are in uuuid root

- src/app/components/favorite-libraries/favorite-libraries.component.html
- src/app/components/libraries/libraries.component.html
> - [x] Bugfix
sorting does not work for "my libraries" and "favorite libraries" …
> [ACA-3852] fix client sorting issues

- angular.json
> - [ ] Bugfix
lot of warnings when starting application
the warnings are related to commonjs libraries and is …
> fix commonjs warnings for angular cli

- e2e/protractor.excludes.json
> - [ ] Bugfix
Remove excluded test …
> Remove excluded test

- src/app/services/node-actions.service.spec.ts
> - [x] Bugfix
cleanup the node selector tests
remove shared state for the tests …
> stabilize the node selector tests

- src/app.config.json
> [ACA-3857]Fix config for search-headers

- src/app/components/page.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3542
The filter sorting …
> [ACA-3542] Fix Filter Sorting Initialization

- docs/audit/audit-info-2.0.1.md
- docs/licences/license-info-2.0.1.md
- package-lock.json
- package.json
- projects/aca-shared/package.json
- projects/aca-shared/src/public-api.ts
- projects/aca-testing-shared/package.json
- projects/adf-office-services-ext/package.json
> - [ ] Bugfix
build and report fixes …
> release 2.0.1

- projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts
- src/app/components/create-menu/create-menu.component.ts
- src/app/components/viewer/viewer.component.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3730
**Does this PR …
> [ACA-3730] - Fix create menu and viewer evaluators not in sync with store values

- src/app/testing/app-testing.module.ts
> Fix failing unit tests

- projects/aca-testing-shared/src/components/data-table/data-table.ts
- src/app/components/page.component.ts
> - [x] Bugfix
[ACA-3907](https://issues.alfresco.com/jira/browse/ACA-3907)
**Does …
> [ACA-3907] Document list header should not appear on an empty list

- src/app/components/common/toggle-shared/toggle-shared.component.html
- src/app/components/common/toggle-shared/toggle-shared.component.spec.ts
- src/app/components/common/toggle-shared/toggle-shared.component.ts
> - [x] Bugfix
[ACA-3902](https://issues.alfresco.com/jira/browse/ACA-3902)
**Does …
> [ACA-3902] Toolbar - Share button doesn't have an aria-label

- e2e/suites/navigation/single-click.test.ts
- package-lock.json
- package.json
- src/app/components/files/files.component.html
- src/app/components/files/files.component.ts
- src/app/components/page.component.spec.ts
- src/app/components/page.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5257
Now that we have …
> [ADF-5257] Refactor Document list header filters

- src/app.config.json
> Add blank route to public routes

- src/app.config.json
> - [x] Bugfix
Fix placeholder …
> [ACA-3916] Fix placeholder

- e2e/suites/search/search-filters.test.ts
- package-lock.json
- package.json
- projects/aca-shared/src/lib/services/app.service.spec.ts
> - [ ] Bugfix
Unit test import missing search provider …
> Update to latest ADF and fix unit tests and broken e2e

- projects/aca-shared/rules/src/app.rules.spec.ts
- projects/aca-shared/rules/src/test-rule-context.ts
- src/app/components/context-menu/context-menu.component.spec.ts
> - [ ] Bugfix
- extra unit tests for rule evaluators
- extra typings and fixes for …
> extra unit tests

- src/app.config.json
> - [X] Bugfix
silent refresh is failing with wrong address
silent refresh is …
> [ACA-4025] - fix for silent refresh

- projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.html
- src/app/components/create-menu/create-menu.component.spec.ts
> - [ ] Bugfix
- create the unit tests for "Create Menu" …
> add "create menu" unit tests

- e2e/suites/actions-available/special-permissions/other-permissions.ts
- e2e/suites/info-drawer/library-properties.test.ts
- e2e/suites/navigation/breadcrumb.test.ts
- e2e/suites/navigation/sidebar.test.ts
- src/assets/app.extensions.json
> - [x] Bugfix
[ACA-3996](https://issues.alfresco.com/jira/browse/ACA-3996)
**Does …
> [ACA-3996] Libraries list is not re-ordered in ACA as it is in ADW

- scripts/update-version.sh
> - [x] Bugfix
- upgrade js-api if no explicit version defined
**Does this PR …
> improve update version script

- scripts/app-config-replace.js
> app/config.json Replace values instead of override

- package-lock.json
- package.json
- projects/adf-office-services-ext/src/lib/aos-extension.module.ts
- src/assets/app.extensions.json
> - [ ] Bugfix
[ACA-4026](https://alfresco.atlassian.net/browse/ACA-4026)
**Does this …
> [ACA-4026] Register plugins dynamically

- projects/aca-shared/src/lib/services/app.extension.service.spec.ts
- projects/aca-shared/src/lib/services/app.extension.service.ts
- src/assets/app.extensions.json
> - [x] Bugfix
- provide support for ordering document list columns from the …
> [ACA-4143] support ordering of document list columns

- angular.json
- extension.schema.json
- package-lock.json
- package.json
- projects/aca-about/assets/about.plugin.json
- projects/aca-about/src/lib/aca-about.module.ts
- projects/aca-settings/README.md
- projects/aca-settings/assets/settings.plugin.json
- projects/aca-settings/src/lib/settings.module.ts
- projects/adf-office-services-ext/assets/aos.plugin.json
- projects/adf-office-services-ext/src/lib/aos-extension.module.ts
- src/app/extensions.module.ts
- src/assets/app.extensions.json
> - [ ] Bugfix
- add missing "about.plugin.json" and "settings.plugin.json"
- update …
> [ACA-3775] add missing plugin configuration

- src/app/directives/library-membership.directive.spec.ts
- src/app/directives/library-membership.directive.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-880 …
> [ACS-880] Enable digital-work-space to join link to site with workspace template

- .travis.yml
- scripts/travis/deploy/publish.sh
> Fix the build path for docker

- docker/build.sh
- docker/docker-entrypoint.d/30-sed-on-appconfig.sh
- docker/run-content-ce.sh
- docker/run.sh
> Fix app.config.json expansion

- scripts/app-config-replace.js
> Fix typo for replacing identity host

- e2e/protractor.excludes.json
- e2e/suites/list-views/empty-list.test.ts
> [ACA-4167] Remove e2e as they are not compatible anymore with the live env

- Dockerfile
- docker/default.conf.template
- docker/run-content-ce.sh
> AAE-4023 fix BASE_PATH as /

- docker/docker-entrypoint.d/30-sed-on-appconfig.sh
> Remove the else ecmhost condition

- docker/default.conf.template
> AAE-4023 return 200 on root regardless of BASE_PATH

- src/assets/i18n/it.json
> - [ ] Other... Please describe: Please use this Italian file for ACA which has the amended terms for "Library" …
> FIXED Italian file for consistency with term "Library"

- e2e/suites/list-views/empty-list.test.ts
- src/app/components/files/files.component.spec.ts
- src/app/components/shared-files/shared-files.component.html
- src/app/components/shared-files/shared-files.component.spec.ts
- src/app/directives/document-list.directive.spec.ts
> - [ ] Bugfix
- automate a manual regression case for Shared Links and pagination …
> unit tests for manual regression cases

- e2e/protractor.excludes.json
> - [ ] Bugfix
include C269007 …
> include C269007

- src/app/app.component.ts
> readding wrongly removed check:

- src/app/components/viewer/viewer.component.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4202 …
> [ACA-4202] User cannot see updated preview when updating with the same node name as the current one

- docs/README.md
- docs/audit/audit-info-2.2.0.md
- docs/licences/license-info-2.2.0.md
- package-lock.json
- package.json
- projects/aca-about/package.json
- projects/aca-settings/package.json
- projects/aca-shared/package.json
- projects/aca-testing-shared/package.json
- projects/adf-office-services-ext/package.json
- scripts/generate-reports.sh
- scripts/update-package-version.sh
- src/app.config.json
> - [ ] Bugfix
- new: script to update all package versions
- new: script to generate …
> Release 2.2.0

- .travis.yml
- e2e/protractor.excludes.json
- e2e/suites/authentication/login.test.ts
- projects/aca-testing-shared/src/pages/browsing-page.ts
- projects/aca-testing-shared/src/pages/login-page.ts
> [ACA-4242] Update e2e login method to account for the changes done for ACA-4197

- projects/aca-shared/store/src/actions/viewer.actions.ts
- src/app/components/viewer/viewer.component.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-970 …
> [ACS-970] Added a new action for the viewer to reload the current node.

- projects/aca-testing-shared/src/pages/browsing-page.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-1129 …
> [ACS-1129] fix signOut method to work for SSO as well

- package-lock.json
- package.json
- scripts/ci/job_hooks/after_e2e.sh
- scripts/ci/job_hooks/before_e2e.sh
> - [ ] Bugfix
The environment will be scanned before and after each E2E job in Travis …
> [ACA-4232] Call the scan-env adf-cli command before and after each E2E job

- e2e/protractor.excludes.json
> - [ ] Bugfix
delete test C213107 from exclude file
https://alfresco.atlassian.net/browse/ACA-4197 …
> [ACA-4197] delete test C213107 from exclude file

- e2e/protractor.excludes.json
> [ACA-4253] Exclude flaky tests

- src/app.config.json
> Add the login route as part of app.config

- src/app/components/common/logout/logout.component.spec.ts
- src/app/components/common/logout/logout.component.ts
> [ACS-1198] - Use the redirectLogout route in case of sso

- e2e/resources/extensibility-configs/context-submenus-ext.json
- e2e/resources/extensibility-configs/document-presets-ext.json
- e2e/resources/extensibility-configs/header-ext.json
- e2e/resources/extensibility-configs/info-drawer-ext.json
- e2e/resources/extensibility-configs/info-drawer-no-tabs-ext.json
- e2e/resources/extensibility-configs/metadata-ext.json
- e2e/resources/extensibility-configs/viewer-ext.json
- src/app.config.json
- src/assets/app.extensions.json
> - [ ] Bugfix
enable email aspect, a new use case will be created to correctly address the read-only scenario
**What …
> Enable email aspect

- docs/tutorials/how-to-create-your-first-extension.md.yaml
> - [ ] Bugfix
N/A
N/A
**Does this PR introduce a breaking change?** (check one with …
> Type on the tutorial

- package-lock.json
- package.json
Update ADF packages version 4.3.0-beta8
> Update ADF packages version 4.3.0-beta8

- package-lock.json
- package.json
- scripts/ci/job_hooks/before_e2e.sh
- src/app/components/common/logout/logout.component.spec.ts
- src/app/components/common/logout/logout.component.ts
> Use the adf-logout latest version

- package-lock.json
- package.json
* Update protractor-retry-angular-cli to 2.0.2 version
> - [ ] Bugfix
> - [x] Other... Please describe: Add protractor-retry-angular-cli for ACA
**What …
> [AAE-4551] Add protractor-retry-angular-cli for ACA

- e2e/protractor.excludes.json
> [ACA-4283] Exclude flaky createActions test

- scripts/ci/job_hooks/before_install.sh
> - [ ] Bugfix
Remove obscure ADF JS-API Update …
> Remove obscure ADF JS-API Update

- .github/dependabot.yml
> - [ ] Bugfix
add certain libs to the dependabot ignore list to avoid CI/CD spamming …
> configure dependabot excludes

- .github/dependabot.yml
> - [ ] Bugfix
Add Alfresco in the ignore list of dependabot …
> Add Alfresco in the ignore list of dependabot

- e2e/smartrunner-factory.js
- package-lock.json
- package.json
- protractor.conf.js
https://alfresco.atlassian.net/browse/AAE-4608
> [AAE-4608] Use smartrunner version 2

- src/app/components/files/files.component.spec.ts
- src/app/components/info-drawer/comments-tab/comments-tab.component.spec.ts
- src/app/components/recent-files/recent-files.component.spec.ts
- src/app/components/search/search-input/search-input.component.spec.ts
- src/app/components/search/search-results-row/search-results-row.components.spec.ts
- src/app/components/toolbar/document-display-mode/document-display-mode.component.spec.ts
- src/app/components/toolbar/document-display-mode/document-display-mode.component.ts
- src/app/components/toolbar/toggle-info-drawer/toggle-info-drawer.component.spec.ts
- src/app/components/trashcan/trashcan.component.spec.ts
- src/app/services/content-management.service.spec.ts
- src/app/services/node-actions.service.spec.ts
- src/app/services/node-actions.service.ts
> - [ ] Bugfix
ACa unit test unstable
Stabilising unit test …
> Stabilising unit test for ACA

- scripts/ci/job_hooks/before_e2e.sh
See the changeset and be enlightened...
> Remove temporarily added npm ci, since Travis has been fixed

- e2e/protractor.excludes.json
- e2e/suites/viewer/viewer-actions.test.ts
> [ACA-2176] Reenable C286314  test

- src/app/components/page.component.spec.ts
- src/app/components/page.component.ts
- src/app/components/toolbar/view-node/view-node.component.spec.ts
- src/app/components/toolbar/view-node/view-node.component.ts
> - [x] Bugfix
[ACA-2923](https://alfresco.atlassian.net/browse/ACA-2923)
**Does this …
> [ACA-2923] Viewer - type link node is not not displaying 

- e2e/protractor.excludes.json
- e2e/suites/actions/create/create-file-from-template.test.ts
- e2e/suites/actions/edit/edit-offline.test.ts
> [ACA-4196] [ACA-4219] [ACA-4283] Delete some tests and reinclude some others

- src/app/store/effects/node.effects.spec.ts
- src/app/store/effects/node.effects.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4323 …
> [ACA-4323] Can't add aspects to a folder in ACA/ADW

- package-lock.json
- package.json
> Update adf 31741 and js api 4.3.0

- docs/audit/audit-info-2.3.0.md
- docs/licences/license-info-2.3.0.md
- package-lock.json
- package.json
- projects/aca-about/package.json
- projects/aca-settings/package.json
- projects/aca-shared/package.json
- projects/aca-testing-shared/package.json
- projects/adf-office-services-ext/package.json
- src/app.config.json
> ACA 2.3.0 with ADF 4.3.0

- package-lock.json
- package.json
> Update branch for ADF 31786 and JS-API 4.3.0

- extension.schema.json
- src/app/components/sidenav/sidenav.component.html
- src/app/components/sidenav/sidenav.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4355 …
> [ACA-4355][ADW] The Process Management section becomes invisible on logout

- .travis.yml
- scripts/travis/deploy/publish.sh
> Run the unit/build/e2e/docker based on the agreed doc

- e2e/suites/actions/library/library-actions.test.ts
- projects/aca-testing-shared/src/components/dialog/create-edit-folder-dialog.ts
- projects/aca-testing-shared/src/components/dialog/create-from-template-dialog.ts
- projects/aca-testing-shared/src/components/dialog/create-library-dialog.ts
- projects/aca-testing-shared/src/components/search/filters/facet-filter.ts
- protractor.conf.js
> - [ ] Bugfix
use selectors that are valid for both ACA and ADW
**Does this PR …
> [ACA-3908] use different selectors that are valid for ADW as well

- e2e/protractor.excludes.json
> [SEARCH-2590] Exclude tests

- .travis.yml
- scripts/ci/job_hooks/after_e2e.sh
- scripts/ci/job_hooks/before_e2e.sh
> - [ ] Bugfix
Scan environment will only run on cron. …
> [ACS-1524] Remove environment scan

- package-lock.json
> - [ ] Bugfix
npm audit fixes …
> audit fixes

- src/app/components/viewer/viewer.component.ts
> [ACS-1519] - Fixed double loading of the viewer

- projects/aca-testing-shared/src/components/data-table/data-table.ts
> - [ ] Bugfix
current selector does not work for adw
change selector to one that is …
> [ACA-3908] improve selector to be valid for ADW as well

- angular.json
- package-lock.json
- package.json
> - [ ] Bugfix
https://github.com/Alfresco/alfresco-ng2-components/pull/6958
added …
> [ADF-5379] Add CropperJS dependency

- angular.json
- package-lock.json
- package.json
- projects/aca-shared/store/src/actions/upload.actions.ts
- src/app/components/layout/app-layout/app-layout.component.scss
- src/app/components/viewer/viewer.component.html
- src/app/components/viewer/viewer.component.ts
- src/app/store/effects/upload.effects.spec.ts
- src/app/store/effects/upload.effects.ts
- src/assets/i18n/en.json
> - [ ] Bugfix
Draft PR in order for team members to test/demo. …
> [ADF-5378] Rotate image: auto increment version on submit

- docs/extending/redistributable-libraries.md
- docs/ja/extending/redistributable-libraries.md
- docs/tutorials/how-to-create-your-first-extension.md
- package-lock.json
- package.json
> - [x] Bugfix
- remove unused `cpr` dependency
- fix high security issues
with this …
> Fix security issues and remove cpr dependency

- package-lock.json
- package.json
> Update branch for ADF 32383 and JS-API 4.4.0-3425

- docs/extending/application-features.md
- extension.schema.json
- projects/aca-shared/src/lib/models/viewer.rules.ts
- projects/aca-shared/src/lib/services/app.extension.service.ts
- src/app/components/viewer/viewer.component.ts
- src/assets/app.extensions.json
> - [ ] Bugfix
As a extension user, I should be able to control the viewer options
new …
> [ACA-3897] Extendable viewer navigation

- projects/aca-testing-shared/src/components/component.ts
- projects/aca-testing-shared/src/components/menu/menu.ts
- projects/aca-testing-shared/src/components/toolbar/toolbar.ts
> [ACA-3908] get Copy action by title to solve problem from ADW run

- docs/ja/getting-started/cors.md
> Modify Japanese translation for CORS docs.

- e2e/protractor.excludes.json
- e2e/suites/actions-available/libraries/library.test.ts
> [ACA-4419] Exclude C326685 test

- package-lock.json
- package.json
> - [ ] Bugfix
[ADF-5396](https://alfresco.atlassian.net/browse/ADF-5396)
**Does this …
> remove cropper

- src/app/app.routes.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4430 …
> [ACA-4430] Add missing viewer routes for Viewing a previous version of a file in Libraries

- e2e/suites/actions-available/libraries/test-data-libraries.ts
- src/assets/app.extensions.json
> - [x] Bugfix
[ACA-4339](https://alfresco.atlassian.net/browse/ACA-4339)
**Does this …
> [ACA-4339] Library actions - Delete

- docs/ja/getting-started/sso.md
> Modify Japanese translation for SSO.

- docs/ja/getting-started/navigation.md
> Modify Japanese translation for Navigation.

- docs/ja/tutorials/how-to-create-your-first-extension.md
- docs/ja/tutorials/how-to-install-an-existing-extension.md
- docs/ja/tutorials/introduction-to-extending.md
> Modify Japanese translation for Extending

- docs/ja/README.md
> Modify Japanese translation for README

- e2e/suites/viewer/viewer-actions.test.ts
- projects/aca-testing-shared/src/components/viewer/viewer.ts
- src/app/components/layout/app-layout/app-layout.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4432 …
> [ACA-4432] Upload Dialog overlaps Upload New Version dialog

- src/assets/i18n/ar.json
- src/assets/i18n/cs.json
- src/assets/i18n/da.json
- src/assets/i18n/de.json
- src/assets/i18n/es.json
- src/assets/i18n/fi.json
- src/assets/i18n/fr.json
- src/assets/i18n/it.json
- src/assets/i18n/ja.json
- src/assets/i18n/nb.json
- src/assets/i18n/nl.json
- src/assets/i18n/pl.json
- src/assets/i18n/pt-BR.json
- src/assets/i18n/ru.json
- src/assets/i18n/sv.json
- src/assets/i18n/zh-CN.json
> - [X ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ NA] Tests for the changes have been added (for bug fixes / features)
> - [NA ] Docs have been added / updated (for bug fixes / features)
> - [ ] Bugfix
> - [ x] Other... Please describe: Update to UI strings for the IPTC content (media)
**Does this PR …
> LOC-303 - Media strings for ACA in 16 languages

- package-lock.json
- package.json
- src/app/services/node-actions.service.spec.ts
- src/app/services/node-actions.service.ts
- src/app/services/node-template.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-5145
Uses the new enumeration …
> [AAE-5145] Update node actions to use enum

- src/app/components/sidenav/sidenav.component.html
- src/app/components/sidenav/sidenav.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-1636 …
> [ACS-1636] Make SideNav Create New Button steady

- projects/aca-about/src/lib/about.component.ts
- projects/aca-shared/src/lib/components/page-layout/page-layout.component.ts
- projects/aca-shared/src/lib/components/tool-bar/toolbar-button/toolbar-button.component.ts
- projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.ts
- projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.ts
- src/app/components/context-menu/context-menu-item.component.ts
- src/app/components/create-menu/create-menu.component.ts
- src/app/components/details/details.component.html
- src/app/components/details/details.component.scss
- src/app/components/details/details.component.ts
- src/app/components/dl-custom-components/name-column/name-column.component.ts
- src/app/components/header/header.component.ts
- src/app/components/preview/preview.component.ts
- src/app/components/search/search-input/search-input.component.ts
- src/app/components/shared-link-view/shared-link-view.component.ts
- src/app/dialogs/node-template/create-from-template.dialog.ts
> - [x] Bugfix
this is the prerequisite for the Angular 11/12 upgrades
- fix …
> [ADF-5407] style fixes before Angular 12 upgrade

- projects/aca-testing-shared/src/utilities/repo-client/apis/favorites/favorites-api.ts
- projects/aca-testing-shared/src/utilities/repo-client/apis/nodes/nodes-api.ts
> [ACA-3611] Add parentFolderId variable to getNodeByPath()

- package-lock.json
- package.json
- protractor.conf.js
> - [ ] Bugfix
Remove ora not used dependency …
> Remove ora not used dependency

- src/app/components/search/search-input/search-input.component.spec.ts
- src/app/components/search/search-input/search-input.component.ts
- src/assets/i18n/en.json
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-3541
snackbar with error …
> [ACA-3541] show error message on empty search

- e2e/suites/list-views/empty-list.test.ts
- src/app.config.json
- src/app/components/search/search-results/search-results.component.html
- src/app/components/search/search-results/search-results.component.scss
- src/app/components/search/search-results/search-results.component.spec.ts
- src/app/components/search/search-results/search-results.component.ts
- src/assets/i18n/en.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ADF-5419 …
> [ADF-5419][aca] support multiple search form

- scripts/travis/deploy/publish.sh
> Fix @alfresco

- e2e/e2e-config/utils/upload-output.js
> fix e2e uploadOutput error

- src/app/components/search/search-results/search-results.component.scss
> Fixed space between preview icon

- src/assets/app.extensions.json
- src/assets/i18n/en.json
> - [ ] Bugfix
> - [ X] Feature
A single configuration for search is showed
Now 3 configurations are …
> [ACA-4506] - added 2 configurations for Dublin Core and Effectivity

- protractor.conf.js
> - [] Bugfix
Fix retry screenshot …
> Fix retry screenshot

- src/assets/i18n/ar.json
- src/assets/i18n/cs.json
- src/assets/i18n/da.json
- src/assets/i18n/de.json
- src/assets/i18n/es.json
- src/assets/i18n/fi.json
- src/assets/i18n/fr.json
- src/assets/i18n/it.json
- src/assets/i18n/ja.json
- src/assets/i18n/nb.json
- src/assets/i18n/nl.json
- src/assets/i18n/pl.json
- src/assets/i18n/pt-BR.json
- src/assets/i18n/ru.json
- src/assets/i18n/sv.json
- src/assets/i18n/zh-CN.json
> - [ na] Tests for the changes have been added (for bug fixes / features)
> - [na ] Docs have been added / updated (for bug fixes / features)
> - [ ] Bugfix
> - [ x] Other... Please describe: Updated UI files in 16 languages …
> LOC-318 - Updated files for ACA 2.3 in 16 languages

- e2e/e2e-config/utils/upload-output.js
- e2e/suites/actions-available/files-folders/folders-actions.test.ts
- e2e/suites/actions-available/files-folders/locked-files-actions.test.ts
- e2e/suites/actions-available/files-folders/multiple-files-actions.test.ts
- projects/aca-testing-shared/src/utilities/repo-client/apis/search/search-api.ts
- projects/aca-testing-shared/src/utilities/user-actions.ts
- protractor.conf.js
> - [ ] Bugfix
Flaky test fixes
https://alfresco.atlassian.net/browse/ACA-4507
**Does …
> [ACA-4507] Fix folder tests

- e2e/suites/search/search-sorting.test.ts
- projects/aca-testing-shared/src/components/search/search-sorting-picker.ts
- src/app/components/search/search-action-menu/search-action-menu.component.html
- src/app/components/search/search-action-menu/search-action-menu.component.spec.ts
- src/app/components/search/search-action-menu/search-action-menu.component.ts
- src/app/components/search/search-results.module.ts
- src/app/components/search/search-results/search-results.component.html
- src/app/components/search/search-results/search-results.component.ts
- src/assets/i18n/en.json
> - [ ] Bugfix
Search sorting is using a select element
Old search sorting component …
> [ACA-4492] - Start restyling of search sorting

- .travis.yml
- package-lock.json
- package.json
- projects/aca-shared/src/lib/services/app.service.spec.ts
- projects/aca-shared/src/lib/services/content-api.service.ts
- src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.spec.ts
- src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.ts
- src/app/components/libraries/libraries.component.spec.ts
- src/app/components/search/search-libraries-results/search-libraries-query-builder.service.spec.ts
- src/app/components/search/search-libraries-results/search-libraries-query-builder.service.ts
- src/app/components/search/search-results/search-results.component.spec.ts
- src/app/components/shared-link-view/shared-link-view.component.spec.ts
- src/app/components/shared-link-view/shared-link-view.component.ts
- src/app/components/toolbar/toggle-edit-offline/toggle-edit-offline.component.ts
- src/app/components/toolbar/toggle-favorite-library/toggle-favorite-library.component.spec.ts
- src/app/components/toolbar/toggle-join-library/toggle-join-library.component.spec.ts
- src/app/components/trashcan/trashcan.component.spec.ts
- src/app/components/viewer/viewer.component.ts
- src/app/services/node-actions.service.spec.ts
- src/app/services/node-actions.service.ts
- src/app/services/node-template.service.spec.ts
- src/app/services/node-template.service.ts
- src/app/store/app-store.module.ts
- src/app/store/bootstrap-effect.ts
- src/app/store/effects/template.effects.spec.ts
- src/app/store/effects/template.effects.ts
> - [ ] Bugfix
Remove old compatibility layer …
> [ADF-5429] Remove old compatibility layer

- src/app/components/files/files.component.html
> - [x] Bugfix
Improve reload
Document list flashes  `no content`  for few seconds and shows loader
What is problem:- …
> [ACA-1918] Improve reload

- projects/aca-shared/src/lib/services/content-api.service.ts
- src/app/dialogs/node-versions/node-versions.dialog.html
- src/app/dialogs/node-versions/node-versions.dialog.spec.ts
- src/app/dialogs/node-versions/node-versions.dialog.ts
- src/app/services/content-management.service.spec.ts
- src/app/services/content-management.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-3669
fixed
**Does this PR …
> [ACA-3669] Incorrect Version Number Displayed

- projects/aca-shared/src/lib/services/app.extension.service.spec.ts
- projects/aca-shared/src/lib/services/app.extension.service.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACA-4226 …
> [ACA-4226] Fix rule enabling in extensions

- docs/abn-tree.yml
- docs/extending/extensibility-features.md
- docs/tutorials/README.md
- docs/tutorials/custom-viewer.md
> - [x] Bugfix
Viewer tutorial …
> Viewer tutorial

- docs/audit/audit-info-2.6.0.md
- docs/licences/license-info-2.6.0.md
- package-lock.json
- package.json
- projects/aca-about/package.json
- projects/aca-settings/package.json
- projects/aca-shared/package.json
- projects/aca-testing-shared/package.json
- projects/adf-office-services-ext/package.json
> - [ ] Bugfix
release preparation  …
> Release 2.6.0

- projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.spec.ts
- projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts
- projects/aca-shared/src/lib/components/tool-bar/toolbar-button/toolbar-button.component.html
- projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.html
- projects/aca-shared/src/lib/services/app.extension.service.spec.ts
- projects/aca-shared/src/lib/services/app.extension.service.ts
- src/app/components/context-menu/context-menu.component.spec.ts
- src/app/components/context-menu/context-menu.component.ts
- src/app/components/create-menu/create-menu.component.spec.ts
- src/app/components/create-menu/create-menu.component.ts
- src/app/components/header/header.component.spec.ts
- src/app/components/header/header.component.ts
- src/app/components/page.component.ts
- src/app/components/preview/preview.component.ts
- src/app/components/shared-link-view/shared-link-view.component.spec.ts
- src/app/components/shared-link-view/shared-link-view.component.ts
- src/app/components/viewer/viewer.component.ts
Reverts Alfresco/alfresco-content-app#2296
> Revert "[AAE-5874] Re-evaluate extension rules when context changes"

- projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.spec.ts
- projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts
- projects/aca-shared/src/lib/components/tool-bar/toolbar-button/toolbar-button.component.html
- projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.html
- projects/aca-shared/src/lib/services/app.extension.service.spec.ts
- projects/aca-shared/src/lib/services/app.extension.service.ts
- src/app/components/context-menu/context-menu.component.spec.ts
- src/app/components/context-menu/context-menu.component.ts
- src/app/components/create-menu/create-menu.component.spec.ts
- src/app/components/create-menu/create-menu.component.ts
- src/app/components/header/header.component.spec.ts
- src/app/components/header/header.component.ts
- src/app/components/page.component.ts
- src/app/components/preview/preview.component.ts
- src/app/components/shared-link-view/shared-link-view.component.spec.ts
- src/app/components/shared-link-view/shared-link-view.component.ts
- src/app/components/viewer/viewer.component.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-5874 …
> [AAE-5874] Re-evaluate extension rules when context changes

- docs/tutorials/search-form.md
- extension.schema.json
- projects/aca-shared/src/lib/services/app.extension.service.spec.ts
- projects/aca-shared/src/lib/services/app.extension.service.ts
> - [ ] Bugfix
Support rule for search forms …
> [MNT-22574] Support rules for search forms

- scripts/generate-reports.sh
> - [ ] Bugfix
include "changelog" generation as part of the release reports
**Does …
> [ACS-2197] add changelog report generation

- docs/audit/audit-info-2.7.0.md
- docs/changelog/changelog-2.7.0.md
- docs/licences/license-info-2.7.0.md
- package-lock.json
- package.json
- projects/aca-about/package.json
- projects/aca-settings/package.json
- projects/aca-shared/package.json
- projects/aca-testing-shared/package.json
- projects/adf-office-services-ext/package.json
- src/app.config.json
> Release 2.7.0

- src/app/components/create-menu/create-menu.component.spec.ts
- src/app/components/main-action/main-action.component.html
- src/app/components/main-action/main-action.component.spec.ts
- src/app/components/main-action/main-action.component.ts
- src/app/testing/app-extension-service-mock.ts
- src/app/testing/content-action-ref.ts
> [AAE-6309] Cleaning process references

- src/app/components/create-menu/create-menu.component.scss
- src/app/components/main-action/main-action.component.html
- src/app/components/main-action/main-action.component.scss
- src/app/components/main-action/main-action.component.spec.ts
- src/app/components/main-action/main-action.component.ts
- src/app/components/main-action/main-action.module.ts
- src/app/components/sidenav/sidenav.component.html
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-6309 …
> [AAE-6309] Fix for displaying main action on collapsed menu

- src/app/components/main-action/main-action.component.html
> [AAE-6309] Adding missing ids to main action

- .travis.yml
- angular.json
- package.json
- scripts/ci/jobs/affected-project-with.sh
> [AAE-6455] - Rename the dist folder to content-ce and use env

- .travis.yml
- angular.json
- karma.conf.js
- package.json
- projects/aca-about/karma.conf.js
- projects/aca-settings/karma.conf.js
- projects/aca-shared/karma.conf.js
- projects/adf-office-services-ext/karma.conf.js
> [AAE-6555] Rename the app into content-ce

- app/tsconfig.app.json
> Fix the typo

- app/src/app.config.json.tpl
- app/src/app/app.component.ts
- app/src/app/store/initial-state.ts
- projects/aca-shared/store/src/selectors/app.selectors.ts
- projects/aca-shared/store/src/states/app.state.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-6811 …
> [AAE-6811] Load custom theme

- Dockerfile
- docker/docker-entrypoint.d/30-sed-on-appconfig.sh
- docker/run.sh
> - [x] Bugfix
add missing `APP_CONFIG_PROVIDER` defaults for the Docker
**Does this …
> add missing PROVIDER env variable for docker

- e2e/suites/actions/library/library-actions.test.ts
- projects/aca-testing-shared/src/components/search/search-input.ts
- projects/aca-testing-shared/src/utilities/user-actions.ts
> - [ ] Bugfix
> - [x]  e2e test improvement
https://alfresco.atlassian.net/browse/ACA-4546 …
> [ACA-4546] Flaky ACA `Library actions` test

- e2e/suites/info-drawer/file-folder-properties.test.ts
- projects/aca-testing-shared/src/components/info-drawer/info-drawer.ts
- projects/aca-testing-shared/src/components/search/search-input.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Automated manual test …
> [AAE-7355] automate manual C599174

- app/src/app/components/search/search-input-control/search-input-control.component.scss
- app/src/app/ui/dynamic-theme/custom-background-color.scss
- app/src/app/ui/dynamic-theme/custom-text-color.scss
- app/src/app/ui/dynamic-theme/custom-theme.scss.tpl
- app/src/app/ui/dynamic-theme/theme-configuration.scss.tpl
- package-lock.json
- package.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-6822 …
> [AAE-6822] Customize background and text colors

- e2e/suites/actions/upload-download/upload-file.test.ts
- e2e/suites/viewer/viewer-actions.test.ts
- projects/aca-testing-shared/src/components/dialog/index.ts
- projects/aca-testing-shared/src/components/dialog/upload-files-dialog.ts
- projects/aca-testing-shared/src/pages/page.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-7154
e2e test is shared …
> [AAE-7154] Automate upload file dialog

- app/src/app/ui/dynamic-theme/custom-theme.scss.tpl
- app/src/app/ui/dynamic-theme/theme-configuration.scss.tpl
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-6808 …
> [AEE-6808] Align theme props with modelling app

- app/src/app.config.json.tpl
- app/src/app/app.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-6808 …
> [AAE-6808] Fix for loading external font

- e2e/protractor.excludes.json
- e2e/suites/list-views/sort-list.test.ts
- projects/aca-testing-shared/src/components/data-table/data-table.ts
- projects/aca-testing-shared/src/utilities/user-actions.ts
> - [ ] Bugfix
> - [x] Other... Please describe: automating manual tests …
> [AAE-7448] Automate remember sorting

- e2e/suites/info-drawer/file-preview.test.ts
- projects/aca-testing-shared/src/components/info-drawer/info-drawer.ts
- projects/aca-testing-shared/src/components/search/search-input.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Automate manual test  …
> [AAE-7660] file preview from info drawer

- projects/aca-shared/src/lib/components/tool-bar/toolbar-action/toolbar-action.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-7832 …
> [AAE-7832] Custom header text colour is not applied to user name

- .travis.yml
- scripts/trigger-travis.sh
> Fix upstream

- app/src/assets/i18n/ar.json
- app/src/assets/i18n/cs.json
- app/src/assets/i18n/da.json
- app/src/assets/i18n/de.json
- app/src/assets/i18n/es.json
- app/src/assets/i18n/fi.json
- app/src/assets/i18n/fr.json
- app/src/assets/i18n/it.json
- app/src/assets/i18n/ja.json
- app/src/assets/i18n/nb.json
- app/src/assets/i18n/nl.json
- app/src/assets/i18n/pl.json
- app/src/assets/i18n/pt-BR.json
- app/src/assets/i18n/ru.json
- app/src/assets/i18n/sv.json
- app/src/assets/i18n/zh-CN.json
> - [ x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Bugfix
> - [ x] Other... Please describe: Updated UI files for ACA 2.6 release in 16 languages
**Does this PR …
> LOC-360 full fix - Updated UI files for ACA 2.6 release in 16 languages

- app/src/app.config.json.tpl
- docs/audit/audit-info-2.9.0.md
- docs/changelog/changelog-2.9.0.md
- docs/licences/license-info-2.9.0.md
- package-lock.json
- package.json
- projects/aca-about/package.json
- projects/aca-settings/package.json
- projects/aca-shared/package.json
- projects/aca-testing-shared/package.json
- projects/adf-office-services-ext/package.json
> - [ ] Bugfix
release 2.9.0
**Does this PR introduce a breaking change?** (check one …
> [ACS-2698] release 2.9.0

- .eslintignore
- app/src/app/components/info-drawer/info.drawer.module.ts
- app/src/app/components/toolbar/toolbar.module.ts
- app/src/app/extensions/core.extensions.module.ts
- package-lock.json
- package.json
> - [ ] Bugfix
- fix ESLint warnings
- ESLint performance improvements
**Does this PR …
> [AAE-7238] fix performance issues and warnings in app

- e2e/protractor.excludes.json
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4578 …
> [ACA-4578] Exclude e2e connected to datatable sorting

- e2e/protractor.excludes.json
- projects/aca-testing-shared/src/components/data-table/data-table.ts
> - [x] Bugfix
Tests are excluded
https://alfresco.atlassian.net/browse/ACA-4578 …
> [ACA-4578] Fix for datatable e2e-s

- .eslintrc.json
- package-lock.json
- package.json
> - [ ] Bugfix
> - [X] Build related changes
Ban non desired words such as fdescribe, fit, xit,... in the linting …
> Add eslint ban rule

- e2e/suites/viewer/viewer-actions.test.ts
> Remove useless duplicated flaky e2es

- app/src/app.config.json.tpl
- docs/audit/audit-info-2.11.0.md
- docs/changelog/changelog-2.11.0.md
- docs/licences/license-info-2.11.0.md
- package-lock.json
- package.json
- projects/aca-about/package.json
- projects/aca-settings/package.json
- projects/aca-shared/package.json
- projects/aca-testing-shared/package.json
- projects/adf-office-services-ext/package.json
> - [ ] Bugfix
> - [x] Other... Please describe: Release
https://alfresco.atlassian.net/browse/ACS-3109
**Does this PR …
> [ACS-3109] Release 2.11.0

- projects/aca-shared/src/lib/services/app.extension.service.spec.ts
- projects/aca-shared/src/lib/services/app.extension.service.ts
…olumns
> - [ ] Bugfix
**Does this PR introduce a breaking change?** (check one with …
> APPS-1568 : ACA should be extended to support visibility rules for Document List columns.

- README.md
> - [ ] Bugfix
- add requirements and steps on how to run the app
- cleanup the doc …
> refine readme file

- app/src/app/app.module.ts
- app/src/app/app.routes.ts
- app/src/app/components/view-profile/view-profile.component.html
- app/src/app/components/view-profile/view-profile.component.scss
- app/src/app/components/view-profile/view-profile.component.ts
- app/src/app/components/view-profile/view-profile.module.ts
- app/src/app/ui/variables/variables.scss
- app/src/assets/i18n/en.json
> ACA-4600-Added-Edit-profile-capabilities-for-user

- Dockerfile
> - [ ] Bugfix
upgrade to later node version for Docker images
**Does this PR …
> upgrade node.js for docker images

- app/src/app/app.routes.ts
> [AAE-10029] - Change auth guard to support BPM configuration

- app/src/app/app.module.ts
- app/src/app/app.routes.ts
- app/src/app/components/view-profile/view-profile.component.html
- app/src/app/components/view-profile/view-profile.component.scss
- app/src/app/components/view-profile/view-profile.component.ts
- app/src/app/components/view-profile/view-profile.module.ts
- app/src/app/ui/variables/variables.scss
- app/src/assets/i18n/en.json
> ACA-4600-Edit-profile-functionality

- app/src/app/components/header/header.component.spec.ts
> - [ ] Bugfix
fix various warnings when running karma tests …
> fix test warnings for karma

- docs/audit/audit-info-3.0.0.md
- docs/changelog/changelog-3.0.0.md
- docs/licences/license-info-3.0.0.md
- package-lock.json
- package.json
> - [ ] Bugfix
release steps for 3.0.0 …
> Release 3.0.0

- projects/aca-folder-rules/assets/i18n/en.json
- projects/aca-folder-rules/src/lib/folder-rules.module.ts
- projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html
- projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.scss
- projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.spec.ts
- projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.ts
- projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html
- projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.spec.ts
- projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
> - [ ] Bugfix
There is no "options" section on create / update rule dialog
Options …
> [ACS-3259] Create / Update rule dialog - options section

- app/src/app/app.component.spec.ts
- app/src/app/app.component.ts
- app/src/app/components/sidenav/components/expand-menu.component.html
> - [x] Bugfix
"Personal files" screen has some accessibility issue.
Accessibility …
> [ACS-3537] - Fix accessibility issues in personal files

- app/src/app/components/common/location-link/location-link.component.ts
> - [x] Bugfix
"Trashcan" screen has some accessibility issues.
Accessibility issues …
> ACS-3544 Fix accessibility issues in trashcan

- app/src/app/app.routes.ts
- app/src/app/components/view-profile/view-profile.guard.ts
> ACA-4615 : Restrict Edit Profile functionality to ECM users only

- app/src/app/app.component.html
heading was not present that gives Headings should not be empty issue …
> [ACS-3548] heading added to resolve heading accessibility issue

- app/src/app/components/view-profile/view-profile.guard.ts
> ACA-4615 view profile functionality should also be visible for SSO users

- projects/aca-folder-rules/assets/i18n/en.json
- projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
- projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
- projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts
- projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html
- projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
- projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts
- projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
> - [ ] Bugfix
There is currently no way to update existing rules.
Update rule …
> [ACS-3511] Update rules

- projects/aca-shared/rules/src/app.rules.spec.ts
- projects/aca-shared/rules/src/app.rules.ts
- projects/aca-shared/rules/src/record.rules.ts
- projects/adf-office-services-ext/src/lib/evaluators.spec.ts
- projects/adf-office-services-ext/src/lib/evaluators.ts
> - [x] Bugfix
"Edit Offline" and "Upload New Version" respect the "record management" …
> [MNT-22754] fix context menus for records

- app/src/app/components/files/files.component.html
- app/src/app/components/search/search-libraries-results/search-libraries-results.component.html
- app/src/app/components/search/search-results/search-results.component.html
- app/src/app/ui/theme.scss
- projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.html
> - [x] Bugfix
Accessibility issues exists.
Added required roles, buttons, focus fixes …
> [ACS-3552] Accessibility fixes for CSV file issues

- app/src/app/app.component.html
- app/src/app/components/details/details.component.html
- app/src/assets/i18n/en.json
> - [ x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
accessibility issues were present
accessibility issues fixed 
**Does …
> [ACS-3548] accessibility issues fixed for ACS-3548

- app/src/app/app.component.html
- app/src/app/components/details/details.component.html
- app/src/assets/i18n/en.json
Aria-level and role was not present
Aria-level and role added 
**Does …
> [ACS-3548] aria-level issue resolved for accessibility in details component

- e2e/protractor.excludes.json
> - [ ] Bugfix
exclude the flaky e2e …
> exclude flaky e2e: C306959

- app/src/app/services/content-management.service.ts
> - [x] Bugfix
a11y issues of create new folder dialog not fixed
a11y issues of create …
> [ACS-3546] Fix for Create new folder a11y

- app/src/app/app.routes.ts
- app/src/assets/i18n/en.json
> - [x] Bugfix
The <title> element on this page does not identify the contents or purpose of the page
**What is the …
> [acs-3548] fixed csv file issues(878577)

- tsconfig.adf.json
> [AAE-10984]: add path alias for adf auth second entry module

- app/src/assets/i18n/en.json
- projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.html
- projects/aca-shared/src/lib/components/info-drawer/shared-info-drawer.module.ts
> - [x] Bugfix
Accessibility issue for metadata sidebar because of missing aria-label.  …
> [ACS-3545] a11y aca metadata sidebar

- app/src/app/ui/theme.scss
> - [x] Bugfix
Raised buttons don't have new focus.
Raised buttons are correctly …
> [ACA-4622] Add focus for raised buttons

- projects/aca-folder-rules/assets/i18n/en.json
- projects/aca-folder-rules/src/lib/folder-rules.module.ts
- projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
- projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss
- projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts
- projects/aca-folder-rules/src/lib/model/rule.model.ts
- projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html
- projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.scss
- projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.spec.ts
- projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.ts
- projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html
- projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.scss
- projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.spec.ts
- projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
- projects/aca-folder-rules/src/lib/rule-details/triggers/rule-triggers.ui-component.html
- projects/aca-folder-rules/src/lib/rule-details/triggers/rule-triggers.ui-component.ts
- projects/aca-folder-rules/src/lib/rules-list/rule-list.ui-component.html
- projects/aca-folder-rules/src/lib/rules-list/rule-list.ui-component.scss
- projects/aca-folder-rules/src/lib/rules-list/rule-list.ui-component.spec.ts
- projects/aca-folder-rules/src/lib/rules-list/rule-list.ui-component.ts
- projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.html
- projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.scss
- projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.ts
- projects/aca-folder-rules/src/lib/rules-list/rules-list.ui-component.html
- projects/aca-folder-rules/src/lib/rules-list/rules-list.ui-component.scss
- projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-3744
Please watch the video …
> [ACS-3744] Folder rules styling fixes

- package-lock.json
- package.json
- projects/aca-testing-shared/src/components/info-drawer/info-drawer-comments-tab.ts
> - [x] Bugfix
E2e tests are failing for comments because of incorrect css selectors. …
> ACS-3545 fix e2e tests

- app/src/app/services/node-actions.service.ts
> - [x] Bugfix
Accessibility issue because of missing dialog role for move and copy dialogs. …
> ACS-3550 Fixed accessibility issues related with move and copy dialogs

- app/src/app/services/content-management.service.spec.ts
- app/src/app/services/content-management.service.ts
- package-lock.json
- package.json
- projects/aca-shared/store/src/actions/snackbar.actions.ts
- projects/aca-shared/store/src/effects/snackbar.effects.ts
- projects/aca-testing-shared/src/pages/page.ts
… close snackbar
> - [x] Bugfix
Some snackbars were autoclosing very quickly and there was not way to close it …
> ACS-3640 a 11 y aca 881740 snackbar messages disappear without option to adjust timing

- app/src/app/services/content-management.service.spec.ts
- app/src/app/services/content-management.service.ts
- e2e/suites/actions/copy-move/copy.test.ts
- e2e/suites/actions/copy-move/move.test.ts
- e2e/suites/actions/delete/delete-undo-delete.test.ts
- e2e/suites/actions/delete/restore.test.ts
- package-lock.json
- package.json
- projects/aca-about/src/lib/about.component.html
- projects/aca-about/src/lib/about.component.ts
- projects/aca-shared/store/src/actions/snackbar.actions.ts
- projects/aca-shared/store/src/effects/snackbar.effects.ts
- projects/aca-testing-shared/src/pages/page.ts
> - [ ] Bugfix
upgrade to using new presentation About component from ADF
depends on …
> [AAE-10766] upgrade to new About component

- app/src/app/services/content-management.service.ts
> - [x] Bugfix
Element must only use allowed ARIA attributes.
Fix the above issue by …
> [ACS-3549] add role dialog in manage version dialog

- app/src/app/ui/theme.scss
> - [x] Bugfix
Pagination styles are broken as described in: https://alfresco.atlassian.net/browse/ACS-4009
**What is …
> [ACS-4009] Fix pagination styling

- .github/workflows/rebase.yml
> - [ ] Bugfix
add `/rebase` support for PRs to enable fast rebasing via GitHub …
> add rebase workflow for PRs

- app/src/app/ui/custom-theme.scss
- app/src/app/ui/dynamic-theme/custom-theme.scss.tpl
- app/src/app/ui/overrides/adf-pagination.theme.scss
- app/src/app/ui/variables/variables.scss
> - [ ] Bugfix
Implemented Styling changes for Pagination as per …
> [ACS-3971] updated pagination styling

- app/src/app/ui/mixins.scss
- app/src/app/ui/overrides/adf-pagination.theme.scss
- app/src/app/ui/theme.scss
> - [x] Bugfix
Close icon focus in content viewer looks broken. https://alfresco.atlassian.net/browse/ACS-4013
**What …
> [ACS-4013] Fix pagination focus styling

- app/src/app/content-plugin/ui/application.scss
> - [x] Bugfix
when zooming to 400%, the lower portion of the screen was inaccessible. …
> [ACS-3731] a11y zoom issues

- e2e/protractor.excludes.json
- package-lock.json
- package.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-11695
**Does this PR …
> [AAE-11695] update adf version

- app/src/app/content-plugin/content-services-extension.module.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-10656
**Does this PR …
> [AAE-10656] Production version of ADW-APA miss the about page

- tsconfig.adf.json
> Fix adf configuration

- projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
- projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts
- projects/aca-folder-rules/src/lib/mock/node.mock.ts
- projects/aca-folder-rules/src/lib/mock/rule-sets.mock.ts
- projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts
- projects/aca-folder-rules/src/lib/rule-set-picker/rule-set-picker.smart-component.spec.ts
- projects/aca-folder-rules/src/lib/rule-set-picker/rule-set-picker.smart-component.ts
- projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.spec.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Unit tests that were previously purposefully omitted
https://alfresco.atlassian.net/browse/ACS-4070 …
> [ACA-4070] Add unit tests for linking rule sets

- projects/aca-shared/src/lib/services/app.service.ts
- tsconfig.adf.json
> - [ ] Bugfix
move shared link in content and deprecate unused dialog service
**Does …
> [AE-11486] move shared link in content and deprecate unused dialog service

- projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-4108
Issue is now resolved …
> [ACS-4108] rule actions were showing id instead of names

- e2e/suites/actions-available/files-folders/test-data.ts
- projects/aca-folder-rules/assets/i18n/en.json
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4648
Capitalised the 'r' in …
> [ACA-4648] Capitalised the 'r' in 'Manage rules'

- projects/aca-content/src/lib/extensions/core.extensions.module.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-12099
**Does this PR …
> [AAE-12099] Process only UI is broken and all sections are shown

- .github/workflows/codeql-analysis.yml
- .github/workflows/test.yml
> - [ ] Bugfix
- add Linting jobs with GHA 
- headless unit tests with GHA
- upgrade …
> [ACA-4649] GHA linting and unit testing support

- app/src/app.config.json.tpl
- docs/audit/audit-info-4.0.0-A.2.md
- docs/changelog/changelog-4.0.0-A.2.md
- docs/licences/license-info-4.0.0-A.2.md
- package-lock.json
- package.json
> - [ ] Bugfix
Release reports and steps for 4.0.0-A.2 …
> Release 4.0.0-A.2

- projects/aca-folder-rules/src/lib/rule-details/conditions/rule-condition-comparators.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-4446
renamed corresponding …
> [ACS-4446] Folder Rules Bug Fix: Error thrown when Condition If Name Starts With/Ends With is used

- scripts/ci/npm/publish-libs.sh
> [AAE-11496] Remove npm deprecation strategy

- angular.json
- package.json
- projects/aca-shared/package.json
- projects/adf-office-services-ext/ng-package.json
- projects/adf-office-services-ext/package.json
- projects/adf-office-services-ext/tsconfig.lib.prod.json
- scripts/ci/npm/publish-libs.sh
> [AAE-11496] Build and publish adf-office-services-ext

- projects/aca-folder-rules/package.json
> [AAE-11496] Publish aca-folder-rules fix

- e2e/suites/list-views/favorites.test.ts
- e2e/suites/list-views/file-libraries.test.ts
- e2e/suites/list-views/personal-files.test.ts
- e2e/suites/list-views/recent-files.test.ts
- e2e/suites/list-views/shared-files.test.ts
- e2e/suites/search/search-results-files-folders.test.ts
- e2e/suites/search/search-results-libraries.test.ts
- projects/aca-content/assets/app.extensions.json
- projects/aca-content/assets/i18n/en.json
- projects/aca-content/src/lib/aca-content.module.ts
- projects/aca-content/src/lib/components/dl-custom-components/tags-column/tags-column.component.scss
- projects/aca-content/src/lib/components/dl-custom-components/tags-column/tags-column.component.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.html
> - [ ] Bugfix
Tags applied to a file are not displayed.
Tags applied to a file are …
> [ACS-4124] Display tags applied to file in files list

- .github/workflows/aca-upstream.yml
- scripts/travis/update/update-project.sh
> - [x] Bugfix
Downgrade node version in ACA upstream workflow.
Node 14 is used. …
> [ACS-4632] Downgrade node version, small script fix

- projects/aca-content/src/lib/ui/dynamic-theme/custom-theme.scss.tpl
> fixed style template generation for content-app

- projects/aca-about/package.json
- projects/aca-content/package.json
- projects/aca-folder-rules/package.json
- projects/aca-preview/package.json
- projects/aca-testing-shared/package.json
- projects/aca-viewer/package.json
- projects/adf-office-services-ext/package.json
> - [x] Bugfix
add missing license fields for the ACA libs …
> [ACS-4702] fix license fields for libs

- projects/aca-content/src/lib/aca-content.module.ts
> [AAE-12833] There are console errors after opening file view.

- e2e/playwright/shared/page-objects/components/dataTable/data-table.component.ts
- e2e/playwright/shared/page-objects/components/mat-menu.component.ts
- e2e/playwright/shared/page-objects/components/pagination.component.ts
> - [x] Bugfix
See title
See titile …
> [ACS-4697] Fix Playwright Pagination for zombie folders (Reported by HxP BDU)

- .github/actions/git-tag/action.yml
- .github/actions/publish-image/action.yml
- .github/actions/publish-libs/action.yml
- .github/workflows/aca-upstream.yml
- .github/workflows/release.yml
- scripts/travis/deploy/publish.sh
> - [x] Bugfix
fixes for the release jobs …
> [ACA-4653] fix release actions

- .github/actions/adf-linking/action.yml
- .github/actions/before-install/action.yml
- .github/actions/setup/action.yml
- .github/workflows/release.yml
> - [x] Bugfix
- remove checks for merge to allow manual invokes for different …
> [ACA-4649] GitHub Actions workflow fixes

- .github/actions/git-tag/action.yml
- .github/actions/publish-image/action.yml
- .github/actions/publish-libs/action.yml
> - [x] Bugfix
-fix checks issues related to missing `dry-run`
**Does this PR …
> [ACA-4649] fix gha checks

- .github/actions/publish-image/action.yml
- .github/workflows/release.yml
- scripts/travis/deploy/publish.sh
> - [x] Bugfix
Release workflow fixes:
- better version extraction (via `jq`)
- fix …
> [ACA-4649] release workflow fixes

- .github/actions/git-tag/action.yml
- .github/actions/publish-libs/action.yml
> - [x] Bugfix
- fix lib publishing
- add published tags checks
**Does this PR …
> [ACA-4649] fix lib publishing

- .github/actions/publish-libs/action.yml
- .github/workflows/release.yml
- package.json
- scripts/gh/npm-publish.sh
- scripts/gh/update-lib-versions.sh
> - [ ] Bugfix
- move "update versions" to a dedicated shell script
- unified package …
> [ACA-4649] release workflow enhancements

- projects/aca-about/package.json
- projects/aca-content/package.json
- projects/aca-folder-rules/package.json
- projects/aca-preview/package.json
- projects/aca-shared/package.json
- projects/aca-testing-shared/package.json
- projects/aca-viewer/package.json
- projects/adf-office-services-ext/package.json
> - [x] Bugfix
fix package json for project libs …
> [ACA-4649] update libs packages

- .github/actions/publish-libs/action.yml
- .github/actions/update-library-versions/action.yml
> release workflow fixes

- .github/actions/publish-libs/action.yml
- .github/actions/update-library-versions/action.yml
> fix update-library-versions action

- .github/actions/publish-libs/action.yml
- .github/actions/update-library-versions/action.yml
> Fix gha workflow for library version bump

- .github/actions/setup/action.yml
> gha: port tag fetch from ADF

- .github/actions/setup/action.yml
> fix gha setup

- .github/workflows/pull-request.yml
> - [ ] Bugfix
support cancelling previously running jobs in the workflow
addresses …
> [ACA-4668] cancel previous jobs in the workflow

- .github/actions/update-library-versions/action.yml
- .github/workflows/release.yml
> ACS-4814 -  Use PR id for library publishing

- .github/actions/update-library-versions/action.yml
> use dot as separator for minor v

- .github/workflows/pull-request.yml
> - [ ] Bugfix
Build doesn't take proper config from $BUILD_OPTS.
Build now takes …
> [ACA-4651] Fix build config in GHA

- .lintstagedrc.json
> - [x] Bugfix
fix `pre-commit` hooks …
> [ACS-4951] fix pre-commit linting

- e2e/suites/list-views/file-libraries.test.ts
- e2e/suites/search/search-results-libraries.test.ts
- projects/aca-content/assets/app.extensions.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-4126
Removed tags from …
> [ACS-4126] Removed tags from libraries

- projects/aca-content/assets/app.extensions.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-4968
Sorts the tags by usage …
> [ACS-4968] Sort tags by usage in search facet

- projects/aca-content/assets/i18n/en.json
> - [ ] Bugfix
This i18n string should be added today for the upcoming PR regarding this ticket https://alfresco.atlassian.net/browse/ACS-4788
**What is the current behaviour?** (You can also …
> Added i18n string for categories facet

- .github/actions/adf-linking/action.yml
- tsconfig.adf.json
> - [x] Bugfix
ADF linking is broken. https://alfresco.atlassian.net/browse/ACS-5027 …
> [ACS-5027] Fix ADF linking in ACA

- .github/actions/run-e2e/action.yml
- e2e/playwright/shared/page-objects/pages/base.page.ts
> [ACS-4922] folder rule e2e fail timeout

- projects/aca-content/src/lib/ui/dynamic-theme/typography.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-13640
**Does this PR …
> [AAE-13640] Custom theme fix

- projects/aca-content/assets/app.extensions.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-4788
Added Categories facet …
> [ACS-4788] Add support for the Categories facet

- projects/aca-content/src/lib/ui/dynamic-theme/custom-theme.scss.tpl
> [AAE-13780] Fix custom theme components colors

- angular.json
> - [ ] Bugfix
remove unused libs from project commonjs bundling
**Does this PR …
> remove unused commonjs libs

- e2e/protractor.excludes.json
- e2e/suites/actions/share/share-file.test.ts
- projects/aca-testing-shared/src/components/datetime-picker/datetime-picker.ts
> - [ ] Bugfix
[C286332] test case doesn't check if picked time is correct. …
> [ACS-4425] Improved share file with expiration date test

- projects/aca-content/assets/i18n/ar.json
- projects/aca-content/assets/i18n/cs.json
- projects/aca-content/assets/i18n/da.json
- projects/aca-content/assets/i18n/de.json
- projects/aca-content/assets/i18n/es.json
- projects/aca-content/assets/i18n/fi.json
- projects/aca-content/assets/i18n/fr.json
- projects/aca-content/assets/i18n/it.json
- projects/aca-content/assets/i18n/ja.json
- projects/aca-content/assets/i18n/nb.json
- projects/aca-content/assets/i18n/nl.json
- projects/aca-content/assets/i18n/pl.json
- projects/aca-content/assets/i18n/pt-BR.json
- projects/aca-content/assets/i18n/ru.json
- projects/aca-content/assets/i18n/sv.json
- projects/aca-content/assets/i18n/zh-CN.json
- projects/aca-folder-rules/assets/i18n/pl.json
> - [ x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ na] Tests for the changes have been added (for bug fixes / features)
> - [na ] Docs have been added / updated (for bug fixes / features)
> - [ ] Bugfix
> - [x ] Other... Please describe: Further updates requested by @MohinishSah to UI files 
**Does …
> LOC-434 - further updates to ACA 3.0 - localized files in 16 languages

- projects/aca-content/src/lib/components/sidenav/sidenav.component.scss
- projects/aca-content/src/lib/ui/variables/variables.scss
- projects/aca-shared/src/lib/components/page-layout/page-layout.component.scss
> [ACS-3742] Added styles for new layout design 

- projects/aca-shared/src/lib/components/page-layout/page-layout.component.scss
> - [x] Bugfix
The width of the Create tag keeps increasing indefinitely.
Limiting the …
> [ACA-4690] added width and max-width to sidebar

- .github/workflows/upstream-adf.yml
- scripts/gh/update/check-pr-already-exists.js
- scripts/gh/update/latest-version-of.js
> - [ ] Bugfix
ADF upstream is created from ADF repo level. https://alfresco.atlassian.net/browse/ACS-5186
**What is …
> [ACS-5186] Add new GH workflow for ADF upstream

- e2e/resources/extensibility-configs/context-submenus-ext.json
- e2e/resources/extensibility-configs/document-presets-ext.json
- e2e/resources/extensibility-configs/header-ext.json
- e2e/resources/extensibility-configs/info-drawer-ext.json
- e2e/resources/extensibility-configs/info-drawer-no-tabs-ext.json
- e2e/resources/extensibility-configs/metadata-ext.json
- e2e/resources/extensibility-configs/viewer-ext.json
- projects/aca-content/about/assets/about.plugin.json
- projects/aca-content/assets/app.extensions.json
- projects/aca-content/src/lib/aca-content.module.ts
- projects/aca-content/src/lib/components/common/user-info/user-info.component.html
- projects/aca-content/src/lib/components/common/user-info/user-info.component.scss
- projects/aca-content/src/lib/components/common/user-info/user-info.component.spec.ts
- projects/aca-content/src/lib/components/sidenav/sidenav.module.ts
- projects/aca-content/src/lib/components/sidenav/user-menu/user-menu.component.html
- projects/aca-content/src/lib/components/sidenav/user-menu/user-menu.component.scss
- projects/aca-content/src/lib/components/sidenav/user-menu/user-menu.component.spec.ts
- projects/aca-content/src/lib/components/sidenav/user-menu/user-menu.component.ts
- projects/aca-content/src/lib/ui/variables/variables.scss
- projects/aca-testing-shared/src/components/header/header.ts
> [ACS-4708] Implemented user initials

- .eslintrc.json
- package-lock.json
- package.json
- projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.html
- projects/aca-content/src/lib/components/search/search-input/search-input.component.html
- projects/aca-content/src/lib/components/sidenav/components/sidenav-header.component.html
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4711
Now accessibility rules …
> [ACA-4711] ACA: Enable checking accessibility in eslint

- projects/aca-content/src/lib/components/dl-custom-components/thumbnail-column/thumbnail-column.component.html
- projects/aca-content/src/lib/components/dl-custom-components/thumbnail-column/thumbnail-column.component.ts
> - [x] Bugfix
rework thumbnail column component to address performance issues; …
> [ACS-5089] performance improvements for Thumbnail Column

- app/src/app/extensions.module.ts
- projects/aca-content/about/src/about.component.ts
- projects/aca-content/about/src/aca-about.module.ts
- projects/aca-content/about/src/dev-mode.tokens.ts
> - [ ] Bugfix
- example of converting About component/module to an Angular Standalone …
> standalone About component

- package-lock.json
- package.json
- projects/aca-content/src/lib/components/search/search-results-row/search-results-row.components.spec.ts
- projects/aca-content/src/lib/components/toolbar/document-display-mode/document-display-mode.component.spec.ts
- projects/aca-content/src/lib/components/toolbar/toggle-info-drawer/toggle-info-drawer.component.spec.ts
- projects/aca-folder-rules/package.json
- projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts
- projects/aca-shared/package.json
> - [ ] Bugfix
cleanup the flex layout dependency
fix issues with test imports
**Does …
> [ADF-5504] remove flex-layout dependency

- app/src/app.config.json.tpl
- app/src/assets/plugins/app.search.json
- projects/aca-content/assets/app.extensions.json
- projects/aca-content/assets/i18n/en.json
> - [ ] Bugfix
Logical search has been added to filter configuration. …
> [ACS-5181] Introduce logical search filter

- projects/aca-content/src/lib/ui/overrides/adf-about.theme.scss
- projects/aca-content/src/lib/ui/overrides/adf-pagination.theme.scss
- projects/aca-content/src/lib/ui/variables/variables.scss
> - [ ] Bugfix
> - [X] Code style update (formatting, local variables)
https://alfresco.atlassian.net/browse/ACS-4795
Removed redundant …
> [ACS-4795] Remove all custom CSS/CSS variables that already have defaults in ADF

- README.md
- docs/README.md
- docs/getting-started/building-from-source.md
- docs/getting-started/nvm.md
> - [ ] Bugfix
- update docs
- closes #3222 …
> [ACS-5386] update docs

- projects/aca-content/assets/app.extensions.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-4986
Filters for Tags and …
> [ACS-4986] Advanced Search - enable new component for Tags and Location filters

- projects/aca-content/src/lib/components/common/user-info/user-info.component.scss
- projects/aca-content/src/lib/components/search/search-results/search-results.component.scss
- projects/aca-content/src/lib/components/sidenav/user-menu/user-menu.component.scss
- projects/aca-content/src/lib/components/view-profile/view-profile.component.scss
- projects/aca-content/src/lib/ui/overrides/ay11.scss
- projects/aca-content/src/lib/ui/variables/variables.scss
- projects/aca-shared/src/lib/components/page-layout/page-layout.component.scss
> - [ ] Bugfix
UI and styles for facets and filters has been updated. Also some …
> [ACS-5347] New styles for filter states

- package-lock.json
- package.json
> upgrade to latest ADF

- projects/aca-testing-shared/src/utilities/utils.ts
> - [ ] Bugfix
Using Math.random populates dozens of security vulnerabilities like 'Insecure randomness' 
**What is …
> Security fix - insecure randomness

- projects/aca-content/assets/app.extensions.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5521, the buttons color scheme is different than expected. …
> [ACS-5521] Create to primary and upload to secondary button color change in ACA

- e2e/playwright/folder-rules/playwright.config.ts
- e2e/playwright/folder-rules/src/tests/actions.spec.ts
- e2e/playwright/folder-rules/src/tests/conditions.spec.ts
- e2e/playwright/folder-rules/src/tests/manage-rules.spec.ts
- projects/aca-playwright-shared/src/fixtures/page-initialization.ts
- projects/aca-playwright-shared/src/page-objects/components/actions-dropdown.component.ts
- projects/aca-playwright-shared/src/page-objects/components/base.component.ts
> - [ ] Bugfix
Local run of folder rules tests fails with for admin user
Local run of …
> [ACS-5585] refactoring - direct api-client-factory call

- Dockerfile
- docker/docker-entrypoint.d/30-sed-on-appconfig.sh
- docker/run.sh
- docs/getting-started/docker.md
> - [ ] Bugfix
- support the original set of Docker variables
- update documentation …
> [ACA-4715] provide support for Docker variables

- package-lock.json
- package.json
> - [ ] Bugfix
bump version to the upcoming 4.2.0 …
> Bump to 4.2.0

- projects/aca-content/about/src/about.component.ts
> - [x] Bugfix
- fix the "About / Plugins" section …
> [ACA-4688] fix about plugins section

- projects/aca-content/about/src/about.component.html
- projects/aca-content/about/src/about.component.ts
- projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.html
- projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.ts
- projects/aca-content/src/lib/components/details/details.component.html
- projects/aca-content/src/lib/components/details/details.component.ts
- projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.html
- projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.ts
- projects/aca-content/src/lib/components/favorites/favorites.component.html
- projects/aca-content/src/lib/components/favorites/favorites.component.ts
- projects/aca-content/src/lib/components/files/files.component.html
- projects/aca-content/src/lib/components/files/files.component.ts
- projects/aca-content/src/lib/components/libraries/libraries.component.html
- projects/aca-content/src/lib/components/libraries/libraries.component.ts
- projects/aca-content/src/lib/components/recent-files/recent-files.component.html
- projects/aca-content/src/lib/components/recent-files/recent-files.component.ts
- projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.html
- projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.html
- projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
- projects/aca-content/src/lib/components/shared-files/shared-files.component.html
- projects/aca-content/src/lib/components/shared-files/shared-files.component.ts
- projects/aca-content/src/lib/components/trashcan/trashcan.component.html
- projects/aca-content/src/lib/components/trashcan/trashcan.component.ts
- projects/aca-shared/src/lib/components/page-layout/page-layout-content.component.ts
- projects/aca-shared/src/lib/components/page-layout/page-layout-error.component.ts
- projects/aca-shared/src/lib/components/page-layout/page-layout-header.component.ts
- projects/aca-shared/src/lib/components/page-layout/page-layout.component.html
- projects/aca-shared/src/lib/components/page-layout/page-layout.md
> - [ ] Bugfix
- reduce the need for empty Angular components for page layout
- …
> [ACS-5631] Improved page layout and provide documentation

- projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.html
- projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.scss
> [ACS-5646] fix library metadata layout

- projects/aca-content/src/lib/components/search/search-results/search-results.component.scss
> - [ ] Bugfix
Facet styles for new tabbed facet component has been added.
**Does this …
> [ACS-5179] Search facet tabbed component styles

- .stylelintrc.json
- projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.scss
- projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.scss
- projects/aca-content/src/lib/components/search/search-input/search-input.component.scss
- projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.scss
- projects/aca-content/src/lib/components/sidenav/components/expand-menu.component.html
- projects/aca-content/src/lib/components/sidenav/sidenav.component.scss
- projects/aca-content/src/lib/components/view-profile/view-profile.component.scss
- projects/aca-content/src/lib/ui/application.scss
- projects/aca-content/src/lib/ui/dynamic-theme/typography.scss
- projects/aca-content/src/lib/ui/mixins.scss
- projects/aca-content/src/lib/ui/overrides/adf-about.theme.scss
- projects/aca-content/src/lib/ui/overrides/adf-pagination.theme.scss
- projects/aca-content/src/lib/ui/overrides/adf-style-fixes.theme.scss
- projects/aca-content/src/lib/ui/overrides/ay11.scss
- projects/aca-content/src/lib/ui/theme.scss
- projects/aca-content/src/lib/ui/variables/variables.scss
- projects/aca-shared/src/lib/components/page-layout/page-layout.component.scss
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4712
declaration-no-important …
> [ACA-4712] disallow using important for styles

- e2e/protractor/suites/actions-available/files-folders/folders-actions.test.ts
- e2e/protractor/suites/actions-available/files-folders/locked-files-actions.test.ts
- e2e/protractor/suites/actions-available/files-folders/multiple-files-actions.test.ts
- e2e/protractor/suites/actions-available/files-folders/office-files-actions.test.ts
- e2e/protractor/suites/actions-available/files-folders/single-file-actions.test.ts
- e2e/protractor/suites/actions-available/special-permissions/search-results.ts
- e2e/protractor/suites/actions-available/special-permissions/viewer.ts
…ableFilesFolders and actionsAvailableSpecialPermissions
> - [ ] Bugfix
**Does this PR …
> ES Draft PR - Swapnil

- projects/aca-shared/src/lib/components/toolbar/toolbar-button/toolbar-button.component.ts
- projects/aca-shared/src/lib/components/toolbar/toolbar-menu-item/toolbar-menu-item.component.ts
> - [ ] Bugfix
> - [X] Other... Please describe: Vulnerability fix 
Incomplete string escaping - does not escape backslash characters. Even if the …
> [ACS-5849] [ACS-5848] Incomplete string escaping fix

- .github/workflows/pull-request.yml
- app/karma.conf.js
- app/project.json
- app/src/app/app.components.spec.ts
- projects/aca-shared/src/lib/services/app.service.ts
> - [x] Bugfix
Due to new 'affected' command NX is trying to start tests for content-ce project which has no tests …
> [ACS-5107] - improve gha after introducing nx workspace 

- e2e/protractor/suites/search/search-filters.test.ts
- e2e/protractor/suites/search/search-results-files-folders.test.ts
> - [ ] Bugfix
Moment.js library is being used
date-fns library is being used.
**Does …
> [APPS-2171][APPS-2172] Migration from moment to date-fns

- .eslintrc.json
- app/.eslintrc.json
- app/project.json
- e2e/playwright/actions/project.json
- e2e/playwright/authentication/project.json
- e2e/playwright/folder-rules/project.json
- e2e/playwright/navigation/project.json
- e2e/playwright/viewer/project.json
- e2e/protractor/project.json
- nx.json
- package-lock.json
- package.json
- projects/aca-content/project.json
- projects/aca-playwright-shared/project.json
- projects/aca-shared/package.json
- projects/aca-shared/project.json
- projects/aca-testing-shared/project.json
- tsconfig.json
> - [ ] Bugfix
- migrate to Nx 16, that does not include Angular
**Does this PR …
> migrate to nx 16

- .github/actions/run-e2e/action.yml
- e2e/playwright/navigation/src/tests/breadcrumb.spec.ts
> - [x] Bugfix
> - [ ] Other... Please describe: 
**What is the new behaviour?**  test result upload protractor in git action
delete test data …
> [ACS-5617] test result upload protractor in git action

- .gitignore
- .prettierignore
- nx.json
- package-lock.json
- package.json
> - [ ] Bugfix
nx 17 upgrade
**Does this PR introduce a breaking change?** (check one …
> migrate to nx 17

- package-lock.json
- package.json
> - [ ] Bugfix
> - [x] Other... Please describe: Version bump
**Does this PR introduce a breaking change?** (check one …
> Bump ACA version

- app/src/app/app.module.ts
- e2e/playwright/authentication/exclude.tests.json
- package-lock.json
- package.json
- projects/aca-content/ms-office/src/aos-extension.service.spec.ts
- projects/aca-content/src/lib/components/context-menu/context-menu.service.spec.ts
- projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.spec.ts
- projects/aca-shared/src/lib/components/document-base-page/document-base-page.spec.ts
- projects/aca-shared/src/lib/services/app.extension.service.spec.ts
> Upstream to ADF:6.5.1 JS-API:7.2.0

- app/src/app/app.module.ts
> - [ ] Bugfix
remove useless imports from app module …
> remove redundant service imports

- package-lock.json
- package.json
- projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.html
- projects/aca-content/src/lib/components/favorites/favorites.component.html
- projects/aca-content/src/lib/components/files/files.component.html
- projects/aca-content/src/lib/components/libraries/libraries.component.html
- projects/aca-content/src/lib/components/recent-files/recent-files.component.html
- projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.html
- projects/aca-content/src/lib/components/search/search-results/search-results.component.html
- projects/aca-content/src/lib/components/shared-files/shared-files.component.html
- projects/aca-content/src/lib/components/trashcan/trashcan.component.html
> - [ ] Bugfix
Added resize option to document lists and disable blur when resizing. …
> [MNT-23166] Add resizing and disable blur for document lists

- app/project.json
> - [x] Bugfix
- fix styling issues when linking ADF …
> fix linked ADF styling

- projects/aca-content/assets/app.extensions.json
> - [x] Bugfix
Minimum width is not set for the column header
Css classes added to set …
> [ACS-6031]  Css classes added for maintaining minimum width in column header

- package-lock.json
- package.json
- projects/aca-content/package.json
- projects/aca-shared/package.json
> update to latest ADF alphas

- projects/aca-content/src/lib/components/sidenav/components/sidenav-header.component.html
- projects/aca-content/src/lib/components/sidenav/user-menu/user-menu.component.html
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-18442
**Does this PR …
> [AAE-18442] Add data-automation-id to ACA user initials and sidenav

- projects/aca-content/assets/app.extensions.json
> - [x] Bugfix
Fix for one of the cases from this issue (Pipe icon) -> …
> [AAE-18662] Fix - Pipe icon is still visible in the search

- projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.scss
- projects/aca-content/src/lib/components/dl-custom-components/tags-column/tags-column.component.scss
- projects/aca-content/src/lib/components/search/search-input/search-input.component.scss
- projects/aca-content/src/lib/components/search/search-results/search-results.component.scss
- projects/aca-content/src/lib/components/sidenav/sidenav.component.scss
- projects/aca-content/src/lib/components/sidenav/user-menu/user-menu.component.scss
- projects/aca-content/src/lib/ui/theme.scss
- projects/aca-content/src/lib/ui/variables/variables.scss
> [AAE-18779] Cannot update colours according to dynamically generated theme due to hardcoded values

- projects/aca-content/assets/app.extensions.json
- projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.html
- projects/aca-content/src/lib/components/favorites/favorites.component.html
- projects/aca-content/src/lib/components/files/files.component.html
- projects/aca-content/src/lib/components/libraries/libraries.component.html
- projects/aca-content/src/lib/components/recent-files/recent-files.component.html
- projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.html
- projects/aca-content/src/lib/components/search/search-results/search-results.component.html
- projects/aca-content/src/lib/components/shared-files/shared-files.component.html
- projects/aca-content/src/lib/components/trashcan/trashcan.component.html
- projects/aca-testing-shared/src/components/data-table/data-table.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-6323
User can reorder columns …
> [ACS-6323] dynamic content list changing columns order with drag drop

- package-lock.json
- package.json
> - [ ] Bugfix
- remove unused `ajv-cli` (security fix) …
> [security] remove ajv-cli

- projects/aca-content/src/lib/components/sidenav/sidenav.component.scss
- projects/aca-content/src/lib/ui/variables/variables.scss
> - [ ] Bugfix
Added possibility to override selected and hovered menu item by overriding css variable 
**What is the …
> [AAE-19247] Add css variables for selected and hover menu item

- package-lock.json
- projects/aca-content/package.json
- projects/aca-shared/package.json
> Upstream dependencies

- e2e/playwright/list-views/exclude.tests.json
- package-lock.json
- package.json
> - [ ] Bugfix
Manual upstream aca …
> [ACS-6732] Manual upstream changes

- projects/aca-content/src/lib/components/search/search-input/search-input.component.ts
- projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.html
- projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.scss
- projects/aca-content/src/lib/components/search/search-results/search-results.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6641
Advanced search filters for Files and Folders search …
> [ACS-6641] fix advanced search filters not display, fix libraries search option uncheck

- projects/aca-content/src/lib/components/dl-custom-components/tags-column/tags-column.component.scss
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5483
Renamed css class name …
> [ACS-5483] Renamed css class

- projects/aca-content/src/lib/components/search/search-results/search-results.component.spec.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
> - [x] Bugfix
Search is not strict enough for TEXT content.
Search should return …
> [ACS-6427] Apply * for TEXT field for highlighting

- docs/extending/application-features.md
- extension.schema.json
- projects/aca-content/assets/app.extensions.json
- projects/aca-content/src/lib/aca-content.module.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.html
- projects/aca-content/src/lib/components/search/search-results/search-results.component.spec.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
- projects/aca-shared/src/lib/services/app.extension.service.ts
> - [ ] Bugfix
Search results list columns are hard-coded in HTML.
Now columns in …
> [ACS-6813] ACA configurable layout for search result list

- package.json
> - [ ] Bugfix
Fixed current release version …
> Correct release version

- package.json
> - [ ] Bugfix
> - [x] Other... Please describe: ACA version bump …
> Post release version bump

- e2e/playwright/search/src/tests/search-results-files-folders.spec.ts
- projects/aca-playwright-shared/src/page-objects/components/base.component.ts
> - [ ] Bugfix
> - [X] Other... Please describe: Migrating tests from Protractor to Playwright …
> ACS-6796 Search results files&folders tests migration to Playwright

- e2e/playwright/search/src/tests/search-results-files-folders.spec.ts
- e2e/playwright/search/src/tests/search-results-general.spec.ts
- e2e/playwright/search/src/tests/search-results-libraries.spec.ts
- projects/aca-playwright-shared/src/page-objects/components/dataTable/data-table.component.ts
- projects/aca-playwright-shared/src/page-objects/components/search/search-input.component.ts
- projects/aca-playwright-shared/src/page-objects/pages/search.page.ts
> [ACS-6954] Refactored search playwright tests

- e2e/playwright/search/src/tests/search-results-general.spec.ts
- e2e/playwright/search/src/tests/search-results-libraries.spec.ts
- projects/aca-playwright-shared/src/page-objects/components/search/search-input.component.ts
- projects/aca-playwright-shared/src/page-objects/components/search/search-overlay.components.ts
- projects/aca-playwright-shared/src/page-objects/pages/search.page.ts
> [ACS-6954] Refactor Search Playwright tests - move search actions to searchOverlay component

- .github/actions/run-e2e-playwright/action.yml
- e2e/playwright/info-drawer/src/tests/comments.spec.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-7260
Added Playwright …
> [ACS-7260] Added Playwright artifacts to github actions

- .github/workflows/release-branch.yml
> - [ ] Bugfix
New GHA workflow has been added to enable publishing ACA libs from a …
> [ACS-6956] Add GHA workflow to release ACA libs from branch

- e2e/playwright/copy-move-actions/src/tests/copy.test.ts
- e2e/playwright/copy-move-actions/src/tests/destination-picker-dialog.test.ts
- e2e/playwright/info-drawer/src/tests/comments.spec.ts
- projects/aca-playwright-shared/src/utils/utils.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-7294
Updated hooks - …
> [ACS-7294] Updated hooks - copy-move-actions

- e2e/playwright/library-actions/src/tests/library-actions.spec.ts
- e2e/playwright/search/src/tests/search-results-general.spec.ts
- e2e/playwright/search/src/tests/search-results-libraries.spec.ts
> [ACS-7297] Updated beforeEach, small 'random' cleanup

- docker/docker-entrypoint.d/30-sed-on-appconfig.sh
- docs/getting-started/docker.md
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-6927
ADF is dependent from Keycloak for SSO login.
**What is …
> [ACS-6927] - Fully compliant with OIDC: ADF

- e2e/playwright/copy-move-actions/src/tests/move.test.ts
- e2e/playwright/create-actions/src/tests/create-file-from-template.spec.ts
- e2e/playwright/create-actions/src/tests/create-folder-from-template.spec.ts
- e2e/playwright/create-actions/src/tests/create-folder.spec.ts
- e2e/playwright/create-actions/src/tests/create-library.spec.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7295
[ACS-7295] create actions …
> [ACS-7295] create actions - beforeEach and afterAll refactored

- e2e/playwright/pagination/src/tests/multiple-pages-files.spec.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7301
[ACS-7301] beforeEach and …
> [ACS-7301] beforeEach and afterAll refactored for pagination tests

- projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.html
- projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.ts
- projects/aca-content/folder-rules/src/rule-list/rule-list/rule-list.ui-component.html
- projects/aca-content/folder-rules/src/rule-list/rule-list/rule-list.ui-component.spec.ts
- projects/aca-content/folder-rules/src/rule-list/rule-list/rule-list.ui-component.ts
- projects/aca-content/folder-rules/src/services/folder-rule-sets.service.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7366
Component refactored to …
> [ACS-7366] Fix infinite re-rendering of RuleListItem component

- projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.ts
- projects/aca-content/src/lib/components/favorites/favorites.component.ts
- projects/aca-content/src/lib/components/files/files.component.ts
- projects/aca-content/src/lib/components/libraries/libraries.component.ts
- projects/aca-content/src/lib/components/recent-files/recent-files.component.ts
- projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
- projects/aca-content/src/lib/components/shared-files/shared-files.component.ts
- projects/aca-content/src/lib/components/trashcan/trashcan.component.ts
> - [ ] Bugfix
- switch to ADF Pagination as standalone …
> [ACS-7376] switch to standalone pagination

- .eslintrc.json
- e2e/playwright/authentication/src/tests/general.e2e.ts
- e2e/playwright/authentication/src/tests/login.e2e.ts
- e2e/playwright/copy-move-actions/src/tests/destination-picker-dialog.e2e.ts
- e2e/playwright/create-actions/src/tests/create-file-from-template.e2e.ts
- e2e/playwright/create-actions/src/tests/create-folder-from-template.e2e.ts
- e2e/playwright/create-actions/src/tests/create-library.e2e.ts
- e2e/playwright/info-drawer/src/tests/comments.e2e.ts
- e2e/playwright/info-drawer/src/tests/general.e2e.ts
- e2e/playwright/info-drawer/src/tests/library-properties.e2e.ts
- e2e/playwright/library-actions/src/tests/library-actions.e2e.ts
- e2e/playwright/list-views/src/tests/favorites.e2e.ts
- e2e/playwright/list-views/src/tests/generic-errors.e2e.ts
- e2e/playwright/navigation/src/tests/breadcrumb.e2e.ts
- e2e/playwright/navigation/src/tests/single-click.e2e.ts
- e2e/playwright/search/src/tests/search-input.e2e.ts
- e2e/playwright/share-action/src/tests/share/unshare-file-search-results.e2e.ts
- e2e/playwright/viewer/src/tests/viewer-action.e2e.ts
- e2e/playwright/viewer/src/tests/viewer-protected.e2e.ts
- e2e/playwright/viewer/src/tests/viewer-useraction.e2e.ts
- e2e/playwright/viewer/src/tests/viewer.e2e.ts
- package-lock.json
- package.json
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7451
[ACS-7451] playwright …
> [ACS-7451] playwright eslint plugin introduced

- projects/aca-content/folder-rules/src/rule-details/edit-rule-dialog.ui-component.scss
- projects/aca-content/src/lib/ui/theme.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7370 …
> [ACS-7370] - leave library dialog misses some padding

- e2e/playwright/search/src/tests/search-filters-general.e2e.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7362
Search general tests …
> [ACS-7362] [E2E] Search general tests migrated to Playwright

- projects/aca-content/src/lib/components/details/details.component.html
- projects/aca-content/src/lib/components/details/details.component.scss
- projects/aca-content/src/lib/components/info-drawer/comments-tab/comments-tab.component.ts
- projects/aca-content/src/lib/ui/overrides/ay11.scss
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7373
https://hyland.atlassian.net/browse/ACS-7374
**What is …
> [ACS-7373][ACS-7374] ng15 Permissions tab fixes

- projects/aca-shared/src/lib/components/locked-by/locked-by.component.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7410 …
> [ACS-7410] - Locked files overflow issues

- projects/aca-content/src/lib/components/sidenav/user-menu/user-menu.component.scss
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7528 …
> [ACS-7528] - Notification and user icons are a bit different

- projects/aca-content/src/lib/ui/theme.scss
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7529 …
> [ACS-7529] - columns visibility dropdown has broken styles

- e2e/playwright/search/src/tests/search-filters-location.e2e.ts
- projects/aca-playwright-shared/src/page-objects/components/search/search-filters/search-filters-location.component.ts
> - [ ] Bugfix
> - [X] Other... Please describe: Migrating e2e tests from Protractor to Playwright
**Does this PR …
> [ACS-7335] Migrated e2e tests - search filters - location

- e2e/playwright/create-actions/src/tests/create-folder.e2e.ts
- e2e/playwright/create-actions/src/tests/create-library.e2e.ts
- projects/aca-playwright-shared/src/page-objects/components/actions-dropdown.component.ts
- projects/aca-playwright-shared/src/page-objects/components/adf-info-drawer.component.ts
- projects/aca-playwright-shared/src/page-objects/components/conditions.component.ts
- projects/aca-playwright-shared/src/page-objects/components/dataTable/mat-menu.component.ts
- projects/aca-playwright-shared/src/page-objects/components/dialogs/adf-folder-dialog.component.ts
- projects/aca-playwright-shared/src/page-objects/components/dialogs/adf-library-dialog.component.ts
- projects/aca-playwright-shared/src/page-objects/components/dialogs/content-node-selector-dialog.ts
- projects/aca-playwright-shared/src/page-objects/components/manageRules/manage-rules.component.ts
- projects/aca-playwright-shared/src/page-objects/components/search/search-overlay.components.ts
- projects/aca-playwright-shared/src/page-objects/components/search/search-sorting-picker.components.ts
> [ACS-7369] ng15 migration - fix e2es

- e2e/playwright/search/exclude.tests.json
- e2e/playwright/search/src/tests/search-filters-categories.e2e.ts
- e2e/playwright/search/src/tests/search-filters-logic.e2e.ts
- projects/aca-playwright-shared/src/api/api-client-factory.ts
- projects/aca-playwright-shared/src/api/categories-api.ts
- projects/aca-playwright-shared/src/api/index.ts
- projects/aca-playwright-shared/src/page-objects/components/search/search-filters.component.ts
- projects/aca-playwright-shared/src/page-objects/components/search/search-filters/search-filters-logic.component.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7337
protractor to playwright …
> [ACS-7337] [E2E] protractor to playwright e2e test suites search filters categories filter

- e2e/playwright/create-actions/src/tests/create-library.e2e.ts
- projects/aca-playwright-shared/src/page-objects/components/dialogs/adf-library-dialog.component.ts
> - [ ] Bugfix
https://github.com/Alfresco/alfresco-ng2-components/pull/9574
**Does …
> [ACS-7575] create library dialog e2e fix

- e2e/playwright/create-actions/src/tests/create-folder.e2e.ts
- e2e/playwright/create-actions/src/tests/create-library.e2e.ts
- projects/aca-playwright-shared/src/page-objects/components/dialogs/adf-folder-dialog.component.ts
- projects/aca-playwright-shared/src/page-objects/components/dialogs/adf-library-dialog.component.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7534 …
> [ACS-7534] ng15 create folder e2e fixes

- projects/aca-content/src/lib/ui/overrides/ay11.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7555
Focused checkboxes have …
> [ACS-7555] Added blue outline to focused checkboxes

- projects/aca-content/folder-rules/src/rule-set-picker/rule-set-picker.smart-component.scss
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7572 …
> [ACS-7572] Link rules dialog

- e2e/playwright/viewer/src/tests/viewer-useraction.e2e.ts
- e2e/playwright/viewer/src/tests/viewer.e2e.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7305
beforeEach and afterAll …
> [ACS-7305] beforeEach and afterAll updated for viewer tests

- e2e/playwright/authentication/src/tests/general.e2e.ts
- e2e/playwright/create-actions/src/tests/create-folder-from-template.e2e.ts
- e2e/playwright/create-actions/src/tests/create-folder.e2e.ts
- e2e/playwright/folder-rules/src/tests/actions.e2e.ts
- e2e/playwright/folder-rules/src/tests/conditions.e2e.ts
- e2e/playwright/folder-rules/src/tests/manage-rules.e2e.ts
- e2e/playwright/viewer/src/tests/viewer-action.e2e.ts
- e2e/playwright/viewer/src/tests/viewer-protected.e2e.ts
- e2e/playwright/viewer/src/tests/viewer.e2e.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7767
viewer-actions folder …
> [ACS-7767] [E2E] ACA e2e folders' renaming for easier debugging in the future

- projects/aca-content/src/lib/ui/theme.scss
- projects/aca-shared/src/lib/components/toolbar/toolbar-action/toolbar-action.component.html
- projects/aca-shared/src/lib/components/toolbar/toolbar-action/toolbar-action.component.scss
> [ACS-7558] - toolbar and buttons

- docs/features/search-forms.md
- docs/tutorials/search-form.md
- projects/aca-content/assets/app.extensions.json
- projects/aca-content/src/lib/components/search/search-results/search-results.component.spec.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
- projects/aca-shared/src/lib/services/app.extension.service.spec.ts
> - [ ] Bugfix
configuration needed to be cleared
unified namespace
**Does this PR …
> [ACS-6647] Review and cleanup Search configuration files in ACA and ADW

- projects/aca-content/src/lib/components/details/details.component.scss
- projects/aca-content/src/lib/ui/theme.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7561 …
> [ACS-7561] - Permissions page

- app/src/app/app.module.ts
- projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.scss
- projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.html
- projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.scss
- projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.html
- projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss
- projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.html
- projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.html
- projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.scss
- projects/aca-content/src/lib/components/search/search-input/search-input.component.html
- projects/aca-content/src/lib/components/search/search-input/search-input.component.scss
- projects/aca-content/src/lib/components/view-profile/view-profile.component.html
- projects/aca-content/src/lib/components/view-profile/view-profile.component.scss
- projects/aca-content/src/lib/components/view-profile/view-profile.component.ts
- projects/aca-content/src/lib/dialogs/node-template/create-from-template.dialog.html
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7768
It's first iteration of …
> [ACS-7768] unify inputs and selects across the app

- projects/aca-shared/store/src/selectors/app.selectors.ts
…vailable
> - [ ] Bugfix
New selector to verify if HxI connector is available has been …
> [ACS-8025] Introduce new selector to check whether HxI connector is available

- package-lock.json
- package.json
> [ACS-8043] fix js api dependencies

- .github/actions/before-e2e/action.yml
> - [ ] Bugfix
> - [x] Other... Please describe: chrome driver link update
chrome driver download link broken
**Does …
> [ACS-8045]update ACA chrome driver

- projects/aca-content/src/lib/dialogs/node-template/create-from-template.dialog.html
- projects/aca-content/src/lib/dialogs/node-template/create-from-template.dialog.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8020
Inputs for Create from …
> [ACS-8020] Fixed inputs for create from template dialog

- tsconfig.adf.json
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8053
ACA run with local ADF is …
> [ACS-8053] add js-api path to tsconfig

- projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.html
- projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.scss
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8052 …
> [ACS-8052] inputs for general info for libraries

- projects/aca-content/folder-rules/src/rule-details/actions/rule-action-list.ui-component.scss
- projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.scss
> [ACS-8059] Inputs for view rules

- projects/aca-content/src/lib/ui/overrides/ay11.scss
- projects/aca-content/src/lib/ui/theme.scss
> - [ ] Bugfix
UI Fixes for angular upgrade
UI for task form rendering was broken after angular upgrade
**What is the …
> [ACS-8026] Fixed Task form rendering

- projects/aca-playwright-shared/src/page-objects/pages/base.page.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8076
[ACS-8076] [E2E] Changed …
> [ACS-8076] [E2E] Changed waitUntil in navigate method to 'load'

- e2e/playwright/info-drawer/src/tests/comments.e2e.ts
- projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.html
- projects/aca-content/src/lib/components/favorites/favorites.component.html
- projects/aca-content/src/lib/components/files/files.component.html
- projects/aca-content/src/lib/components/libraries/libraries.component.html
- projects/aca-content/src/lib/components/recent-files/recent-files.component.html
- projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.html
- projects/aca-content/src/lib/components/search/search-results/search-results.component.html
- projects/aca-content/src/lib/components/shared-files/shared-files.component.html
- projects/aca-content/src/lib/components/trashcan/trashcan.component.html
- projects/aca-playwright-shared/src/page-objects/components/dataTable/data-table.component.ts
> - [ ] Bugfix
Multiselection has been enabled in each document list …
> [ACS-8080] Enable multiselection in lists

- projects/aca-content/src/lib/ui/overrides/ay11.scss
> [ACS-8099] [ACA] Testing Angular 15 - Accessibility for search text area

- projects/aca-content/src/lib/ui/overrides/ay11.scss
…and filter
> - [ ] Bugfix
**Does this PR introduce a breaking change?** (check one …
> [ACS-8100] [ACA] Angular 15 accessibility for search facet and filter

- package-lock.json
- package.json
> Update ADF dependencies

- package-lock.json
- package.json
> - [ ] Bugfix
> - [x] Other... Please describe: dependency update …
> Manual ADF dependencies bump

- projects/aca-content/src/lib/components/context-menu/context-menu-item.component.ts
- projects/aca-content/src/lib/components/context-menu/context-menu.component.ts
- projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.ts
- projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.ts
- projects/aca-content/src/lib/components/favorites/favorites.component.ts
- projects/aca-content/src/lib/components/files/files.component.html
- projects/aca-content/src/lib/components/files/files.component.ts
- projects/aca-content/src/lib/components/libraries/libraries.component.ts
- projects/aca-content/src/lib/components/recent-files/recent-files.component.ts
- projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
- projects/aca-content/src/lib/components/shared-files/shared-files.component.ts
- projects/aca-content/src/lib/components/sidenav/sidenav.component.ts
- projects/aca-content/src/lib/components/toolbar/toggle-favorite-library/toggle-favorite-library.component.ts
- projects/aca-content/src/lib/components/toolbar/toggle-favorite/toggle-favorite.component.ts
- projects/aca-content/src/lib/components/toolbar/toggle-join-library/toggle-join-library-button.component.ts
- projects/aca-content/src/lib/components/toolbar/toggle-join-library/toggle-join-library-menu.component.ts
- projects/aca-content/src/lib/components/trashcan/trashcan.component.ts
- projects/aca-shared/src/lib/components/toolbar/toolbar-action/toolbar-action.component.ts
- projects/aca-shared/src/lib/components/toolbar/toolbar-menu-item/toolbar-menu-item.component.ts
- projects/aca-shared/src/lib/components/toolbar/toolbar-menu/toolbar-menu.component.ts
- projects/aca-shared/src/lib/deprecated/shared-toolbar.module.ts
> - [ ] Bugfix
update imports for newly introduced ADF standalone components
**Does …
> Update imports for new ADF standalone components

- package-lock.json
- package.json
- projects/aca-playwright-shared/src/page-objects/components/dataTable/data-table.component.ts
> - [ ] Bugfix
> - [x] Other... Please describe: dependencies upstream …
> ADF dependencies upstream fix

- projects/aca-playwright-shared/src/page-objects/components/dataTable/data-table.component.ts
> - [ ] Bugfix
Revert changes in #3915 …
> Revert changes in #3915

- projects/aca-content/viewer/src/lib/components/viewer/viewer.component.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8253 …
> [ACS-8253] viewer file name change position on navigation 

- app/src/app.config.json
- app/src/app/app.routes.ts
> - [ ] Bugfix
remove the blank page route from the app as it makes no sense
**Does …
> Remove blank page route

- projects/aca-content/src/lib/ui/overrides/ay11.scss
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8375 …
> [ACS-8375] [ACA] [General] Selecting a checkbox gives a light green color on focus

- projects/aca-content/folder-rules/src/rule-details/actions/rule-action-list.ui-component.scss
- projects/aca-content/src/lib/ui/theme.scss
> [ACS-8376] [ACA] manage rules multiple UI issues in create rule dialog

- e2e/playwright/folder-rules/src/tests/delete-view-rules.e2e.ts
- projects/aca-playwright-shared/src/api/rules-api.ts
- projects/aca-playwright-shared/src/page-objects/components/manageRules/manage-rules.component.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-4896
delete view folder rules …
> [ACS-4896] [E2E] delete view folder rules tests added

- projects/aca-shared/store/src/public-api.ts
> Modal config export fix

- projects/aca-content/folder-rules/src/rule-details/actions/rule-action-list.ui-component.scss
- projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8259
UI has been fixed
**Does …
> [ACS-8259] Testing Angular 15 - Manage rule page issue

- package-lock.json
- package.json
> - [ ] Bugfix
- cleanup the project from the old protractor remains and libs
**Does …
> Cleanup scripts and protractor dependencies

- projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.scss
- projects/aca-content/folder-rules/src/rule-details/edit-rule-dialog.ui-component.scss
- projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss
> - [x] Bugfix
UI for folder select input fields in create/edit rules was broken. Run script on error dropdown UI was …
> [ACS-8452] Fixed UI for folder select input fields in create/edit rules

- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/agents-button/agents-button.component.spec.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-input/search-ai-input.component.html
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-input/search-ai-input.component.spec.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8398
Added tests for part of …
> [ACS-8398] unit tests

- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-input-container/search-ai-input-container.component.spec.ts
- projects/aca-content/src/lib/services/search-ai-navigation.service.spec.ts
- projects/aca-content/src/lib/services/search-ai-navigation.service.ts
- projects/aca-content/src/lib/store/effects/search-ai.effects.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8398
Next part of unit tests …
> [ACS-8398] Unit tests part 2

- projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.html
- projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss
> - [x] Bugfix
* marker was not showing up for rule name field
* marker now shows up …
> [ACS-8450] Fixed issue where required marker * was not showing up for create rule > Name field

- projects/aca-content/src/lib/ui/theme.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8549
tab's titles are centered …
> [ACS-8549] Align mat-tabs

- e2e/playwright/authentication/playwright.config.ts
- e2e/playwright/copy-move-actions/playwright.config.ts
- e2e/playwright/create-actions/playwright.config.ts
- e2e/playwright/favorite-actions/playwright.config.ts
- e2e/playwright/info-drawer/playwright.config.ts
- e2e/playwright/list-views/playwright.config.ts
- e2e/playwright/navigation/playwright.config.ts
- e2e/playwright/pagination/playwright.config.ts
- e2e/playwright/search/playwright.config.ts
- e2e/playwright/share-action/playwright.config.ts
- e2e/playwright/special-permissions-actions-available/playwright.config.ts
- e2e/playwright/upload-download-actions/playwright.config.ts
- e2e/playwright/viewer/playwright.config.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8548
[ACS-8548] [E2E] deleted …
> [ACS-8548] [E2E] deleted unused users from configs

- projects/aca-content/src/lib/components/search/search-input/search-input.component.spec.ts
- projects/aca-content/src/lib/components/search/search-input/search-input.component.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.spec.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
- projects/aca-content/src/lib/components/toolbar/toggle-edit-offline/toggle-edit-offline.component.spec.ts
- projects/aca-content/src/lib/components/toolbar/toggle-edit-offline/toggle-edit-offline.component.ts
- projects/aca-content/src/lib/components/toolbar/toggle-join-library/toggle-join-library-button.component.ts
- projects/aca-content/src/lib/components/toolbar/toggle-join-library/toggle-join-library-menu.component.ts
- projects/aca-content/src/lib/components/toolbar/toggle-join-library/toggle-join-library.component.spec.ts
- projects/aca-content/src/lib/services/content-management.service.spec.ts
- projects/aca-content/src/lib/services/content-management.service.ts
- projects/aca-content/src/lib/services/node-template.service.spec.ts
- projects/aca-content/src/lib/services/node-template.service.ts
- projects/aca-content/src/lib/store/effects/library.effects.ts
- projects/aca-content/src/lib/store/effects/template.effects.spec.ts
- projects/aca-content/src/lib/store/effects/template.effects.ts
- projects/aca-content/src/lib/store/effects/upload.effects.ts
- projects/aca-shared/store/src/effects/router.effects.ts
> - [ ] Bugfix
- switch to using native ADF `NotificationService` where NgRx is not …
> Use ADF Notification Service instead of NgRx store

- projects/aca-content/src/lib/ui/theme.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8559
padding is fixed
**Does …
> [ACS-8559] Fix paddings for dialog

- projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.scss
https://hyland.atlassian.net/browse/ACS-8458
> - [ ] Bugfix …
> [ACS-8458] Review css selectors

- package-lock.json
- package.json
> Fix eslint

- .github/workflows/pull-request.yml
- package-lock.json
- package.json
- projects/aca-content/src/lib/components/details/details.component.spec.ts
- projects/aca-content/src/lib/components/details/details.component.ts
- projects/aca-content/src/lib/components/dl-custom-components/tags-column/tags-column.component.ts
- projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.ts
- projects/aca-content/src/lib/components/favorites/favorites.component.ts
- projects/aca-content/src/lib/components/files/files.component.ts
- projects/aca-content/src/lib/components/info-drawer/metadata-tab/metadata-tab.component.spec.ts
- projects/aca-content/src/lib/components/info-drawer/metadata-tab/metadata-tab.component.ts
- projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
- projects/aca-content/src/lib/testing/app-testing.module.ts
> Update ADF upstream

- e2e/playwright/library-actions/src/tests/library-actions.e2e.ts
- e2e/playwright/viewer/src/tests/viewer.e2e.ts
- projects/aca-content/src/lib/components/dl-custom-components/datatable-cell-badges/datatable-cell-badges.component.scss
- projects/aca-content/src/lib/ui/variables/variables.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7732
Badges have proper size, …
> [ACS-7732] Add missing badges styling

- projects/aca-content/src/lib/components/search/search-results/search-results.component.html
- projects/aca-content/src/lib/components/search/search-results/search-results.component.scss
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8371
Correct title for info …
> [ACS-8371] Fix toolbar button title

- projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.html
- projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8618 …
> [ACS-8618] fix bulk dropdown icon alignment

- projects/aca-content/src/lib/store/effects/node.effects.spec.ts
- projects/aca-content/src/lib/store/effects/node.effects.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/ACS-6712
Details panel can be …
> [ACS-6712] Expanding the details panel from the viewer doesn't work

- app/src/app.config.json
- app/src/app/components/login/app-login.component.html
- app/src/app/components/login/app-login.component.ts
- karma.conf.js
- projects/aca-content/src/lib/components/info-drawer/versions-tab/versions-tab.component.ts
- projects/aca-content/src/lib/services/content-management.service.spec.ts
- projects/aca-content/src/lib/services/content-management.service.ts
- projects/aca-content/src/lib/store/effects/upload.effects.spec.ts
- projects/aca-content/viewer/src/lib/components/viewer/viewer.component.html
- projects/aca-content/viewer/src/lib/components/viewer/viewer.component.spec.ts
- projects/aca-content/viewer/src/lib/components/viewer/viewer.component.ts
- projects/aca-shared/src/lib/services/app-settings.service.ts
> ACS-8404: Update application settings service

- .github/workflows/pull-request.yml
Daily cron E2E fix https://hyland.atlassian.net/browse/ACS-8660
> [ACS-8660] Fix daily cron e2e

- projects/aca-content/src/lib/store/effects/app.effects.ts
> Refactor AppEffects

- projects/aca-content/src/lib/store/effects/app.effects.ts
- projects/aca-content/src/lib/store/effects/library.effects.ts
- projects/aca-shared/store/src/effects/router.effects.ts
> Refactor effects to use inject()

- scripts/gh/update/latest-version-of.js
> Upstream made more future-proof

- projects/aca-content/assets/i18n/en.json
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/agents-button/agents-button.component.html
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/agents-button/agents-button.component.spec.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/agents-button/agents-button.component.ts
https://hyland.atlassian.net/browse/ACS-8664
ADF PR: https://github.com/Alfresco/alfresco-ng2-components/pull/10174
> [ACS-8664] generic question redirection to hx insight page

- projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.ts
- projects/aca-content/src/lib/components/search/search-input/search-input.component.ts
https://hyland.atlassian.net/browse/ACS-8743
> Acs 8743 adw click on search button open a blank page

- projects/aca-content/src/lib/components/details/details.component.ts
- projects/aca-content/src/lib/store/effects/node.effects.spec.ts
- projects/aca-content/src/lib/store/effects/node.effects.ts
https://hyland.atlassian.net/browse/ACS-8747
> [ACS-8747] Viewer does not display the content if opened from info drawer expanded panel view

- projects/aca-content/src/lib/aca-content.routes.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.html
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.scss
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.spec.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.ts
- projects/aca-content/viewer/src/lib/services/viewer.service.spec.ts
- projects/aca-content/viewer/src/lib/services/viewer.service.ts
- projects/aca-content/viewer/src/public-api.ts
https://hyland.atlassian.net/browse/ACS-8767
> [ACS-8767] allow to open referenced files

- projects/aca-content/src/lib/store/effects/node.effects.ts
> Refactor injections in effects

- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.spec.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.ts
https://hyland.atlassian.net/browse/ACS-8833
> [ACS-8833] Displaying error page when there is no selected nodes

- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.scss
https://hyland.atlassian.net/browse/ACS-8784
> [ACS-8784] Fixed references layout

- e2e/playwright/authentication/project.json
- e2e/playwright/copy-move-actions/project.json
- e2e/playwright/create-actions/project.json
- e2e/playwright/delete-actions/project.json
- e2e/playwright/edit-actions/project.json
- e2e/playwright/favorite-actions/project.json
- e2e/playwright/folder-rules/project.json
- e2e/playwright/info-drawer/project.json
- e2e/playwright/library-actions/project.json
- e2e/playwright/list-views/project.json
- e2e/playwright/navigation/project.json
- e2e/playwright/pagination/project.json
- e2e/playwright/search/project.json
- e2e/playwright/share-action/project.json
- e2e/playwright/special-permissions-actions-available/project.json
- e2e/playwright/upload-download-actions/project.json
- e2e/playwright/viewer/project.json
https://hyland.atlassian.net/browse/ACS-8866
> [ACS-8866] [E2E] Added UI, Debug and Headed modes to NX console

- e2e/playwright/authentication/exclude.tests.json
- e2e/playwright/authentication/src/tests/general.e2e.ts
https://hyland.atlassian.net/browse/ACS-5996
> [ACS-5996] [E2E] fixed C286473 e2e test

- projects/aca-content/src/lib/components/search/search-input/search-input.component.ts
> Router might be undefined added safe check

- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.scss
https://hyland.atlassian.net/browse/ACS-8807
> [ACS-8807] Fixed answer formatting

- projects/aca-content/src/lib/ui/overrides/adf-pagination.theme.scss
https://hyland.atlassian.net/browse/MNT-24648?focusedCommentId=2205803
> [MNT-24648] Turn page selector button visible

- projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.html
- projects/aca-content/src/lib/components/search/search-input/search-input.component.html
- projects/aca-playwright-shared/src/api/favorites-api.ts
- projects/aca-playwright-shared/src/api/file-actions.ts
- projects/aca-playwright-shared/src/api/nodes-api.ts
- projects/aca-playwright-shared/src/api/queries-api.ts
- projects/aca-playwright-shared/src/api/search-api.ts
- projects/aca-playwright-shared/src/api/shared-links-api.ts
https://hyland.atlassian.net/browse/ACS-8924
> [ACS-8924] Failing Sonar job

- projects/aca-content/src/lib/components/search/search-save/sidenav/save-search-sidenav.component.html
- projects/aca-content/src/lib/components/search/search-save/sidenav/save-search-sidenav.component.ts
- projects/aca-content/src/lib/components/sidenav/components/expand-menu.component.html
- projects/aca-content/src/lib/components/sidenav/components/expand-menu.component.ts
- projects/aca-content/src/lib/components/sidenav/directives/action.directive.ts
Fixes https://hyland.atlassian.net/browse/ACS-8991, depends on https://github.com/Alfresco/alfresco-ng2-components/pull/10393
> [ACS-8991] Fix sidenav issue when clicking on manage saved searches

- projects/aca-content/src/lib/components/context-menu/context-menu.component.spec.ts
- projects/aca-content/src/lib/components/context-menu/context-menu.component.ts
https://hyland.atlassian.net/browse/ACS-8898
> [ACS-8898] Empty context menu on multi-selected libraries

- e2e/playwright/list-views/exclude.tests.json
- e2e/playwright/list-views/src/tests/sort-list.e2e.ts
https://hyland.atlassian.net/browse/ACS-8993
> [ACS-8993] [E2E] fixed expect in sorting order for C261147

- projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
https://hyland.atlassian.net/browse/ACS-9010
> [ACS-9010] Loading spinner is not shown on search results page when filtering for files or folders

- projects/aca-content/assets/i18n/en.json
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.spec.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.ts
https://hyland.atlassian.net/browse/ACS-8999
ADF PR: https://github.com/Alfresco/alfresco-ng2-components/pull/10431
> [ACS-8999] rename confirmation button label for closing conversation dialog

- package-lock.json
- projects/aca-content/src/lib/components/sidenav/sidenav.component.scss
> [ACS-9049] [ACA] sidebar is missing panels and has broken styles

- .eslintrc.json
- .github/workflows/pull-from-crowdin.yml
- .github/workflows/release.yml
- crowdin.yml
Add new workflow to pull translated entries from Crowdin when they're ready, it should automatically create PR, added also a new step in release process to push new translation keys to Crowdin if any were added.
https://hyland.atlassian.net/browse/ACS-9042
> [ACS-9042]  Introduce Crowdin related workflows and Crowdin config

- projects/aca-content/assets/i18n/en.json
> Test translation added

- projects/aca-content/assets/i18n/en.json
> Test translation cleanup

- e2e/playwright/navigation/.eslintrc.json
- package-lock.json
- projects/aca-content/folder-rules/src/rule-set-picker/rule-set-picker.smart-component.spec.ts
- projects/aca-content/folder-rules/src/rule-set-picker/rule-set-picker.smart-component.ts
- projects/aca-shared/src/lib/components/page-layout/page-layout-content.component.ts
- projects/aca-shared/src/lib/components/page-layout/page-layout-error.component.ts
- projects/aca-shared/src/lib/components/page-layout/page-layout-header.component.ts
- projects/aca-shared/src/lib/components/page-layout/page-layout.component.html
https://hyland.atlassian.net/browse/ACS-9068
> [ACS-9068] [ACA] - Pipeline changes enabling packagage release

- projects/aca-shared/src/lib/components/toolbar/toolbar-action/toolbar-action.component.scss
- projects/aca-shared/src/lib/components/toolbar/toolbar-action/toolbar-action.component.ts
https://hyland.atlassian.net/browse/ACS-9075
ADF PR: https://github.com/Alfresco/alfresco-ng2-components/pull/10489
> [ACS-9075] buttons texts have different color 2

- projects/aca-playwright-shared/package.json
https://hyland.atlassian.net/browse/ACS-9100
> ACS-9100-ACA-playwright-package-version-fix

- projects/aca-content/src/lib/components/files/files.component.scss
- projects/aca-content/src/lib/components/files/files.component.ts
- projects/aca-content/src/lib/ui/theme.scss
> [ACS-9103] [ACA] - UI changes fix on input field

- projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss
> [ACS-9111][Angular 17] - manage rules filling the rule name makes the input name jump

- projects/aca-content/src/lib/components/details/details.component.spec.ts
- projects/aca-content/src/lib/components/details/details.component.ts
https://hyland.atlassian.net/browse/ACS-6486
> [ACS-6486] in breadcrumb the file title is not updating after editing

- e2e/playwright/list-views/src/tests/sort-list.e2e.ts
- package-lock.json
- package.json
- projects/aca-content/src/lib/components/search/search-save/sidenav/save-search-sidenav.component.spec.ts
- projects/aca-content/src/lib/components/search/search-save/sidenav/save-search-sidenav.component.ts
https://hyland.atlassian.net/browse/ACS-9166
Depends on https://github.com/Alfresco/alfresco-ng2-components/pull/10559
> [ACS-9166] Migrate Saved Searches to preferences API from config file

- e2e/playwright/list-views/src/tests/sort-list.e2e.ts
- package-lock.json
- package.json
- projects/aca-content/src/lib/components/search/search-save/sidenav/save-search-sidenav.component.spec.ts
- projects/aca-content/src/lib/components/search/search-save/sidenav/save-search-sidenav.component.ts
Reverts Alfresco/alfresco-content-app#4340
> Revert "[ACS-9166] Migrate Saved Searches to preferences API from config file"

- projects/aca-content/src/lib/components/search/search-save/sidenav/save-search-sidenav.component.spec.ts
- projects/aca-content/src/lib/components/search/search-save/sidenav/save-search-sidenav.component.ts
https://hyland.atlassian.net/browse/ACS-9119
> [ACS-9119] Saved Search navbar title now gets translated

- projects/aca-content/assets/i18n/ar.json
- projects/aca-content/assets/i18n/cs.json
- projects/aca-content/assets/i18n/da.json
- projects/aca-content/assets/i18n/de.json
- projects/aca-content/assets/i18n/en.json
- projects/aca-content/assets/i18n/es.json
- projects/aca-content/assets/i18n/fi.json
- projects/aca-content/assets/i18n/fr.json
- projects/aca-content/assets/i18n/it.json
- projects/aca-content/assets/i18n/ja.json
- projects/aca-content/assets/i18n/nb.json
- projects/aca-content/assets/i18n/nl.json
- projects/aca-content/assets/i18n/no.json
- projects/aca-content/assets/i18n/pl.json
- projects/aca-content/assets/i18n/pt-BR.json
- projects/aca-content/assets/i18n/ru.json
- projects/aca-content/assets/i18n/sv.json
- projects/aca-content/assets/i18n/zh-CN.json
https://hyland.atlassian.net/browse/ACS-9213
> [ACS-9213] Update license visible on login page from SSO

- projects/aca-content/folder-rules/assets/i18n/en.json
- projects/aca-content/folder-rules/src/rule-details/actions/rule-action-list.ui-component.html
- projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.html
- projects/aca-content/folder-rules/src/rule-details/edit-rule-dialog.ui-component.html
https://hyland.atlassian.net/browse/ACS-9236
> [ACS-9236] a11y testing: Create Rule - Buttons must have discernible text

- projects/aca-content/src/lib/components/search/search-input/search-input.component.html
- projects/aca-content/src/lib/components/search/search-input/search-input.component.scss
https://hyland.atlassian.net/browse/ACS-9229
> [ACS-9229] a11y testing: Search Page / Elements must only use supported ARIA attributes

- .github/actions/run-e2e-playwright/action.yml
- e2e/playwright/edit-actions/exclude.tests.json
- e2e/playwright/edit-actions/src/tests/edit-offline.e2e.ts
https://hyland.atlassian.net/browse/ACS-9187
> [ACS-9187] [E2E] Fix XAT-5304 - file downloading is flaky

- projects/aca-content/assets/i18n/en.json
- projects/aca-content/src/lib/components/files/files.component.html
- projects/aca-content/src/lib/components/files/files.component.spec.ts
- projects/aca-content/src/lib/components/files/files.component.ts
- projects/aca-content/src/lib/store/effects/library.effects.spec.ts
- projects/aca-content/src/lib/store/effects/library.effects.ts
https://hyland.atlassian.net/browse/ACS-9344
> [ACS-9344] change permissions error message for opening records management library

- projects/aca-shared/src/lib/services/app.extension.service.spec.ts
- projects/aca-shared/src/lib/services/app.extension.service.ts
https://hyland.atlassian.net/browse/ACS-9369
> [ACS-9369] Resolved issues where visibility rules with a single element array would log errors

- projects/aca-content/src/lib/components/search/search-input/search-input.component.scss
https://hyland.atlassian.net/browse/ACA-4735
> [ACA-4735] Fix search input focus styles

- projects/aca-content/assets/app.extensions.json
Fixes https://hyland.atlassian.net/browse/ACS-9346
> [ACS-9346] Use visibility rules as array

- .github/actions/deploy-local-acs/action.yml
- .github/dependabot.yml
> OPSEXP-3069 Use kubectl-wait action

- .github/acs-deployment-values-override.yaml
- .github/actions/deploy-local-acs/action.yml
Bump to the latest version of helm charts and latest repository tag
> Bump tests environment to latest chart/tag

- docs/features/search-forms.md
- docs/features/search-results.md
- docs/getting-started/sso.md
- docs/ja/features/search-results.md
- docs/ja/getting-started/prerequisites.md
- docs/ja/getting-started/sso.md
- docs/tutorials/search-form.md
https://hyland.atlassian.net/browse/ACS-9371
> [ACS-9371] Migrate docs from docs.alfresco to support.hyland

- e2e/playwright/info-drawer/src/tests/file-preview.e2e.ts
https://hyland.atlassian.net/browse/ACS-9424
> [ACS-9424] [E2E] Update the checkFileContent function in file-preview.e2e.ts to not use raw locators

- projects/aca-content/assets/i18n/en.json
- projects/aca-content/src/lib/services/content-management.service.spec.ts
- projects/aca-content/src/lib/services/content-management.service.ts
This PR adds snackbar notifications for favorites actions.
Fixes #953 
https://hyland.atlassian.net/browse/ACS-9398
> [ACS-9398] Add snackbar notifications for favorite actions

- projects/aca-content/folder-rules/src/rule-details/edit-rule-dialog.smart-component.spec.ts
- projects/aca-content/folder-rules/src/rule-details/edit-rule-dialog.ui-component.ts
https://hyland.atlassian.net/browse/ACS-9386
> [ACS-9386] Fix wrong dialog title & button text on edit rule dialog

- projects/aca-content/src/lib/components/details/details.component.spec.ts
> Ng18 migration fix unit tests

- docs/extending/rules.md
- projects/aca-content/assets/app.extensions.json
- projects/aca-content/src/lib/aca-content.module.ts
- projects/aca-shared/rules/src/app.rules.spec.ts
- projects/aca-shared/rules/src/app.rules.ts
https://hyland.atlassian.net/browse/ACS-9388
> [ACS-9388] Print button is now disabled in viewer for media files

- projects/aca-content/src/lib/ui/theme.scss
> [ACS-9451][ACA] Create rule dialog has smaller width

- projects/aca-content/src/lib/ui/theme.scss
> [ACS-9449][ACA] ng18 - Arrow in the profile button dialog is displaced

- e2e/playwright/info-drawer/src/tests/comments.e2e.ts
- projects/aca-playwright-shared/src/page-objects/components/adf-info-drawer.component.ts
https://hyland.atlassian.net/browse/ACS-9372
> [ACS-9372] [E2E] Fixed eslint errors

- e2e/playwright/create-actions/src/tests/create-folder.e2e.ts
https://hyland.atlassian.net/browse/ACS-9255
> [ACS-9255] [E2E] Automated XAT-17591

- e2e/playwright/list-views/exclude.tests.json
- e2e/playwright/list-views/src/tests/sort-list.e2e.ts
https://hyland.atlassian.net/browse/ACS-9294
> [ACS-9294] [E2E] XAT-4526 stable and included

- e2e/playwright/authentication/src/tests/general.e2e.ts
- e2e/playwright/authentication/src/tests/login.e2e.ts
- e2e/playwright/info-drawer/exclude.tests.json
- e2e/playwright/info-drawer/src/tests/file-preview.e2e.ts
- e2e/playwright/list-views/src/tests/permissions.e2e.ts
- e2e/playwright/upload-download-actions/src/tests/upload-new-version.e2e.ts
- e2e/playwright/upload-download-actions/src/tests/upload.e2e.ts
- e2e/playwright/viewer/src/tests/viewer-action.e2e.ts
https://hyland.atlassian.net/browse/ACS-9301
> [ACS-9301] [E2E] Updated IDs with the new test cases

- app/src/app.config.json
- e2e/playwright/search/exclude.tests.json
https://hyland.atlassian.net/browse/MNT-24848
> [MNT-24848] Include properties in search header calls

- .github/acs-deployment-values-override.yaml
- projects/aca-content/src/lib/dialogs/folder-details/folder-information.component.spec.ts
- projects/aca-content/src/lib/dialogs/folder-details/folder-information.component.ts
https://hyland.atlassian.net/browse/ACS-9466
> [ACS-9466] Folder information dialog no longer displays error message if response returned from API is "IN_PROGRESS'

- tsconfig.adf.json
https://hyland.atlassian.net/browse/ACS-9427
> [ACS-9427] Fix for linking with ADF

- projects/aca-shared/src/lib/services/router.extension.service.spec.ts
- projects/aca-shared/src/lib/services/router.extension.service.ts
…
https://hyland.atlassian.net/browse/ACS-9510
> [ACS-9510] Tasks and processes are not displayed when About page is refreshed

- projects/aca-content/src/lib/aca-content.module.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-marked-options.spec.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-marked-options.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.spec.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.ts
https://hyland.atlassian.net/browse/ACS-9535
> [ACS-9535] open links inside strings in md format as separated browser tab

- Dockerfile
https://hyland.atlassian.net/browse/ACS-9570
> [ACS-9570] Update Dockerfile node version to 20.18

- projects/aca-content/src/lib/ui/colors.scss
https://hyland.atlassian.net/browse/AAE-34498
> AAE-34498 Add missing palette color vars

- projects/aca-content/src/lib/components/details/details.component.spec.ts
- projects/aca-content/src/lib/components/details/details.component.ts
https://hyland.atlassian.net/browse/ACS-9554
> [ACS-9554] Redirect from permissions page after node delete

- e2e/playwright/search/exclude.tests.json
- e2e/playwright/search/src/tests/search-filters-date.e2e.ts
https://hyland.atlassian.net/browse/ACS-9482
> [ACS-9482] [E2E] included XAT-17700 and XAT-17702

- projects/aca-content/ng-package.json
- projects/aca-content/package.json
https://hyland.atlassian.net/browse/AAE-34576
> AAE-34576 Setup missing ngx-markdown dependency

- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-input/search-ai-input.component.spec.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-input/search-ai-input.component.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.scss
- projects/aca-content/src/lib/components/sidenav/sidenav.component.spec.ts
- projects/aca-content/src/lib/components/sidenav/sidenav.component.ts
- projects/aca-shared/src/lib/services/navigation-history.service.spec.ts
- projects/aca-shared/src/lib/services/navigation-history.service.ts
https://hyland.atlassian.net/browse/ACS-9546
> [ACS-9546] knowledge retrieval question is repeated when new question is asked

- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.scss
https://hyland.atlassian.net/browse/ACS-9601
> [ACS-9601] Fixed cut reference image

- e2e/playwright/info-drawer/src/tests/file-folder-properties.e2e.ts
https://hyland.atlassian.net/browse/ACS-9666
> [ACS-9666] fix-info-drawer-test

- crowdin.yml
https://hyland.atlassian.net/browse/ACS-9648
> [ACS-9648] Change Crowdin update strategy

- e2e/playwright/search/src/tests/search-filters-tags.e2e.ts
- projects/aca-playwright-shared/src/api/tags-api.ts
https://hyland.atlassian.net/browse/ACS-7706
ADF PR: https://github.com/Alfresco/alfresco-ng2-components/pull/10869
applications PR: https://github.com/Alfresco/alfresco-applications/pull/1080
> [ACS-7706] Fixed e2e

- app/src/styles.scss
https://hyland.atlassian.net/browse/ACS-9670
> [ACS-9670] Set color scheme to light

- app/src/app/components/login/app-login.component.ts
- projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-results/search-ai-results.component.scss
- projects/aca-content/src/lib/components/view-profile/view-profile.component.scss
- projects/aca-content/src/lib/ui/overrides/ay11.scss
- projects/aca-content/src/lib/ui/theme.scss
- projects/aca-content/src/lib/ui/variables/variables.scss
- projects/aca-shared/src/lib/components/open-in-app/open-in-app.component.scss
https://hyland.atlassian.net/browse/ACS-9670
> [ACS-9670] Add white background to login screen

- projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.spec.ts
- projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.ts
- projects/aca-content/src/lib/services/content-management.service.spec.ts
- projects/aca-content/src/lib/services/content-management.service.ts
https://hyland.atlassian.net/browse/ACS-9702
> [ACS-9702] Restore focus after closing dialog

- extension.schema.json
- projects/aca-content/src/lib/components/info-drawer/metadata-tab/metadata-tab.component.spec.ts
- projects/aca-content/src/lib/components/info-drawer/metadata-tab/metadata-tab.component.ts
https://hyland.atlassian.net/browse/MNT-24923
alfresco-applications PR: https://github.com/Alfresco/alfresco-applications/pull/1114
ADF PR: https://github.com/Alfresco/alfresco-ng2-components/pull/10930
> [MNT-24923] legal hold hold capabilities are not verified properly

- projects/aca-content/folder-rules/src/rule-list/rule-list-item/rule-list-item.ui-component.ts
- projects/aca-content/folder-rules/src/services/folder-rules.service.spec.ts
- projects/aca-content/folder-rules/src/services/folder-rules.service.ts
https://hyland.atlassian.net/browse/ACS-5503
> [ACS-5503] Folder rules rule update with correct error message when definition is invalid

- package-lock.json
- package.json
https://hyland.atlassian.net/browse/ACS-9782
> [ACS-9782] Viewer doesn't work when running with ADF linked

- e2e/playwright/list-views/exclude.tests.json
- e2e/playwright/search/exclude.tests.json
- package-lock.json
- package.json
- projects/aca-content/package.json
- projects/aca-shared/package.json
Fix upstream because of changes in https://hyland.atlassian.net/browse/AAE-36173
> [AAE-36173] fix upstream

- e2e/playwright/search/exclude.tests.json
- e2e/playwright/search/src/tests/search-filters-date.e2e.ts
- e2e/playwright/search/src/tests/search-highlighting.e2e.ts
- e2e/playwright/search/src/tests/search-sorting.e2e.ts
- projects/aca-playwright-shared/src/page-objects/components/search/search-filters/search-filters-date.component.ts
https://hyland.atlassian.net/browse/ACS-9756
> [ACS-9756] [E2E] Tests 5571, 17700, 17120, 5567 fixed and included

- e2e/playwright/search/exclude.tests.json
- projects/aca-content/src/lib/components/search/search-input/search-input.component.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.spec.ts
- projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
- projects/aca-content/src/lib/utils/aca-search-utils.spec.ts
- projects/aca-content/src/lib/utils/aca-search-utils.ts
- projects/aca-playwright-shared/src/page-objects/components/search/search-filters/search-filters-properties.component.ts
https://hyland.atlassian.net/browse/MNT-25070
> MNT-25070: ADW - Search request is altered when using quote marks

- e2e/playwright/viewer/exclude.tests.json
- projects/aca-content/ms-office/src/aos-extension.module.ts
- projects/aca-content/src/lib/components/dl-custom-components/datatable-cell-badges/datatable-cell-badges.component.spec.ts
- projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.spec.ts
- projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.spec.ts
- projects/aca-content/src/lib/components/libraries/libraries.component.spec.ts
- projects/aca-content/src/lib/services/content-management.service.spec.ts
- projects/aca-content/src/lib/services/node-template.service.spec.ts
- projects/aca-content/src/lib/store/app-store.module.ts
- projects/aca-content/src/lib/store/effects/contextmenu.effects.spec.ts
- projects/aca-content/src/lib/store/effects/download.effects.spec.ts
- projects/aca-content/src/lib/store/effects/library.effects.spec.ts
- projects/aca-content/src/lib/store/effects/node.effects.spec.ts
- projects/aca-content/src/lib/store/effects/search-ai.effects.spec.ts
- projects/aca-content/src/lib/store/effects/search.effects.spec.ts
- projects/aca-content/src/lib/store/effects/template.effects.spec.ts
- projects/aca-content/src/lib/store/effects/upload.effects.spec.ts
- projects/aca-content/src/lib/store/effects/viewer.effects.spec.ts
- projects/aca-content/src/lib/testing/app-testing.module.ts
- projects/aca-shared/src/lib/testing/lib-testing-module.ts
- projects/aca-shared/store/src/effects/router.effects.spec.ts
https://hyland.atlassian.net/browse/ACS-9911
> [ACS-9911] Upgrade NgRx API

- projects/aca-content/assets/i18n/ar.json
- projects/aca-content/assets/i18n/cs.json
- projects/aca-content/assets/i18n/da.json
- projects/aca-content/assets/i18n/de.json
- projects/aca-content/assets/i18n/es.json
- projects/aca-content/assets/i18n/fi.json
- projects/aca-content/assets/i18n/fr.json
- projects/aca-content/assets/i18n/it.json
- projects/aca-content/assets/i18n/ja.json
- projects/aca-content/assets/i18n/nl.json
- projects/aca-content/assets/i18n/no.json
- projects/aca-content/assets/i18n/pl.json
- projects/aca-content/assets/i18n/pt-BR.json
- projects/aca-content/assets/i18n/ru.json
- projects/aca-content/assets/i18n/sv.json
- projects/aca-content/assets/i18n/zh-CN.json
Reverts Alfresco/alfresco-content-app#4713
> Revert "GH Auto: Automated Update of Translations from Crowdin"

- projects/aca-shared/store/src/selectors/app.selectors.ts
https://hyland.atlassian.net/browse/ACS-9907
alfresco-applications PR: https://github.com/Alfresco/alfresco-applications/pull/1198
> [ACS-9907] create store selector with current acs version

- projects/aca-content/assets/i18n/en.json
- projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.html
- projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.spec.ts
- projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.ts
- projects/aca-content/src/lib/components/search/search-input/search-input.component.html
- projects/aca-content/src/lib/components/search/search-input/search-input.component.scss
- projects/aca-content/src/lib/components/search/search-input/search-input.component.spec.ts
- projects/aca-content/src/lib/components/search/search-input/search-input.component.ts
- projects/aca-shared/src/lib/validators/no-whitespace.validator.spec.ts
- projects/aca-shared/src/lib/validators/no-whitespace.validator.ts
- projects/aca-shared/src/public-api.ts
https://hyland.atlassian.net/browse/ACS-9374
https://hyland.atlassian.net/browse/ACS-9590
> [ACS-9374] [ACS-9590] Fix search pop up and infinite loading animation

- app/src/app/app.config.ts
- projects/aca-content/folder-rules/src/rule-set-picker/rule-set-picker.smart-component.spec.ts
- projects/aca-content/ms-office/src/aos-extension.service.spec.ts
- projects/aca-content/src/lib/components/context-menu/context-menu.service.spec.ts
- projects/aca-content/src/lib/components/details/details.component.spec.ts
- projects/aca-content/src/lib/components/dl-custom-components/datatable-cell-badges/datatable-cell-badges.component.spec.ts
- projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.spec.ts
- projects/aca-content/src/lib/components/info-drawer/versions-tab/versions-tab.component.spec.ts
- projects/aca-content/src/lib/components/search/search-save/list/smart-list/saved-searches-smart-list.component.spec.ts
- projects/aca-content/src/lib/testing/app-testing.module.ts
- projects/aca-shared/src/lib/components/document-base-page/document-base-page.spec.ts
- projects/aca-shared/src/lib/services/app.extension.service.spec.ts
- projects/aca-shared/src/lib/services/app.service.spec.ts
- projects/aca-shared/src/lib/testing/lib-testing-module.ts
https://hyland.atlassian.net/browse/AAE-37293
> AAE-37293 switch to provider api

- .github/actions/deploy-local-acs/action.yml
> OPSEXP-3437 Increase ingress creation timeout for setup-kind action

- e2e/playwright/folder-rules/exclude.tests.json
- e2e/playwright/info-drawer/exclude.tests.json
https://hyland.atlassian.net/browse/ACS-10091
> [ACS-10091] exclude e2e test

- projects/aca-content/src/lib/utils/aca-search-utils.spec.ts
- projects/aca-content/src/lib/utils/aca-search-utils.ts
https://hyland.atlassian.net/browse/ACS-10076
> [ACS-10076] [ACA] Search input clears when using special search with text:value

- projects/aca-content/src/lib/services/content-management.service.spec.ts
- projects/aca-content/src/lib/services/content-management.service.ts
https://hyland.atlassian.net/browse/MNT-25285
> [MNT-25285] Unable to change version preview from within the preview window

- .github/actions/deploy-local-acs/action.yml
- projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.spec.ts
- projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.ts
https://hyland.atlassian.net/browse/ACS-10116
> [ACS-10116] [ACA] Search page renders HTML from the Description,Title field instead of showing it as plain text

- .github/actions/get-image-tag/action.yml
- .github/actions/git-tag/action.yml
- .github/actions/run-e2e-playwright/action.yml
- .github/actions/setup/action.yml
- .github/actions/update-library-versions/action.yml
https://hyland.atlassian.net/browse/ACS-10124
> [ACS-10124] Fix Change this action to not use user-controlled data directly in a run block sonar issue

- package-lock.json
- package.json
- projects/aca-content/src/lib/ui/custom-theme.scss
- projects/aca-content/src/lib/ui/overrides/adf-variables.scss
- projects/aca-content/src/lib/ui/theme.scss
https://hyland.atlassian.net/browse/ACS-10448
Depends on https://github.com/Alfresco/alfresco-ng2-components/pull/11235
> [ACS-10448] Move theme variables from ADF to ACA

- projects/aca-content/about/src/about.component.html
- projects/aca-content/assets/i18n/en.json
https://hyland.atlassian.net/browse/ACS-10297
> [ACS-10297] Add label and title to back button in about section

- projects/aca-content/folder-rules/assets/i18n/en.json
- projects/aca-content/folder-rules/src/rule-list/rule-list-item/rule-list-item.ui-component.html
https://hyland.atlassian.net/browse/ACS-10285
> [ACS-10285] Fix rule toggle label

- e2e/playwright/folder-rules/exclude.tests.json
- projects/aca-content/folder-rules/assets/i18n/en.json
- projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.spec.ts
- projects/aca-content/folder-rules/src/rule-list/rule-list/rule-list.ui-component.html
- projects/aca-content/folder-rules/src/rule-list/rule-list/rule-list.ui-component.scss
- projects/aca-content/folder-rules/src/rule-list/rule-list/rule-list.ui-component.spec.ts
- projects/aca-content/folder-rules/src/rule-list/rule-list/rule-list.ui-component.ts
https://hyland.atlassian.net/browse/ACS-10286
> [ACS-10286] Add label and aria expanded to the rule set header
