Alfresco/alfresco-content-app

docs/docker.md
In the docker example we were proposing that folks map port 80 from the docker container to port 80 on localhost. Unless the user is running as root, they likely won't be able to bind to any port < 1024. As such, I am proposing we bind to the local port 8888. Could change it to 3000 to be in-line with the `docker compose` example; but to me the use cases are different so I like having different ports...
=> Don't try to port map to 80 as it is < 1024 in docker docs

src/app/common/common.module.ts, src/app/common/directives/node-unshare.directive.ts, src/app/components/shared-files/shared-files.component.html, src/app/components/shared-files/shared-files.component.ts, src/assets/i18n/en.json
- unshare link button
- unshare multiple selected links
- remove "Delete" and "Move" actions from the "Shared" page toolbar
Known issues:
it may take some time for the REPO to reflect the new state
=> [ACA-591] unsharing links

src/app/common/directives/node-copy.directive.ts, src/app/common/directives/node-delete.directive.spec.ts, src/app/common/directives/node-delete.directive.ts, src/app/common/directives/node-move.directive.ts, src/app/common/services/content-management.service.ts, src/app/components/favorites/favorites.component.spec.ts, src/app/components/favorites/favorites.component.ts, src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts, src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.spec.ts, src/app/components/preview/preview.component.ts, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/recent-files/recent-files.component.ts, src/app/components/shared-files/shared-files.component.spec.ts, src/app/components/shared-files/shared-files.component.ts, src/app/components/sidenav/sidenav.component.spec.ts, src/app/components/trashcan/trashcan.component.spec.ts, src/app/components/trashcan/trashcan.component.ts
- delete node from the Viewer (with undo support)
- content management service enhancements
- rename events to better reflect their nature
- new api to delete/restore nodes
=> [ACA-1135] spike on deleting nodes from the viewer

src/app/common/directives/node-copy.directive.spec.ts, src/app/common/directives/node-copy.directive.ts, src/app/common/services/node-actions.service.spec.ts, src/app/components/preview/preview.component.spec.ts
- tests need to references only the minimal required modules/services/etc.
- use `NO_ERRORS_SCHEMA` instead of recreating entire application tree for each test run
- avoid using CoreModule or any module that has massive sets of imports (i.e Material modules)
**SidenavComponent**
Before: Executed 6 of 299 (skipped 293) SUCCESS (22.266 secs / 21.643 secs)
After: Executed 6 of 299 (skipped 293) SUCCESS (7.888 secs / 7.607 secs)
**PreviewComponent**
Before: Executed 45 of 299 (skipped 254) SUCCESS (1 min 6.31 secs / 1 min 6.028 secs)
After: Executed 45 of 299 (skipped 254) SUCCESS (1.74 secs / 1.516 secs)
**NodeActionsService**
Before: Executed 62 of 299 (skipped 237) SUCCESS (1 min 38.092 secs / 1 min 37.774 secs)
After: Executed 62 of 299 (skipped 237) SUCCESS (1.425 secs / 1.215 secs)
=> [ACA-1137] Spike - Improving speed of unit tests 

src/app/app.module.ts, src/app/components/empty-folder/empty-folder.component.html, src/app/components/empty-folder/empty-folder.component.scss, src/app/components/empty-folder/empty-folder.component.spec.ts, src/app/components/empty-folder/empty-folder.component.ts, src/app/components/favorites/favorites.component.html, src/app/components/libraries/libraries.component.html, src/app/components/recent-files/recent-files.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html, src/app/ui/overrides/_alfresco-document-list.scss
- move "empty folder" to a separate component
- remove styles from the document list that are related to old "empty folder" implementation
=> move empty folder UI into separate component

src/app/common/services/node-actions.service.ts
code is no longer needed because [ACA-1054] is fixed since this ADF change was made:
https://github.com/Alfresco/alfresco-ng2-components/pull/2868/files#diff-80f7c6137233f6a2440b1e75cc0b9244R614
=> Remove commented out code related to the fix for [ACA-1054]

scripts/update-version.sh
- use only currently needed dependencies (`core` and `content-services`)
- use `npm install` to setup new versions, that ensures also the `package-lock.json` file is updated as well
- evaluates versions of the libs, can be used with `alpha`, `beta` tags as well
Examples:
```sh
./update-version.sh -v alpha
./update-version.sh -v beta
./update-version.sh -v 2.3.0-18ec14f2109fb6249e9d67ffd5edc3be157b8f18
```
=> evaluate versions and update with package lock

.travis.yml, README.md
=> [ACA-1266] use 'npm ci' for faster installs

src/app/ui/overrides/_alfresco-document-list.scss
Hotfix for the background colour regression in ADF 2.3.0. Will be reviewed for ACA 1.3.0 once ADF 2.4.0 alpha with the corresponding fix is out.
=> hotfix for document list background colour

.angular-cli.json, README.md, docs/configuration.md, docs/docker.md, protractor.conf.js
- using standard Angular CLI port 4200 not to have issues with shared local storage when running after ADF demo shell
- allows running both apps in parallel at the same time
=> use default port 4200 for development

src/app.config.json, src/app/app.module.ts, src/app/directives/experimental.directive.ts
```
[ ] Bugfix
[x] Feature
```
This feature will allow us getting more features from ADF early.
Allows toggling features when running application in development mode, and hiding for production.
Add `feature1` key to the `experimental` section in the `app.config.json`:
```json
{
"experimental": {
"feature1": true
}
}
```
Use `*ifExperimental` directive, similar to the `*ngIf`
```html
<button …
```
=> special ifExperimental directive to toggle features

src/app.config.json
```
```
```
[ ] Bugfix
[ ] Feature
```
No buckets were shown for the 'Modified Date' category.
Please check https://issues.alfresco.com/jira/browse/ACA-1562 & ACA-1578
The facet buckets are now displayed for the 'Modified Date' facet.
```
[ ] Yes
[x] No
```
=> [ACA-1578] Facet Intervals - show modified date buckets

docker-entrypoint.sh
```
```
```
[ ] Bugfix
[ ] Feature
```
There is no way of doing path rewriting on the application using nginx for example without setting ./ as base href. 
We dont want to break local development so adding the possibility of changing the base href when running the docker container gives us the flexibility of choosing under which path we want the app to run in.
```
[ ] Yes
[x] No
```
=> fix #653 : add basepath modification at runtime trough env vars

src/app/dialogs/library/library.dialog.html, src/app/dialogs/library/library.dialog.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1957] Create Library - check existent site title by field 

src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.html, src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.spec.ts, src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1957] Library metadata - check title uniqueness

e2e/components/dialog/create-library-dialog.ts, e2e/components/sidenav/sidenav.ts, e2e/suites/actions/create-folder.test.ts, e2e/suites/actions/create-library.test.ts, e2e/suites/application/general.test.ts, e2e/utilities/repo-client/apis/sites/sites-api.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1517] add tests for create library

docs/extending/components.md, src/app/app.module.ts, src/app/components/favorite-libraries/favorite-libraries.component.ts, src/app/components/libraries/libraries.component.ts, src/app/components/toolbar/toggle-favorite-library/toggle-favorite-library.component.spec.ts, src/app/components/toolbar/toggle-favorite-library/toggle-favorite-library.component.ts, src/app/directives/library-favorite.directive.spec.ts, src/app/directives/library-favorite.directive.ts, src/app/extensions/core.extensions.module.ts, src/app/services/content-management.service.ts, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-20] Add/Remove favorite library

docs/extending/application-features.md, docs/extending/components.md, docs/extending/rules.md, src/app/components/search/search-input-control/search-input-control.component.spec.ts, src/app/components/search/search-input-control/search-input-control.component.ts, src/app/components/search/search-input/search-input.component.spec.ts, src/app/components/search/search-input/search-input.component.ts, src/app/components/search/search-libraries-results/search-libraries-query-builder.service.spec.ts, src/app/components/search/search-libraries-results/search-libraries-query-builder.service.ts, src/app/components/search/search-libraries-results/search-libraries-results.component.ts, src/app/directives/library-membership.directive.spec.ts, src/app/directives/library-membership.directive.ts, src/app/services/content-management.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1989
fixes the Jira issue 
```
[ ] Yes
[x] No
```
=> [ACA-19] show search libraries hint

e2e/components/sidenav/sidenav.ts, e2e/configs.ts, e2e/pages/browsing-page.ts, e2e/suites/actions/context-menu-single-selection.test.ts, e2e/suites/actions/create-folder.test.ts, e2e/suites/actions/edit-folder.test.ts, e2e/suites/actions/restore.test.ts, e2e/suites/actions/special-permissions-available-actions.test.ts, e2e/suites/actions/toolbar-single-selection.test.ts, e2e/suites/actions/unshare-file.test.ts, e2e/suites/application/page-titles.test.ts, e2e/suites/info-drawer/library-properties.test.ts, e2e/suites/list-views/empty-list.test.ts, e2e/suites/list-views/favorites.test.ts, e2e/suites/list-views/file-libraries.test.ts, e2e/suites/list-views/permissions.test.ts, e2e/suites/list-views/personal-files.test.ts, e2e/suites/list-views/recent-files.test.ts, e2e/suites/list-views/shared-files.test.ts, e2e/suites/list-views/trash.test.ts, e2e/suites/navigation/breadcrumb.test.ts, e2e/suites/navigation/sidebar.test.ts, e2e/utilities/repo-client/apis/favorites/favorites-api.ts, src/assets/i18n/en.json
add tests for Favorite Libraries
refactor File Libraries related tests to include My Libraries
fix for ACA-2007
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1946] automate tests for Favourite Libraries list

src/app/components/common/trashcan-name-column/trashcan-name-column.component.spec.ts, src/app/components/common/trashcan-name-column/trashcan-name-column.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2005] Trash - display library name

src/app/components/context-menu/context-menu-outside-event.directive.ts, src/app/components/context-menu/context-menu.directive.ts, src/app/components/context-menu/context-menu.directives.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Context menu - librarie files fix 

src/app/components/search/search-input-control/search-input-control.component.html, src/app/components/search/search-input-control/search-input-control.component.scss, src/app/components/search/search-input/search-input.component.html, src/app/components/search/search-input/search-input.component.theme.scss, src/app/components/search/search-input/search-input.component.ts, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1968
improved UX for the search input
```
[ ] Yes
[x] No
```
=> [ACA-1968] Search input tunings

src/app/components/current-user/current-user.component.theme.scss, src/app/components/header/header.component.html, src/app/components/header/header.component.ts, src/app/components/search/search-input-control/search-input-control.component.html, src/app/components/search/search-input-control/search-input-control.component.scss, src/app/components/search/search-input/search-input.component.theme.scss
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1968
'max-width: 959px' screens:
'max-width: 599px' screens:
```
[ ] Yes
[x] No
```
=> [ACA-1968] style search input for smaller screens

cspell.json, e2e/components/data-table/data-table.ts, e2e/components/menu/menu.ts, e2e/components/toolbar/toolbar.ts, e2e/suites/actions/context-menu-multiple-selection.test.ts, e2e/suites/actions/context-menu-single-selection.test.ts, e2e/suites/actions/create-folder.test.ts, e2e/suites/actions/create-library.test.ts, e2e/suites/actions/edit-folder.test.ts, e2e/suites/actions/library-actions.test.ts, e2e/suites/actions/new-menu.test.ts, e2e/suites/actions/permanently-delete.test.ts, e2e/suites/actions/restore.test.ts, e2e/suites/actions/toolbar-single-selection.test.ts, e2e/suites/list-views/empty-list.test.ts, e2e/suites/pagination/pag-search-results.test.ts, e2e/suites/pagination/pag-single-page.test.ts, e2e/utilities/repo-client/apis/nodes/nodes-api.ts, e2e/utilities/repo-client/apis/sites/sites-api.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] add more e2e tests

src/app/services/content-management.service.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2053] Create folder - focus on first form input

src/app/components/common/library-status-column/library-status-column.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/es.json, src/assets/i18n/fr.json, src/assets/i18n/it.json, src/assets/i18n/ja.json, src/assets/i18n/nb.json, src/assets/i18n/nl.json, src/assets/i18n/pt-BR.json, src/assets/i18n/ru.json, src/assets/i18n/zh-CN.json
```
```
```
[ ] Bugfix
[ ] Feature
```
use i18n strings from ADF instead of local copies
```
[ ] Yes
[x] No
```
=> remove duplicated strings, use ADF instead

nginx.conf, src/index.html
```
```
```
[x] Bugfix
[ ] Feature
```
each time we build a new Angular app, the static assets have cache control embedded into file names as hashes, however index.html is always the same. That causes the app trying to load old files that no longer exist on server (referenced from the cached index.html)
Issue Number: ACA-1558
disable caching for "index.html" file so that once new build is released the app correctly updates …
=> [ACA-1558] cache busting for index.html

Dockerfile
```
```
```
[ ] Bugfix
[x] Feature
```
- Automatically generate licenses and disclaimer upon image build
- Regenerate licenses only when package.json content changes
The files should be accessible via the web interface:
* <app-url>/licenses/licenses.txt
* <app-url>/licenses/disclaimer.txt
```
[ ] Yes
[x] No
```
=> [ACA-2168] auto-generate licenses for docker image

docs/extending/application-actions.md, docs/extending/rules.md, src/app/components/preview/preview.component.spec.ts, src/app/components/preview/preview.component.ts, src/app/extensions/core.extensions.module.ts, src/app/services/content-api.service.ts, src/app/services/content-management.service.spec.ts, src/app/services/content-management.service.ts, src/app/store/actions/node.actions.ts, src/app/store/effects/node.effects.spec.ts, src/app/store/effects/node.effects.ts, src/app/store/effects/upload.effects.ts, src/assets/app.extensions.json
```
```
```
[x] Bugfix
[ ] Feature
```
Preconditions
* any file is created
* file is locked for Edit Offline
Steps to reproduce
* Select the locked file and click on More actions -> Upload new version
* Select a file and press Upload
* After the upload is complete, observe the file
Expected result: New version is uploaded and file is unlocked
Actual result: File is not unlocked
Issue Number: ACA-2193
The file should be unlocked …
=> [ACA-2193] Lock node - unlock after new version is uploaded

src/app/components/node-version/node-version-form.component.spec.ts, src/app/components/node-version/node-version-form.component.ts, src/assets/i18n/en.json
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number:
https://issues.alfresco.com/jira/browse/ACA-2198
https://issues.alfresco.com/jira/browse/ACA-2206
align version form design with XD
```
[ ] Yes
[x] No
```
=> [ACA-2198 ACA-2206]  Node version - align dialog with XD

src/app/components/layout/app-layout/app-layout.component.html, src/app/components/layout/app-layout/app-layout.component.spec.ts, src/app/components/layout/app-layout/app-layout.component.ts, src/app/ui/overrides/adf-sidenav-layout.theme.scss
```
```
```
[x] Bugfix
[x] Feature
```
Issue Number: #928 
- Allow using `swipe left` gesture on small screens to close the application menu.
- Adopt the size of the menu to small devices, always leave a space for click out
**iPhone 5 layout**
**iPhone 6 layout**
```
[ ] Yes
[x] No
```
=> [ACA-2208] Hide app menu on swipe

docs/extending/rules.md, src/app/extensions/core.extensions.module.ts, src/app/extensions/evaluators/app.evaluators.spec.ts, src/app/extensions/evaluators/app.evaluators.ts, src/assets/app.extensions.json
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2199](https://issues.alfresco.com/jira/browse/ACA-2199)
- add unit tests for evaluators
- dedicated evaluator for "Upload Version" action (previously used "Versions" one)
```
[ ] Yes
[x] No
```
Upload Version action on an unlocked file should be available only for users with "Update" permissions
=> [ACA-2199] Upload Version - granular permission  

src/app/guards/auth.guard.spec.ts, src/app/guards/auth.guard.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: #913
Skipt the Basic/oAuth checks if `withCredentials` (Kerberos) is enabled in `app.config.json`
```
[ ] Yes
[x] No
```
To enable the mode, one has to set the following setting in the `app.config.json` file:
```json
{
"auth": {
"withCredentials": true
}
}
```
=> [ACA-2211] auth guard: add support for withCredentials

src/assets/app.extensions.json
```
```
```
[x] Bugfix
[ ] Feature
```
for a folder in More actions there is a separator between Favorite and Edit actions.
Issue Number: ACA-2177
removed the separator between Favorite and Edit folder actions
```
[ ] Yes
[x] No
```
=> [ACA-2177] remove separator between Favorite and Edit folder

src/app/directives/lock-node.directive.spec.ts, src/app/directives/lock-node.directive.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2221](https://issues.alfresco.com/jira/browse/ACA-2221)
check if selection is not null 
```
[ ] Yes
[x] No
```
=> [ACA-2221] Lock node - check selection is not null

e2e/suites/actions/download.test.ts, e2e/utilities/utils.ts, package-lock.json, package.json
```
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: automated tests
```
Issue Number: ACA-833
```
[ ] Yes
[ ] No
```
Automate tests for download folder and download multiple items, meaning download as zip
=> [ACA-833] automate tests for download as zip

docs/extending/rules.md, src/app/components/shared-link-view/shared-link-view.component.html, src/app/components/shared-link-view/shared-link-view.component.spec.ts, src/app/components/shared-link-view/shared-link-view.component.ts, src/app/components/shared-link-view/shared-link-view.module.ts, src/app/extensions/core.extensions.module.ts, src/app/extensions/evaluators/navigation.evaluators.spec.ts, src/app/extensions/evaluators/navigation.evaluators.ts, src/app/extensions/extension.service.spec.ts, src/app/extensions/extension.service.ts, src/app/store/reducers/app.reducer.ts, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: [ACA-2216](https://issues.alfresco.com/jira/browse/ACA-2216)
Shared link preview employs extension action rules 
```
[ ] Yes
[x] No
```
=> [ACA-2216] Shared link preview - use extension actions

projects/adf-office-services-ext/package.json, projects/adf-office-services-ext/src/lib/evaluators.ts, src/app/extensions/app.interface.ts, src/app/extensions/extension.service.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: [ACA-2212](https://issues.alfresco.com/jira/browse/ACA-2212)
Where SSO is configured (Alfresco Identity Service) then the **Edit in Office** action will not be shown
```
[ ] Yes
[x] No
```
=> [ACA-2212] allow "edit in office" only for basic auth

src/app/components/search/search-results/search-results.component.spec.ts, src/app/components/search/search-results/search-results.component.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: [ACA-2220](https://issues.alfresco.com/jira/browse/ACA-2220)
Provide a very simple support for search in fields:
If the search input query contains a column (`:`) symbol, passes the query to the search service as it is.
This enables the whole range of scenarios for advanced search, examples:
https://docs.alfresco.com/6.0/concepts/rm-searchsyntax-fields.html
Can also be joined …
=> [ACA-2220] simple "search in fields" support

docs/extending/application-actions.md, src/app/components/favorites/favorites.component.spec.ts, src/app/components/favorites/favorites.component.ts, src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts, src/app/components/page.component.ts, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/recent-files/recent-files.component.ts, src/app/components/shared-files/shared-files.component.spec.ts, src/app/components/shared-files/shared-files.component.ts, src/app/components/toolbar/toggle-favorite/toggle-favorite.component.ts, src/app/components/trashcan/trashcan.component.spec.ts, src/app/components/trashcan/trashcan.component.ts, src/app/directives/document-list.directive.ts, src/app/services/content-management.service.spec.ts, src/app/services/content-management.service.ts, src/app/store/actions/app.actions.ts, src/app/store/effects/app.effects.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #975
Introduce support for reloading document list via NgRx Action (`RELOAD_DOCUMENT_LIST`).
Deprecate some of the application events that existed only to reload the data.
```
[ ] Yes
[x] No
```
=> reload active doclist via NgRx actions

src/app/app.component.ts, src/app/extensions/app.interface.ts, src/app/extensions/evaluators/repository.evaluators.ts, src/app/extensions/extension.service.ts, src/app/store/actions/repository.actions.ts, src/app/store/reducers/app.reducer.ts, src/app/store/selectors/app.selectors.ts, src/app/store/states/app.state.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: #983 
- fixes #983 
- stores all repository info (discovery api) in the application state, not only Status
That solves the problem with extensions and rules that cannot access the module information to toggle certain behaviors. 
```
[ ] Yes
[x] No
```
=> support repository info with app state

build-tomcat-e2e.sh, docs/getting-started/configuration.md, src/app.config.json, src/app/app.component.spec.ts, src/app/app.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2214](https://issues.alfresco.com/jira/browse/ACA-2214)
- fixes #946
- adds correct default for the baseShareUrl
- provides full control of the url prefix (including application route)
```
[ ] Yes
[x] No
```
=> [ACA-2214] Sharing URL being constructed from ECM Host incorrectly

src/app/ui/overrides/adf-search-filter.theme.scss
```
```
```
[x] Bugfix
[ ] Feature
```
The facet-buttons from "Created Date" do not have the correct styling applied.
Issue Number:https://issues.alfresco.com/jira/browse/ACA-2242
fixes missing buttons styles issue until ADF 3.1.0 will fix it
```
[ ] Yes
[x] No
```
=> [ACA-2242] add old style back

src/app/components/search/search-input/search-input.component.ts, src/app/components/search/search-results/search-results.component.spec.ts, src/app/components/search/search-results/search-results.component.ts, src/app/store/effects/search.effects.spec.ts, src/app/store/effects/search.effects.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2240](https://issues.alfresco.com/jira/browse/ACA-2240)
replace query string  parentheses to ASCII
```
[ ] Yes
[x] No
```
=> [ACA-2240] Search - Unable to use parenthesis in search term

cspell.json, src/app/services/app.service.spec.ts, src/app/services/app.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
AppService prevents loading Repository and Profile information on application startup when Kerberos is used.
Issue Number: [ACA-2133](https://issues.alfresco.com/jira/browse/ACA-2133)
fixes #894
Correctly set `ready$` state on application start. 
Load Repository and Profile information.
```
[ ] Yes
[x] No
```
=> [ACA-2133] fix application ready event for kerberos

projects/adf-office-services-ext/src/lib/evaluators.spec.ts, projects/adf-office-services-ext/src/lib/evaluators.ts, src/app/extensions/evaluators/app.evaluators.ts, src/app/services/node-permission.service.ts, src/app/store/reducers/app.reducer.ts
```
```
```
[x] Bugfix
[ ] Feature
```
The issue fixed is that Edit in Microsoft Office action was displayed regardless of user permissions.
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2259
```
[ ] Yes
[x] No
```
=> [ACA-2259] Edit in Microsoft Office - check update permissions

src/app/app.component.ts, src/app/store/actions/app.actions.ts, src/app/store/reducers/app.reducer.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: 
[ACA-2351](https://issues.alfresco.com/jira/browse/ACA-2351)
#1067 
load user group membership and store in the application state;
that allows rules accessing group information via "context.profile.groups" property.
```
[ ] Yes
[x] No
```
=> [ACA-2351] allow rules access user group membership

src/app.config.json
- use the default value of 1
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: 
```
The temporary workaround for the [ACA-1623] issue was setting the `mincount` to 0. This way all facets were visible even if they were empty. The issue is now fixed on ADF component so this PR removes the workaround and uses the default value of 1 for `mincount`.
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1623
```
[ ] Yes
[x] No
```
=> [ACA-1623] remove mincount set to 0

.github/plint.yml, docs/extending/application-features.md, extension.schema.json, src/app/extensions/extension.service.ts, src/app/extensions/viewer.rules.ts, src/app/store/effects/viewer.effects.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: ACA-2364
allow defining custom rules to determine whether a node can be previewed or not,
can be used to restrict certain content from opening in the Viewer
```
[ ] Yes
[x] No
```
=> [ACA-2364] support 'canPreview' rule for the Viewer

src/app.config.json, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: These aspects and their properties will not be displayed.
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2472
Don't show these aspects until the ADF content-metadata has support to set individual aspects to 'editable' false. At that moment, these 2 aspects should be displayed, but set as not-editable as mentioned on [ACA-2421](https://issues.alfresco.com/jira/browse/ACA-2421) and …
=> [ACA-2472] Temporarily disable "Emailed" and "Likes" properties

docs/extending/application-actions.md, projects/aca-shared/store/src/actions/viewer.actions.ts, proxy.conf.js, src/app/components/preview/preview.component.spec.ts, src/app/components/preview/preview.component.ts
```
```
```
[ ] Bugfix
[x] Feature
```
We are overriding the deletion of the node. If the user performs **delete** operation
in the viewer menu, the viewer is not getting closed.
I have created one action to close the preview. so, we can able to dispatch the action from the extension.
```
[ ] Yes
[x] No
```
https://issues.alfresco.com/jira/browse/ACA-2471
=> [ACA-2471] - close preview action

src/app/services/content-management.service.spec.ts, src/app/services/content-management.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-1930](https://issues.alfresco.com/jira/browse/ACA-1930)
```
[ ] Yes
[x] No
```
=> [ACA-1930] Search results list does not refresh after renaming a folder

projects/adf-office-services-ext/assets/aos.plugin.json
Sync the AOS version displayed on the About page with the version from AOS package.json
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2715
=> [ACA-2715] Fix display version of AOS on About page

docker/entrypoint.sh
Issue Number: ACA-2713
Use `BASE_PATH` variable name for Docker image
=> [ACA-2713] use standard base_path variable

karma.conf.js, package-lock.json, package.json, protractor.conf.js
Use fixed Chrome version (76) via puppeteer. 
Allows having multiple PRs with different Chrome versions to see if the app can be upgraded safely. 
Does not rely on CI/CD
=> use fixed chrome version via puppeteer

src/app/components/search/search-input.module.ts, src/app/components/search/search-input/search-input.component.html
"The element is not accessible by keyboard alone.
Refer to
1. search filter options ""Files, Folders, Libraries"" are not operable with a keyboard alone. These elements are displayed when search textbox receives focus.
2. Profile icon (A) provided next to the administrator text."
Solution: Trap the tab in the cdk search overlay.
Issue Number: ACA-2505
Kudos to @pionnegru for helping with that :)
=> [ACA-2505] Header - Action is not accessible by keyboard alone

package.json
Allow a specific chrome version for webdriver with 'VERSION_CHROME="--versions.chrome=1.2.3" npm run wd:update'. Defaults back to the latest chrome version.
Can than be used like for Bamboo which requires a specific chrome version.
Issue Number:[ACA-2779]
=> [ACA-2779] Configurable Chrome Protractor version

docker/entrypoint.sh
* href should be override href="/" and href="./" as that is our prod build. As well ADW uses ACS_URL
Issue Number: ACA-2800
=> [ACA-2800] Entry.sh overrides wrong BASE_PATH

package-lock.json, package.json
upgrade puppeteer version in order to use chrome v78
upgrade webdriver-manager to 12.1.7, compatible with chrome v78
=> upgrade webdriver-manager and puppeteer

src/app/components/header/header.component.html, src/app/components/header/header.component.ts, src/app/components/layout/app-layout/app-layout.component.html
Issue Number: ACA-2782
Accessiblity improvement with showing on the sidenav toggle button if the sidnav is expanded or not
=> [ACA-2782] Header - sidenav menu button expanded/collapsed state not exposed via ARIA

e2e/resources/extensibility-configs/context-submenus-ext.json, src/app/components/common/toggle-shared/toggle-shared.component.html, src/app/components/common/toggle-shared/toggle-shared.component.ts, src/app/services/content-management.service.ts, src/assets/app.extensions.json
Issue Number: [ACA-2621](https://issues.alfresco.com/jira/browse/ACA-2621)
use custom component action to ensure elements are not removed from DOM when different states must render. this way, focused element reference will not get lost
=> [ACA-2621] Shared link - when dialog is closed focus is not returned to trigger

e2e/components/menu/menu.ts, e2e/suites/viewer/viewer-actions.test.ts, src/app/components/page.component.spec.ts, src/app/components/page.component.ts, src/app/components/viewer/viewer.component.ts
Issue Number: 
[ACA-2850](https://issues.alfresco.com/jira/browse/ACA-2850)
[ACA-2849](https://issues.alfresco.com/jira/browse/ACA-2849)
- after upload a  new version get new data for viewer to display
- prevent feature document list upload event triggering  reload when in outlet viewer since it already does the same actions
=> [ACA-2850][ACA-2849] Viewer - document properties not refreshed after changes or uploading new version

e2e/suites/info-drawer/comments.test.ts
reorganize the Comments tests so that the comment is created closer to the moment when comment created date is checked, in order to avoid this flaky fail:
```Expected 'a few seconds ago' to be 'a minute ago', 'Incorrect comment created time'.```
Issue Number: ACA-2863
extracted the tests checking the comment created date in a separate suite, and moved the call to create the comment inside this new suite
=> [ACA-2863] reorganize the Comments tests

docs/extending/application-actions.md, projects/aca-shared/store/src/actions/template.actions.ts, src/app/dialogs/node-templates/create-from-template-dialog.service.ts, src/app/dialogs/node-templates/create-from-template.dialog.spec.ts, src/app/dialogs/node-templates/create-from-template.dialog.ts, src/app/store/effects/template.effects.spec.ts, src/app/store/effects/template.effects.ts, src/assets/app.extensions.json
Issue Number: [ACA-2869](https://issues.alfresco.com/jira/browse/ACA-2869)
Created 2 template effects:
- FileFromTemplate - manages dialogs
- CreateFileFromTemplate -  create node from template source
Created a dialog service which holds a Subject to be called once node is successful created to close the dialog that subscribes to it. This will keep the dialog open in case of error
=> [ACA-2869] Create File from template - keep the dialog open if creation fails due to the usage of a duplicate file name

package-lock.json, package.json
Issue Number: [ACA-2912](https://issues.alfresco.com/jira/browse/ACA-2912)
Align pdfjs version with ADF
=> [ACA-2912] [MNT] [Security] CVE-2018-5158 - XSS vulnerability in pdfjs

src/app/components/create-menu/create-menu.component.scss
Issue Number: ACA-2124
- Rise `font-size` from **12.7px to 18.7px** and `font-weight` from **normal to bold** to need only a 3:1 contrast ratio for colors and not a 4.5:1 ratio for AA accessibility level compliance.
- New color chose from `alfresco-accent-orange` palette to respect the 3:1 contrast ratio.
PS : Sidenav colors will be updated and harmonized in next PR (cf ACA-2125)
=> [ACA-2124] New bg-color and font style for "New" button

projects/aca-shared/src/lib/components/page-layout/page-layout.component.scss, src/app/components/sidenav/sidenav.component.theme.scss, src/app/ui/custom-theme.scss, src/app/ui/theme.scss
Issue Number: ACA-2125
- Rise `font-size` from **14px to 18.7px** and `font-weight` from **normal to bold** so we need only a 3:1 contrast ratio for colors and not a 4.5:1 ratio for AA accessibility level compliance for sidenav buttons.
- New color chose from `alfresco-accent-orange` palette and update the default background-color from `#fafafa` to `#fcfcfc` to respect the 3:1 contrast ratio.
- Rise `font-size` from **14px to 18.7px** for  the`page-layout-header` to harmonize with sidenav.
=> [ACA-2125] Update sidenav colors and font-size

src/app/components/search/search-input/search-input.component.theme.scss, src/app/components/search/search-results-row/search-results-row.component.scss, src/app/ui/custom-theme.scss
> - [ ] Bugfix
Styling
No change in color when a row is selected and missing some contrast for AA accessibility in …
=> [ACA-2604] Search result/input color update

src/app/ui/custom-theme.scss
> - [ ] Bugfix
The background color of data table row when selected or hovered is slightly too dark: only …
=> [ACA-2970] Change hover and select data row background color

src/app/components/search/search-results-row/search-results-row.component.scss
> - [ ] Bugfix
When a data table cell is selected, the color of its background and links changes and the …
=> [ACA-2604] Fix color update on datable row

src/app/components/create-menu/create-menu.component.scss
> - [ ] Bugfix
With the theme update, the create menu component has its colors changed and it wasn't: Every …
=> [ACA-2979] Change create menu item colors

src/app/components/search/search-input/search-input.component.theme.scss
> - [ ] Bugfix
The search input background has 0.54 of opacity and when the width of the window is small …
=> [ACA-2980] Update search input background-color

src/app/services/node-template.service.spec.ts, src/app/services/node-template.service.ts, src/app/store/effects/template.effects.spec.ts, src/app/store/effects/template.effects.ts
> - [x] Bugfix
[ACA-3043](https://issues.alfresco.com/jira/browse/ACA-3043)
**Does …
=> [ACA-3043] Create From Template - relativePath not working when ACS installation language is different

src/app/components/dl-custom-components/name-column/name-column.component.scss, src/app/ui/custom-theme.scss
> - [ ] Bugfix
The hover color of the aca-custom-name-column is too light for AA accessibility.
**What is the …
=> [ACA-2496] Change hover color on custom name color

src/app/components/create-menu/create-menu.component.scss
> - [ ] Bugfix
Texts in create menu lack contrast ratio for AA accessibility requirements. …
=> [ACA-2542] Change create menu colors

src/app/components/dl-custom-components/name-column/name-column.component.scss
> - [ ] Bugfix
The new color isn't attributed to the right element in the column. This doesn't create any …
=> [ACA-2496] Refactor of color change for colum name

src/app/ui/custom-theme.scss, src/app/ui/snackbar.scss
> - [x] Bugfix
[ACA-2994](https://issues.alfresco.com/jira/browse/ACA-2994)
**Does …
=> [ACA-2994] Snackbar- notifications are displayed with wrong colours

docs/getting-started/configuration.md, projects/aca-shared/store/src/selectors/app.selectors.ts, projects/aca-shared/store/src/states/app.state.ts, src/app.config.json, src/app/app.component.ts, src/app/components/header/header.component.scss, src/app/components/header/header.component.ts, src/app/store/initial-state.ts, src/app/ui/custom-theme.scss
> - [x] Bugfix
Allow customizing the background image path via `app.config.json`
Fixes …
=> [ACA-3249] customisable header image url

package-lock.json, package.json, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/extensions/extension.service.ts, src/app/mock/extension-routes.mock.ts, src/app/types.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3182
Right now every route that we define in the …
=> [ACA-3182] Add a way to define an extension route as child of a route

docs/extending/application-features.md, docs/ja/extending/application-features.md, e2e/resources/extensibility-configs/context-submenus-ext.json, e2e/resources/extensibility-configs/document-presets-ext.json, e2e/resources/extensibility-configs/extensions-default.json, e2e/resources/extensibility-configs/header-ext.json, e2e/resources/extensibility-configs/info-drawer-ext.json, e2e/resources/extensibility-configs/metadata-ext.json, e2e/resources/extensibility-configs/viewer-ext.json, extension.schema.json, projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.html, projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.spec.ts, projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts, projects/aca-shared/src/lib/components/info-drawer/shared-info-drawer.module.ts, projects/aca-shared/src/lib/services/app.extension.service.ts, src/assets/app.extensions.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3257
Able to create/extend …
=> [ACA-3257] Add actions extension capability to info drawer

projects/aca-shared/store/src/actions/library.actions.ts, src/app/app.routes.ts, src/app/components/favorite-libraries/favorite-libraries.component.spec.ts, src/app/components/favorite-libraries/favorite-libraries.component.ts, src/app/store/effects/library.effects.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-1992
Until now, when a user …
=> [ACA-1992] Keep favorite libraries navigation under same path

projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.html
> - [ x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x ] Bugfix
Currently each item in the menu is announcing as a button. 
Each item …
=> [ACA-2582]- fix: proper menuitem aria for screen reader users

projects/adf-office-services-ext/src/lib/utils.ts
> - [ ] Bugfix
XLAM files are cannot be edited online 
Similar to PPAM files (for MS Powerpoint), those are Macro-Enabled Add-ins for MS …
=> Edit Online for XLAM files

src/app/components/files/files.component.ts
> - [x] Bugfix
ERROR in apps/content-ce/src/app/components/files/files.component.ts:39:30 - error TS2307: Cannot find …
=> Fix FilterSearch import path

projects/aca-shared/src/lib/components/locked-by/locked-by.component.scss, projects/aca-shared/src/lib/components/locked-by/locked-by.component.ts, projects/aca-shared/src/lib/components/locked-by/locked-by.module.ts, src/app/components/dl-custom-components/name-column/name-column.component.html, src/app/components/dl-custom-components/name-column/name-column.component.ts, src/app/components/search/search-results-row/search-results-row.component.html, src/app/components/search/search-results-row/search-results-row.component.ts, src/app/components/search/search-results.module.ts, src/assets/i18n/en.json
> - [x] Bugfix
- display "locked by" in the search results
- enable the e2e for locked …
=> [ACA-2314] display "locked by" in search results

src/app/components/files/files.component.html, src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts, src/app/testing/translation.service.ts, src/assets/i18n/en.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-4045
Show Document List …
=> [ACA-4045] Show Document List header if filter header is active

projects/aca-shared/rules/src/app.rules.ts, projects/aca-shared/store/src/actions/library.actions.ts, src/app/app.component.ts, src/app/components/toolbar/toggle-join-library/toggle-join-library-button.component.ts, src/app/components/toolbar/toggle-join-library/toggle-join-library.component.spec.ts, src/app/directives/library-membership.directive.spec.ts, src/app/directives/library-membership.directive.ts, src/app/store/effects/library.effects.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-3729
At the moment admin …
=> [ACA-3729] Join library action for Admin Users

package-lock.json, package.json, src/app/components/files/files.component.ts
> - [X] Bugfix
Navigating through breadcrumb won't reset pagination for DL
Navigating …
=> [ACA-4168] - reset pagination on breadcrumb navigation

.travis.yml
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-1116
A new condition to the …
=> [ACS-1116] E2e tests to not run on Master

src/app/directives/document-list.directive.spec.ts, src/app/directives/document-list.directive.ts
> - [x] Bugfix
[ACA-4224](https://alfresco.atlassian.net/browse/ACA-4224)
**Does this …
=> [ACA-4224] DocumentList - clear filterers action renders previous selection toolbar actions

src/app/services/content-management.service.spec.ts, src/app/services/content-management.service.ts
> - [x] Bugfix
`deletedSharedLink` would always return false causing the check on it to always fail, the …
=> [ACA-4320] Correctly trigger linksUnshared event after unsharing a file

src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/MNT-22241
**Does this PR …
=> [ACA-4374] FE - [ADW] Navigate to Smart Folder subfolders throws "This item no longer exists or you don't have permission to view it."

src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACA-4383
When having a pagination …
=> [ACA-4383] - Fix pagination when performing navigation

projects/aca-shared/store/src/actions/upload.actions.ts, src/app/components/layout/app-layout/app-layout.component.scss, src/app/components/viewer/viewer.component.html, src/app/components/viewer/viewer.component.ts, src/app/store/effects/upload.effects.spec.ts, src/app/store/effects/upload.effects.ts, src/assets/i18n/en.json
> - [ ] Bugfix
https://github.com/Alfresco/alfresco-ng2-components/pull/6984 …
=> Revert changes from dev-durse-ADF-5378-integration

src/app/components/files/files.component.html, src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4384
We were not showing an error template in case of BE 500 …
=> [ACA-4384] [ADW] Empty template or error template should be displayed in case error occurred when clicking a folder

projects/aca-shared/rules/src/app.rules.ts, projects/aca-shared/rules/src/repository.rules.ts
> - [X] Bugfix
Edit aspect action fails with ACS versions below 7
Edit Aspect action …
=> [ACA-4445] - added condition to check major version 7

src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts
> - [ ] Bugfix
folder-link is handled as a regular folder
clicking on a folder-link …
=> [ACA-376] navigate inside original folder when clicking on a folder-link

src/app/components/header/header.component.spec.ts, src/app/services/node-actions.service.spec.ts
> - [ ] Bugfix
remove the deprecated `async` (removed in later Angular versions) from …
=> [ADF-5423] remove deprecated async from unit tests

projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.spec.ts, projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts, projects/aca-shared/src/lib/components/tool-bar/toolbar-button/toolbar-button.component.html, projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.html, projects/aca-shared/src/lib/services/app.extension.service.spec.ts, projects/aca-shared/src/lib/services/app.extension.service.ts, src/app/components/context-menu/context-menu.component.spec.ts, src/app/components/context-menu/context-menu.component.ts, src/app/components/create-menu/create-menu.component.spec.ts, src/app/components/create-menu/create-menu.component.ts, src/app/components/header/header.component.spec.ts, src/app/components/header/header.component.ts, src/app/components/page.component.ts, src/app/components/preview/preview.component.ts, src/app/components/shared-link-view/shared-link-view.component.spec.ts, src/app/components/shared-link-view/shared-link-view.component.ts, src/app/components/viewer/viewer.component.ts
> - [X] Bugfix
The rules for the extensions are not evaluated once the context changes. …
=> [AAE-5874] Re-evaluate extension rules when context changes

src/app/ui/custom-theme.scss
Changed min-width value of fileSize column to 110px in order to make more letters visible if sort and filter icons are present
> - [x] Bugfix
**What is the current behaviour?** (You can also …
=> [ACA-4203] The width of the "Size" column is too small and the text gets truncated

.travis.yml, scripts/travis/deploy/publish.sh
* Publish images to dockerhub when pushing to master in addition to the tag
> - [*] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [n/a] Docs have been added / updated (for bug fixes / features)
> - [*] Bugfix
Images are just pushed …
=> ACA-4526 Alfresco Content Application Docker Images are not available in Docker Hub from 2.3.0

src/app/components/page.component.spec.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4532
The `Info Drawer state` tests overrides/spy on …
=> [ACA-4532] Flaky ACA unit test

app/src/app/components/create-menu/create-menu.component.scss, app/src/app/components/main-action/main-action.component.scss, app/src/app/ui/custom-theme-palettes.scss, app/src/app/ui/custom-theme.scss, app/src/app/ui/dynamic-theme/custom-palette-creator.scss, app/src/app/ui/dynamic-theme/custom-theme-palettes.scss.tpl, app/src/app/ui/dynamic-theme/index.scss
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-6826
BE is going to be able …
=> [AAE-6826] Create SCSS template

docs/tutorials/how-to-create-your-first-extension.md
> - [ ] Bugfix
```
ERROR: projects/my-extension/src/lib/my-extension.module.ts:16:53 - error TS2304: Cannot find name …
```
=> Fix first extension instruction

app/src/app/services/content-management.service.ts, app/src/app/store/effects/node.effects.ts, projects/aca-folder-rules/assets/i18n/en.json, projects/aca-folder-rules/src/lib/model/rule-composite-condition.model.ts, projects/aca-folder-rules/src/lib/model/rule-simple-condition.model.ts, projects/aca-folder-rules/src/lib/model/rule.model.ts, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.html, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.scss, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.spec.ts, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.scss, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.spec.ts, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts, projects/aca-folder-rules/src/public-api.ts, projects/aca-shared/store/src/actions/node.actions.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-3255
New dialog for creating …
=> [ACS-3255] Add basic dialog for create / update rule

app/src/app.config.json.tpl, app/src/app/app.routes.ts, app/src/app/services/content-management.service.ts, app/src/app/store/effects/node.effects.ts, app/src/assets/app.extensions.json, e2e/suites/actions-available/files-folders/test-data.ts, projects/aca-folder-rules/assets/i18n/en.json, projects/aca-folder-rules/src/lib/folder-rules.module.ts, projects/aca-folder-rules/src/lib/folder-rules.rules.ts, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts, projects/aca-folder-rules/src/public-api.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-3379
- Very basic skeleton …
=> [ACA-3379] Routing & skeleton for manage rules screen

.travis.yml, projects/aca-folder-rules/karma.conf.js, projects/aca-folder-rules/src/lib/folder-rules.rules.spec.ts
> - [x] Bugfix
Some of the unit tests in the `aca-folder-rules` project hadn't been changed for …
=> [ACS-3379] Fix unit tests for the visibility rules of the folder rules

projects/aca-folder-rules/assets/i18n/en.json, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.spec.ts, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts, projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts, projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
> - [ ] Bugfix
There is currently no way for a user to delete a rule set for a folder. …
=> [ACS-3219] Delete Rule

app/src/app/ui/application.scss, app/src/styles.scss
> - [x] Bugfix
[AAE-10512](https://alfresco.atlassian.net/browse/AAE-10512)
The reason for the bug is a fix …
=> [AAE-10512] Several icons cut off due to a fix introduced in Angular 14

angular.json, app/src/styles.scss
> - [ ] Bugfix
- remove the need for breaking change for the scss path
- remove the …
=> cleanup unused theming

projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html, projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.html, projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.scss, projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.spec.ts, projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.ts, projects/aca-folder-rules/src/lib/rules-list/rules-list.ui-component.html, projects/aca-folder-rules/src/lib/rules-list/rules-list.ui-component.spec.ts, projects/aca-folder-rules/src/lib/rules-list/rules-list.ui-component.ts, projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts, projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
> - [ ] Bugfix
There is currently no option to enable/disable the rule.
For each rule, …
=> [ACS-3512] - ACA enable/disable rule from listing

projects/aca-shared/src/lib/directives/contextmenu/contextmenu.directive.spec.ts, projects/aca-shared/src/lib/directives/contextmenu/contextmenu.directive.ts
> - [X] Bugfix
When we right click to drag&drop  empty area  context menu is rendered …
=> [AAE-10253] It shouldn't be possible to right click in a drag&drop empty area

README.md, angular.json, app/tsconfig.app.adf.json, tsconfig.adf.json
> - [ ] Bugfix
add the configuration to enable running ACA with local ADF builds …
=> [ACA-4612] ACA: integrating with the local ADF source code

projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
> - [X] Bugfix
Creating a rule without a conditions returns `simpleConditions: [null] `. It results to an error and …
=> [ACS-3586] ACA/Folder Rules: Adding a rule to a Folder seems to break the Folder Rules UI

projects/aca-folder-rules/assets/i18n/en.json, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts, projects/aca-folder-rules/src/lib/model/aspect.model.ts, projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html, projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts, projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
> - [ ] Bugfix
Currently there is no possibility to get list of aspects.
`loadAspects` …
=> [ACS-3575] Update FolderRulesService to provide a list of available aspects

projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.html, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts, projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts, projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
> - [ ] Bugfix
Currently there is no possibility to create rules and display errors if any occurs. …
=> [ACS-3596] Create / Update rule dialog - display errors

app/src/app/components/toolbar/toggle-join-library/toggle-join-library-menu.component.ts
…aries - can't join to libraries issue resolved
While logging in using hruser credentials and …
=> [ACS-3315] Alfresco Administrators - private and moderate libraries-can't join to libraries issue resolved

projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-3721
The endpoints should use …
=> [ACS-3721] Change folder rules endpoints to private

projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts, projects/aca-folder-rules/src/lib/mock/actions.mock.ts, projects/aca-folder-rules/src/lib/mock/aspects.mock.ts, projects/aca-folder-rules/src/lib/model/aspect.model.ts, projects/aca-folder-rules/src/lib/rule-details/actions/rule-action-list.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/actions/rule-action-list.ui-component.ts, projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.spec.ts, projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.ts, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.html, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts, projects/aca-folder-rules/src/lib/services/actions.service.spec.ts, projects/aca-folder-rules/src/lib/services/actions.service.ts, projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts, projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
> - [ ] Bugfix
Currently there is a blank field for add/remove aspect actions 
Now …
=> [ACS-3576] Map aspect actions with the aspect picker dropdown

projects/aca-folder-rules/src/lib/rule-details/conditions/rule-condition-comparators.ts
> - [X] Bugfix
When creating or updating rule and adding condition for Size ‘Greater than' (or any other multi-word …
=> [ACS-3823] ACA: Folder rule conditions - wrong values passed as comparators

projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-3872
The dropdown box is …
=> [ACS-3872] Disable boolean mode dropdown due to lack of OR in ACS

projects/aca-folder-rules/src/lib/model/rule-action.model.ts, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.html, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.spec.ts, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-3886
The button is no longer …
=> [ACS-3886] Fix edit button being disabled when opening edit rule dialog initially

projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.ts, projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.ts
> - [x] Bugfix
Context menu items can't be accessed via keyboard.
Context menu items …
=> [ACS-3700] Pass mat menu items from external components to mat menu

projects/aca-folder-rules/assets/i18n/en.json, projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.html
> - [ ] Bugfix
As @KikoUK mentioned - "although it might seem logical what the last input field is for, users might …
=> [ACA-4624] - Add placeholder for input field in rules conditions

.husky/pre-commit, .lintstagedrc.json, package.json
> - [x] Bugfix
Pre-commit hook is not working. https://alfresco.atlassian.net/browse/ACS-4014 …
=> [ACS-4014] Fix pre-commit hook for ACA

cspell.json, projects/aca-folder-rules/assets/i18n/en.json, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts, projects/aca-folder-rules/src/lib/mock/actions.mock.ts, projects/aca-folder-rules/src/lib/rule-details/actions/rule-action-list.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/actions/rule-action-list.ui-component.ts, projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.spec.ts, projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.ts, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.html, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
> - [ ] Bugfix
Currently for action parameters of type "d:noderef" there is text input, where user should manually …
=> [ACS-3860] Folder rules - Node picker for action parameters of type "d:noderef"

app/src/app/content-plugin/services/content-management.service.ts, app/src/app/content-plugin/services/node-template.service.spec.ts, app/src/app/content-plugin/services/node-template.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-3758
After closing dialogs …
=> [ACS-3758] 880526 modal is closed focus is not returned to trigger in the create new menu

projects/aca-folder-rules/assets/i18n/en.json, projects/aca-folder-rules/src/lib/folder-rules.module.ts, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.spec.ts, projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts, projects/aca-folder-rules/src/lib/rule-list/rule-list-grouping/rule-list-grouping.ui-component.html, projects/aca-folder-rules/src/lib/rule-list/rule-list-grouping/rule-list-grouping.ui-component.spec.ts, projects/aca-folder-rules/src/lib/rule-list/rule-list-grouping/rule-list-grouping.ui-component.ts, projects/aca-folder-rules/src/lib/rule-list/rule-list-item/rule-list-item.ui-component.html, projects/aca-folder-rules/src/lib/rule-list/rule-list-item/rule-list-item.ui-component.ts, projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.html, projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.scss, projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.spec.ts, projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.ts, projects/aca-folder-rules/src/lib/rule-set-picker/rule-set-picker.smart-component.html, projects/aca-folder-rules/src/lib/rule-set-picker/rule-set-picker.smart-component.scss, projects/aca-folder-rules/src/lib/rule-set-picker/rule-set-picker.smart-component.ts, projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-3513
https://alfresco.atlassian.net/browse/ACS-3515
**What …
=> [ACS-3513] [ACS-3515] Create, edit and delete rule set link

projects/aca-folder-rules/assets/i18n/en.json, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts, projects/aca-folder-rules/src/lib/mock/rules.mock.ts, projects/aca-folder-rules/src/lib/model/rule.model.ts, projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.ts, projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts, projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
> - [ ] Bugfix
Currently in ACA, the user does not have the ability to choose whether a folder should inherit folder …
=> [ACS-3895] ACA - Folder Rules: inherit rule sets toggle

projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.spec.ts, projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4630
New rule is selected …
=> [ACS-4630] Fix no different rule is selected when rule is deleted

projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.spec.ts, projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACA-4627
GET Rules request for …
=> [ACA-4627] Folder Rules - clicking on Manage Rules button does not fire the correct requests to the backend for inherited rules

projects/aca-folder-rules/src/lib/mock/actions.mock.ts, projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.scss, projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.spec.ts, projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.ts, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4632
https://alfresco.atlassian.net/browse/ACA-4633
**What …
=> [ACA-4632] [ACA-4633] Fix error script dropdown not having any options + hide dropdown when isAsynchronous unchecked

projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-4091
The parameters get …
=> [ACS-4091] Folder rules: "Add simple workflow" action clears out parameters when trying to set destination folder

projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts, projects/aca-folder-rules/src/lib/mock/rule-sets.mock.ts
> - [X] Bugfix
In case if parent folder have non-inheritable rule, and child folder has no own or linked rules - …
=> [ACS-4146] Folder Rules bug fix: An empty list for a child folder is displayed instead of an empty content template

projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss, projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts, projects/aca-folder-rules/src/lib/rule-list/rule-list-item/rule-list-item.ui-component.scss
> - [ ] Bugfix
> - [X] Other... Please describe: style fixe
Edit/Delete buttons are invisible due to been pushed to the side, same with toggle button. …
=> [ACA-4634] Folder Rules style fix: Edit and Delete Rule buttons disappear if rules have long description or name

app/src/app/content-plugin/store/effects/upload.effects.spec.ts, app/src/app/content-plugin/store/effects/upload.effects.ts, app/src/app/content-plugin/ui/overrides/ay11.scss
> - [x] Bugfix
After closing browser's modal for file input, focus was not returning to New button. 
**What is the …
=> [ACS-3758] 880526 fix for modals which close was not returning to new button

app/src/app/content-plugin/components/common/toggle-shared/toggle-shared.component.html, app/src/app/content-plugin/components/common/toggle-shared/toggle-shared.component.ts, app/src/app/content-plugin/components/context-menu/context-menu.component.html, app/src/app/content-plugin/components/context-menu/context-menu.component.spec.ts, app/src/app/content-plugin/components/context-menu/context-menu.component.ts, app/src/app/content-plugin/services/content-management.service.spec.ts, app/src/app/content-plugin/services/content-management.service.ts, app/src/app/content-plugin/services/node-actions.service.spec.ts, app/src/app/content-plugin/services/node-actions.service.ts, app/src/app/content-plugin/store/effects/download.effects.spec.ts, app/src/app/content-plugin/store/effects/download.effects.ts, app/src/app/content-plugin/store/effects/library.effects.ts, app/src/app/content-plugin/store/effects/node.effects.spec.ts, app/src/app/content-plugin/store/effects/node.effects.ts, app/src/app/content-plugin/store/effects/upload.effects.ts, app/src/assets/app.extensions.json, package-lock.json, package.json, projects/aca-shared/src/lib/components/tool-bar/toolbar-button/toolbar-button.component.ts, projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.ts, projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.html, projects/aca-shared/src/lib/models/modal-configuration.ts, projects/aca-shared/src/lib/services/app.extension.service.ts, projects/aca-shared/src/public-api.ts, projects/aca-shared/store/src/actions/library.actions.ts, projects/aca-shared/store/src/actions/node.actions.ts, projects/aca-shared/store/src/actions/upload.actions.ts
> - [x] Bugfix
Modals which were opened from personal files/libraries list or toolbar or more menu, after closing, …
=> [ACS-3757] returning focus to element from which they were opened

app/src/app/content-plugin/components/common/toggle-shared/toggle-shared.component.ts, app/src/app/content-plugin/store/effects/download.effects.spec.ts, app/src/app/content-plugin/store/effects/download.effects.ts, app/src/app/content-plugin/store/effects/library.effects.ts, app/src/app/content-plugin/store/effects/node.effects.ts, app/src/app/content-plugin/store/effects/upload.effects.ts, projects/aca-shared/src/lib/services/app.extension.service.spec.ts, projects/aca-shared/src/lib/services/app.extension.service.ts, projects/aca-shared/store/src/actions/library.actions.ts, projects/aca-shared/store/src/actions/node.actions.ts, projects/aca-shared/store/src/actions/upload.actions.ts
> - [x] Bugfix
Missing configuration field. 
Added configuration field when running …
=> [AAE-11830] Changes required to address comment in APPS

.travis.yml, angular.json, app/tsconfig.spec.adf.json, e2e/tsconfig.e2e.adf.json, projects/aca-folder-rules/tsconfig.spec.adf.json, projects/aca-settings/tsconfig.spec.adf.json, projects/aca-shared/tsconfig.spec.adf.json, projects/adf-office-services-ext/tsconfig.spec.adf.json, protractor.conf.js, scripts/ci/job_hooks/before_install.sh, scripts/ci/jobs/affected-project-with.sh, scripts/ci/partials/_adf-linking.sh
> - [ ] Bugfix
ADF linking in ACA is running only with build. https://alfresco.atlassian.net/browse/ACA-4625
**What …
=> [ACA-4625] Add ADF linking to unit tests and e2es

e2e/protractor.excludes.json, e2e/suites/actions/share/share-file.test.ts, e2e/suites/actions/share/unshare-file-search-results.test.ts, projects/aca-testing-shared/src/components/toolbar/toolbar.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4645
Running the e2e tests on …
=> [ACA-4645] Fix for shareActions e2es

projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.spec.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4633
Label should always be …
=> [ACA-4633] Fix error script dropdown sometimes not having a label

angular.json, package.json, projects/aca-content/.eslintrc.json
> - [x] Bugfix
add the missing Lint configuration for the `aca-content` that was lost …
=> add missing linting for aca-content

app/src/app.config.json.tpl, e2e/protractor.excludes.json
> - [x] Bugfix
time picker is not available
fix the regression: datetime mode for …
=> [ACS-4417] fix the shared link datetime picker defaults

scripts/ci/npm/publish-libs.sh
=> [AAE-11496] Publish npm package using https

angular.json, app/src/app/extensions.module.ts, package.json, projects/aca-about/ng-package.json, projects/aca-about/package.json, projects/aca-about/src/lib/about.component.html, projects/aca-about/src/lib/about.component.ts, projects/aca-about/src/lib/aca-about.module.ts, projects/aca-about/src/lib/package-json.token.ts, projects/aca-about/src/public-api.ts, projects/aca-about/tsconfig.lib.prod.json, projects/aca-settings/ng-package.json, projects/aca-settings/package.json, projects/aca-settings/tsconfig.lib.prod.json, scripts/ci/npm/publish-libs.sh
=> [AAE-11496] Build and publish aca-about and aca-settings

projects/aca-about/package.json, projects/aca-settings/package.json
First time published scoped packages are private by default, need to set access to public:
https://docs.npmjs.com/cli/v6/configuring-npm/package-json#publishconfig
> - [ ] Bugfix
**What is the …
=> [AAE-11496] Publish aca-about and aca-settings with public access

.travis.yml, scripts/travis/update/aca-same-commit-verify.js, scripts/travis/update/pr-creator.js, scripts/travis/update/update-project.sh
> - [ ] Bugfix
ACA libraries published to NPM are not updated in monorepo. …
=> [ACS-4530] Add ACA libraries upstream PR to monorepo

e2e/tsconfig.e2e.adf.json, e2e/tsconfig.e2e.json, tsconfig.adf.json, tsconfig.json
> - [x] Bugfix
fix TS config error related to missing lib …
=> fix project mapping for testing shared lib

.github/workflows/aca-upstream.yml, .travis.yml, scripts/travis/update/update-project.sh
> - [ ] Bugfix
There is no way to trigger ACA upstream manually. ACA upstream is not created for applications repo. …
=> [ACS-4632] Add GH workflow to trigger ACA upstream

projects/aca-content/src/lib/ui/overrides/ay11.scss, projects/aca-content/src/lib/ui/variables/variables.scss
Updated CSS rules for DateTimePicker  to show which date is currently focused on when navigating using the keyboard.
> - [x] Bugfix
**What is the current behaviour?** (You can also link to an …
=> [ACS-4259] Updated CSS rules for DateTimePicker

e2e/suites/application/page-titles.test.ts
> - [x] Bugfix
C280415 fails due to pagination errors. https://alfresco.atlassian.net/browse/ACS-4741
**What is the …
=> [ACS-4741] User random user instead of admin in e2e

.github/workflows/pull-request.yml
> - [x] Bugfix
Finalize job is skipped when previous one fails. https://alfresco.atlassian.net/browse/ACA-4666
**What …
=> [ACA-4666] Make finalize fail if any previous check fails

tsconfig.adf.json
> - [x] Bugfix
Merging this [PR](https://github.com/Alfresco/alfresco-ng2-components/pull/7856) on ADF, a new module …
=> [AAE-12511] Fix oidc breaking changes

.github/workflows/pull-request.yml, .github/workflows/release.yml
> - [x] Bugfix
upon merge, it takes the name of the source branch, not the target one …
=> fix publishing upon PR merge

cspell.json, projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.scss
…n Folder Rules
> - [x] Bugfix
Destination Folder ids are truncated on View Rule screen in Folder Rules
**What is the …
=> [ACS-4441] Destination folder ids are now properly visible on View Rule Screen in Folder Rules

projects/aca-folder-rules/assets/i18n/en.json, projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.ts
> - [x] Bugfix
If upload file is not selected, the 'create' buttons remains in enabled state. …
=> [ACS-4106] Removed default text for file upload placeholder

projects/aca-content/assets/app.extensions.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-4125
Add new default config …
=> [ACS-4125] Add support for the tags search facet

projects/aca-content/src/lib/components/header/header.component.scss, projects/aca-content/src/lib/ui/colors.scss, projects/aca-content/src/lib/ui/variables/variables.scss
> - [x] Bugfix
The ‘Primary’ mat-flat-button in ACA and alfresco-applications renders text in black color.
**What is …
=> [ACS-4964] Color fix for primary button text

app/src/app.config.json.tpl, projects/aca-folder-rules/src/lib/mock/conditions.mock.ts, projects/aca-folder-rules/src/lib/rule-details/conditions/rule-condition-fields.ts, projects/aca-folder-rules/src/lib/rule-details/conditions/rule-mime-types.ts, projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.html, projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.spec.ts, projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.ts, projects/aca-shared/src/lib/services/app.service.ts
…nditions.
> - [ ] Bugfix
You used to get a input field to input mime types in add condition while creating folder …
=> [ACS-4448] Adding selectable options of mime types in folder rules add conditions

projects/aca-content/src/lib/services/content-management.service.ts, projects/aca-content/src/lib/services/node-template.service.ts, projects/aca-content/src/lib/store/effects/upload.effects.spec.ts, projects/aca-content/src/lib/store/effects/upload.effects.ts
> - [X] Bugfix
After closing create and upload dialogs, the focus was not returning back to the menu/button …
=> [ACA-4692] fixed focus for create and upload modals

e2e/protractor.excludes.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4708
enabled [C290020] e2e …
=> [ACA-4708] enable e2e - [C290020] Empty Search results - Libraries

projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.html, projects/aca-testing-shared/src/components/search/search-input.ts
> - [ ] Bugfix
non-unique **data-automation-id="menu-item-title"** was being used in the toolbar-menu component to …
=> [ACS-5293] changed non-unique data automation ids

docs/upgrade-guide/upgrade211-30.md
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ADF-5532
Upgrade guide was not present for ACA3.0
**What is the …
=> [ADF-5532] Create upgrade211-30.md

e2e/suites/search/search-results-libraries.test.ts, projects/aca-content/assets/i18n/en.json, projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.html, projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.html
> - [x] Bugfix
1.After searching something in libraries, the search input should be visible but instead of that it …
=> [ACS-5156] Bug fixes for search Input

cspell.json, e2e/playwright/tests/folder-rules/page-objects/components/actions-dropdown.component.ts, e2e/playwright/tests/folder-rules/page-objects/components/conditions.component.ts, e2e/playwright/tests/folder-rules/page-objects/components/manage-rules-dialog.component.ts, e2e/playwright/tests/folder-rules/playwright.config.ts, e2e/playwright/tests/folder-rules/tests/actions.spec.ts, e2e/playwright/tests/folder-rules/tests/conditions.spec.ts, e2e/playwright/tests/folder-rules/tests/manage-rules.spec.ts
> - [ ] Bugfix
> - [x] Other... Please describe: e2e added steps …
=> [ACS-4887] e2e added test step for action tests

projects/aca-content/src/lib/components/common/logout/logout.component.ts
> - [x] Bugfix
Standalone logout component was missing import for DirectiveModule (required for adf-logout directive) …
=> Added missing DirectiveModule import in standalone LogoutComponent

app/src/app.config.json.tpl
> - [x] Bugfix
Earlier matDateTimePicker was used in ADF so type was 'datetime' which needs to be changed.
**What is …
=> [PRODSEC-6575] used date instead of datetime for datePicker implementation in Shared link dialog component in ADF

projects/aca-content/src/lib/aca-content.module.ts, projects/aca-shared/src/lib/services/app.service.ts
> - [x] Bugfix
Popup disappears after login and was only visible on refresh afer login into the application in ADW …
=> [MOBILEAPPS-1707] fix for pop up disappear issue in ADW

e2e/protractor/protractor.excludes.json, e2e/protractor/suites/actions/share/share-file.test.ts, projects/aca-shared/src/lib/services/app.service.ts, projects/aca-testing-shared/src/components/datetime-picker/datetime-picker.ts, projects/aca-testing-shared/src/components/dialog/share-dialog.ts
> - [x] Bugfix
C286327, C286332, C286333 e2e tests were failing for Share-file.tests.ts   …
=> e2e tests fix for new google calendar implemented

projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.scss, projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5374
When we refresh page, …
=> [ACS-5374] Fixed lost styles for library details after refreshing page

projects/aca-content/package.json, projects/aca-shared/package.json
> - [ ] Bugfix
JS-APU version bump
ACA libs are using latest JS-API
**Does this PR …
=> JS-API version fix in ACA libs

app/src/app.config.json
> - [x] Bugfix
'File type' filter gets applied without clicking on 'Apply' button. …
=> [ACS-5152] Fix for File type filter getting applied before clicking apply button

.github/actions/before-e2e/action.yml, .github/actions/run-e2e-playwright/action.yml
> - [ ] Bugfix
> - [ ] Other... Please describe: chrome version static set as v114
chrome version update to 115
chrome …
=> chrome version set to 114

e2e/playwright/viewer/src/tests/viewer.spec.ts, projects/aca-content/src/lib/components/files/files.component.html, projects/aca-content/src/lib/components/trashcan/trashcan.component.html
> - [ ] Bugfix
Checkboxes were implemented to handle bulk edit, which was removed from the scope of 23.1 version. …
=> [ACS-5638] hide checkboxes in file lists

projects/aca-content/src/lib/components/sidenav/sidenav.component.spec.ts, projects/aca-content/src/lib/components/sidenav/sidenav.component.ts
> - [X] Bugfix
In some cases, the 'expand navigation' icon was missing when it was needed, and vice versa. …
=> [ACS-5564] Bugfix: Expand navigation menu icon is visible even when navigation menu is expanded

projects/aca-content/src/lib/directives/document-list.directive.ts
> - [x] Bugfix
When entering a document list with server side sorting, icon in column header suggested there is a …
=> [AC-4313] - Add missing sorting in list component on init

projects/aca-content/src/lib/components/sidenav/components/expand-menu.component.html, projects/aca-content/src/lib/components/sidenav/sidenav.component.scss, projects/aca-content/src/lib/ui/overrides/ay11.scss
> - [x] Bugfix
Tab button is focusing twice on sidenav panel header and blue border cuses changing of height of …
=> [ACS-5692] - fix focus for sidenav options

e2e/protractor/e2e-config/utils/upload-output.js
> - [ ] Bugfix
remove the deprecated `AlfrescoApiCompatibility` usage and migrate to …
=> [ACS-5845] remove AlfrescoApiCompatibility usage

projects/aca-content/src/lib/store/effects/node.effects.ts
> - [x] Bugfix
When in viewer mode, clicking details disappear buttons hides side drawer only after first click, if …
=> [ACS-5841] - viewer details disappear on button click

projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.html
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5680
Properties' labels are not shown in edit mode in ADW. …
=> [ACS-5680] fix library properties to show labels in edit mode

projects/aca-content/src/lib/components/files/files.component.spec.ts, projects/aca-content/src/lib/components/files/files.component.ts
> - [x] Bugfix
The filters and header of the table disappears after a refresh if there are no records in the table. …
=> [ACS-5654] Retain filter header in document list.

projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.html, projects/aca-content/folder-rules/src/rule-details/options/rule-options.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/options/rule-options.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/options/rule-options.ui-component.ts
…le rules exist and clicking between them
> - [x] Bugfix
When clicking between different rules with different options …
=> [ACS-5284] - updating a folder rule options has no effect when multiple rules exist and clicking between them

projects/aca-content/src/lib/components/files/files.component.spec.ts, projects/aca-content/src/lib/components/files/files.component.ts, projects/aca-shared/src/lib/services/app.extension.service.spec.ts, projects/aca-shared/src/lib/services/app.extension.service.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-5563
Security marks are being …
=> [ACS-5563] Fixed incorrect initial loading of security marks

.eslintrc.json, app/karma.conf.js, app/project.json, e2e/playwright/actions/project.json, e2e/playwright/authentication/project.json, e2e/playwright/folder-rules/project.json, e2e/playwright/navigation/project.json, e2e/playwright/viewer/project.json, e2e/protractor/project.json, nx.json, projects/aca-content/.eslintrc.js, projects/aca-content/project.json, projects/aca-shared/.eslintrc.js, projects/aca-shared/project.json
> - [x] Bugfix
- fix coverage settings for the app
- fix eslint settings using …
=> ESLint fixes and unified lint targets

projects/aca-content/src/lib/components/toolbar/toggle-edit-offline/toggle-edit-offline.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5686
Node is reselected to …
=> [ACS-5686] add reselect to edit offline, shorten template

e2e/protractor/suites/search/search-filters.test.ts, e2e/protractor/suites/search/search-results-files-folders.test.ts
> - [ ] Bugfix
search-filter.test and search-results-file-folders.test use moment.js …
=> [APPS-2171][APPS-2172] Replace from moment.js to date-fns in search-filter.test and search-results-file-folders.test

projects/aca-shared/src/lib/components/document-base-page/document-base-page.component.ts, projects/aca-shared/src/lib/components/document-base-page/document-base-page.spec.ts
> - [x] Bugfix
There was a lack of consistency in document base page component. There was a condition that when i …
=> [ACS-5988] - Details tab not opening in custom file preview

projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.spec.ts, projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5949
Update button is …
=> [ACS-5949] library property update and cancel button do not reflect the change in UI

e2e/protractor/suites/info-drawer/file-folder-properties.test.ts, projects/aca-testing-shared/src/configs.ts
> - [ ] Bugfix
file-folder-properties.test.ts is using date fns dependency. …
=> [APPS-2170] Replace moment.js to date-fns in file-folder-properties.test.ts

projects/aca-content/src/lib/dialogs/node-template/create-from-template.dialog.html, projects/aca-content/src/lib/dialogs/node-template/create-from-template.dialog.scss, projects/aca-content/src/lib/dialogs/node-template/create-from-template.dialog.ts, projects/aca-playwright-shared/src/page-objects/components/dialogs/create-from-template-dialog-component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6078
Layout for 'Create from …
=> [ACS-6078] Fixed layout for create from template component

projects/aca-content/assets/i18n/en.json, projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.html, projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.spec.ts, projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6085
User can't edit library …
=> [ACS-6085] user is not prevented from renaming library to name containing only spaces

projects/aca-content/src/lib/components/details/details.component.html, projects/aca-content/src/lib/components/details/details.component.spec.ts, projects/aca-content/src/lib/components/details/details.component.ts
> - [X] Bugfix
Clicking on a folder from the breadcrumbs navigates the user to the previous page. …
=> [ACS-6106] Breadcrumb navigation fail on Details tab

e2e/protractor/protractor.excludes.json, e2e/protractor/suites/extensions/ext-info-drawer.test.ts, e2e/protractor/suites/info-drawer/file-folder-properties.test.ts
> - [ ] Bugfix
test suite fail due to DateFnsUtils adf import
e2e GA CI result fix, …
=> [ACS-6185 ] infoDriver test fix.

e2e/playwright/actions/src/tests/create-library.spec.ts, projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.html, projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.spec.ts, projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.ts, projects/aca-playwright-shared/src/page-objects/components/adf-info-drawer.component.ts, projects/aca-testing-shared/src/components/info-drawer/info-drawer-metadata-library.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5647
Template for Edit mode …
=> [ACS-5647] rework template of library metadata form component

e2e/protractor/suites/search/search-filters.test.ts, e2e/protractor/suites/search/search-results-files-folders.test.ts
> - [ ] Bugfix
> - [x] Other... Please describe: remove test related to file search
test fail on GA CI for search with date …
=> [ACS-6191] remove e2e test on search filter

projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.spec.ts, projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-5752
The visibility of the libraries are not getting updated …
=> [ACS-5752] Fixed incorrect info drawer properties update

projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.html, projects/aca-content/src/lib/components/favorites/favorites.component.html, projects/aca-content/src/lib/components/files/files.component.html, projects/aca-content/src/lib/components/libraries/libraries.component.html, projects/aca-content/src/lib/components/recent-files/recent-files.component.html, projects/aca-content/src/lib/components/shared-files/shared-files.component.html, projects/aca-content/src/lib/components/trashcan/trashcan.component.html
> - [ ] Bugfix
In document list component columns are static. Once configured via html or json, they can't be …
=> [ACS-5566] - add configurable columns to document list

.github/actions/publish-image/action.yml
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4722
There are multi-arch images of ACA available
**What is …
=> [ACA-4722] - add multi-arch images publish scripts

projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.html
> - [ ] Bugfix
Getting this "Aria-hidden element must not be focusable or contain focusable elements" for …
=> [ACS-6126] Fixed accessibility issue

.github/actions/get-image-tag/action.yml, .github/actions/publish-image/action.yml, .github/workflows/release.yml
> - [x] Bugfix
On develop there is failing job with pushing images.
Pipeline is fixed. …
=> [ACA-4722] - fix publish image script

.github/workflows/pull-request.yml, e2e/playwright/actions/src/tests/create-library.spec.ts, projects/aca-playwright-shared/src/api/index.ts, projects/aca-playwright-shared/src/api/trashcan-api.ts
> - [ ] Bugfix
Create library tests are failing often and have issues with deleting sites  …
=> [ACS-5511] create library tests update

projects/aca-content/folder-rules/src/folder-rules.rules.spec.ts, projects/aca-content/folder-rules/src/folder-rules.rules.ts, projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/rules/src/app.rules.ts
> - [x] Bugfix
'Manage rules' is visible for smart folders.
'Manage rules' is not …
=> [ACS-6278] - disable manage rules for smart folders

app/src/app.config.json, docker/docker-entrypoint.d/30-sed-on-appconfig.sh, docs/getting-started/docker.md, docs/getting-started/sso.md, docs/ja/getting-started/sso.md
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/MNT-22836
Code flow is not supported. …
=> [MNT-22836] - support of pkce o auth grant type by aims

app/src/app.config.json, projects/aca-content/assets/app.extensions.json, projects/aca-content/folder-rules/src/mock/action-parameter-constraints.mock.ts, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.ts, projects/aca-content/folder-rules/src/rule-details/conditions/rule-simple-condition.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/conditions/rule-simple-condition.ui-component.ts, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.ts, projects/aca-content/src/lib/aca-content.module.ts, projects/aca-content/src/lib/components/info-drawer/metadata-tab/metadata-tab.component.spec.ts, projects/aca-content/src/lib/components/info-drawer/metadata-tab/metadata-tab.component.ts, projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/rules/src/app.rules.ts, projects/aca-shared/src/lib/services/app.extension.service.spec.ts, projects/aca-shared/src/lib/services/app.extension.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-6252
Allowing to hide things …
=> [ACS-6252] support disabling the tags and categories feature in the applications

projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.html, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.ts, projects/aca-playwright-shared/src/page-objects/components/actions-dropdown.component.ts
> - [x] Bugfix
Create rule dialog had minor UI alignment issues
Fixed alignment issues …
=> [ACS-6211] Resolved UI alignment issue in create rule dialog

projects/aca-playwright-shared/src/resources/test-data/test-data-files-folders.ts, projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/rules/src/app.rules.ts
> - [x] Bugfix
On multi select file/folder permission menu should is shown
On multi …
=> [ACS-6369] - ACA on multi select file/folder permisstion menu should not be shown

projects/aca-content/src/lib/components/details/details.component.html, projects/aca-content/src/lib/components/details/details.component.spec.ts, projects/aca-content/src/lib/components/details/details.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6278
It's possible to enter permissions for smart folders …
=> [ACS-6278] - Permissions manager should not be showed for smart folder

projects/aca-shared/rules/src/app.rules.ts
Enable case-insensitive matching when determining file extensions in the application. This enhancement ensures that the system accurately recognizes and processes file extensions regardless of the case used in the filenames.
> - [x] Bugfix
> - [ ] …
=> [#3569] Implement case-insensitive matching for file extensions

projects/aca-content/src/lib/aca-content.routes.ts, projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.html, projects/aca-content/src/lib/components/favorites/favorites.component.html, projects/aca-content/src/lib/components/files/files.component.html, projects/aca-content/src/lib/components/libraries/libraries.component.html, projects/aca-content/src/lib/components/recent-files/recent-files.component.html, projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.html, projects/aca-content/src/lib/components/search/search-results/search-results.component.html, projects/aca-content/src/lib/components/shared-files/shared-files.component.html, projects/aca-content/src/lib/components/trashcan/trashcan.component.html, projects/aca-content/src/lib/directives/document-list.directive.spec.ts, projects/aca-content/src/lib/directives/document-list.directive.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-6325
Document list columns …
=> [ACS-6325] Persisting configuration of document list columns size, visibility and order

projects/aca-content/src/lib/ui/colors.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6212
Color for warning …
=> [ACS-6212] Corrected color for warning

projects/aca-testing-shared/src/components/dialog/upload-files-dialog.ts, projects/aca-testing-shared/src/utilities/test-element.ts
> - [ ] Bugfix
bug fixes in the e2e helper code;
unused code cleanup
**Does this PR …
=> e2e bug fixes and code cleanup

projects/aca-content/src/lib/store/effects/node.effects.spec.ts, projects/aca-content/src/lib/store/effects/node.effects.ts
> - [x] Bugfix
Manage Permissions window could not be opened from inside file preview. The URL got updated to a wrong …
=> [ACS-6573] Manage permissions window can now be opened from inside file preview

projects/aca-shared/src/lib/services/app.service.spec.ts, projects/aca-shared/src/lib/services/app.service.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-6576
Local storage prefix is created/updated only with basic …
=> [ACS-6576] Local storage prefix is not always created/updated properly in ADW 

projects/aca-content/src/lib/components/search/search-results/search-results.component.html, projects/aca-content/src/lib/components/search/search-results/search-results.component.spec.ts, projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
> - [x] Bugfix
Tags column and getTags API was still being called from search page, even if the tags plugin was …
=> [ACS-6642] Tags column and getTags API call is now dynamic on app.config.json for search page

.github/workflows/upstream-adf.yml, scripts/update-version.sh
> - [x] Bugfix
Upstream workflow right now correctly updates JS-API version first …
=> [ACA-4732] Update JS-API version first to fix upstream workflow

docs/extending/application-features.md, docs/ja/extending/application-features.md, docs/tutorials/custom-viewer.md, extension.schema.json, projects/aca-content/assets/app.extensions.json
> - [x] Bugfix
Viewer extension config uses `content` key to get viewer extensions. …
=> [ACS-6620] Use extensions instead of content key for viewer extensions

projects/aca-content/src/lib/components/files/files.component.spec.ts, projects/aca-content/src/lib/components/files/files.component.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-6583
Folder uploaded with drag and drop has extra `/` in the …
=> [ACS-6583] Fix flickering toolbar on folder upload

projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.spec.ts, projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.ts, projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/rules/src/app.rules.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-6445
When a user is a member of the ALFRESCO_ADMINISTRATOR …
=> [ACS-6445] Address #PT20471_7 Missing Access Control

projects/aca-shared/src/lib/services/app.extension.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/MNT-24151
Extensions can't extend exsiting rules, they can only …
=> [MNT-24151] - ADW: Users can see some actions Edit Offline" and "Upload New Version" for the declared record

.stylelintrc.json, package-lock.json, package.json, projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.html, projects/aca-content/folder-rules/src/rule-details/conditions/rule-simple-condition.ui-component.html, projects/aca-content/folder-rules/src/rule-details/conditions/rule-simple-condition.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/edit-rule-dialog.ui-component.html, projects/aca-content/folder-rules/src/rule-details/edit-rule-dialog.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss, projects/aca-content/folder-rules/src/rule-list/rule-list/rule-list.ui-component.html, projects/aca-content/folder-rules/src/rule-list/rule-list/rule-list.ui-component.scss, projects/aca-content/src/lib/components/details/details.component.html, projects/aca-content/src/lib/components/details/details.component.scss, projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.html, projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.scss, projects/aca-content/src/lib/components/search/search-input/search-input.component.scss, projects/aca-content/src/lib/components/search/search-results/search-results.component.scss, projects/aca-content/src/lib/components/view-profile/view-profile.component.html, projects/aca-content/src/lib/components/view-profile/view-profile.component.scss, projects/aca-content/src/lib/dialogs/node-template/create-from-template.dialog.scss, projects/aca-content/src/lib/ui/overrides/adf-about.theme.scss, projects/aca-content/src/lib/ui/overrides/adf-pagination.theme.scss, projects/aca-content/src/lib/ui/overrides/ay11.scss, projects/aca-content/src/lib/ui/theme.scss, projects/aca-shared/src/lib/components/generic-error/generic-error.component.html, projects/aca-shared/src/lib/components/generic-error/generic-error.component.scss
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-6140
All internal Angular …
=> [ACS-6140] - Remove references to internal Angular Material CSS classes

e2e/protractor/suites/actions/delete/delete-undo-delete.test.ts, e2e/protractor/suites/actions/delete/permanently-delete.test.ts, e2e/protractor/suites/actions/delete/restore.test.ts, e2e/protractor/suites/actions/edit/edit-offline.test.ts, e2e/protractor/suites/actions/favorite/mark-favorite.test.ts, e2e/protractor/suites/actions/upload-download/download.test.ts, e2e/protractor/suites/actions/upload-download/upload-file.test.ts, e2e/protractor/suites/actions/upload-download/upload-new-version.test.ts, e2e/protractor/suites/actions/upload-download/version-actions.test.ts, e2e/protractor/suites/viewer/viewer-actions.test.ts, projects/aca-playwright-shared/src/api/nodes-api.ts, projects/aca-testing-shared/src/utilities/repo-client/apis/nodes/nodes-api.ts, projects/aca-testing-shared/src/utilities/user-actions.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5994 …
=> [ACS-5994] Remove redundant deleteNodes method from e2e

projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.scss
> - [x] Bugfix
Search input is not clickable when filled.
Search input is always …
=> [ACS-6828] Clicking on search input when it has some content inside it does not allow user to edit search term

package-lock.json, package.json, projects/aca-content/src/lib/components/info-drawer/metadata-tab/metadata-tab.component.ts
> - [x] Bugfix
Stored display aspect is not passed to metadata panel.
Stored display …
=> [ACS-6831] Correctly pass stored displayAspect to metadata component

projects/aca-content/src/lib/services/content-management.service.spec.ts, projects/aca-content/src/lib/services/content-management.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6891
After deleting a library, user stays on the library …
=> [ACS-6891] The user is not redirected to the library page after deleting the library from the Manage Members view

e2e/playwright/search/src/search-input.spec.ts, e2e/playwright/search/src/tests/search-input.spec.ts, projects/aca-playwright-shared/src/page-objects/components/search/search-overlay.components.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Migrated tests from Protractor to Playwright …
=> [ACS-6795] Search Input tests migrated to Playwright

app/src/app.config.json, docker/docker-entrypoint.d/30-sed-on-appconfig.sh, projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/rules/src/app.rules.ts
> - [x] Bugfix
Tags and categories plugins has been renamed to mitigate naming …
=> [ACS-6924] Rename tags and categories plugins to mitigate naming conflicts

projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.ts
> - [ ] Bugfix
Link to a category action has a text input, where user must type in category id. …
=> [ACS-6150] Folder rules - add category selector for link category action

projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.scss, projects/aca-content/folder-rules/src/rule-details/actions/rule-action-list.ui-component.html, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.html, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/edit-rule-dialog.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.html, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-7330 …
=> [ACS-7330] NG15 Edit rules dialog fixes

e2e/playwright/list-views/src/tests/favorites.spec.ts, e2e/playwright/list-views/src/tests/file-libraries.spec.ts, e2e/playwright/list-views/src/tests/generic-errors.spec.ts, e2e/playwright/list-views/src/tests/permissions.spec.ts, e2e/playwright/list-views/src/tests/personal-files.spec.ts, e2e/playwright/list-views/src/tests/recent-files.spec.ts, e2e/playwright/list-views/src/tests/shared-files.spec.ts, e2e/playwright/list-views/src/tests/trash-admin.spec.ts, e2e/playwright/list-views/src/tests/trash.spec.ts, projects/aca-playwright-shared/src/utils/utils.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7298
[ACS-7298] beforeEach and …
=> [ACS-7298] beforeEach and afterAll updated for list-views

e2e/playwright/navigation/src/tests/breadcrumb-admin.spec.ts, e2e/playwright/navigation/src/tests/breadcrumb.spec.ts, e2e/playwright/navigation/src/tests/sidebar.spec.ts, e2e/playwright/navigation/src/tests/single-click.spec.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7300
[ACS-7300] beforeEach and …
=> [ACS-7300] beforeEach and afterAll refactored for navigation tests

e2e/playwright/share-action/src/tests/share/unshare-file-search-results.e2e.ts, projects/aca-playwright-shared/src/page-objects/components/dialogs/share-dialog.component.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7303
[ACS-7303] beforeEach and …
=> [ACS-7303] beforeEach and afterAll updated for share-action tests

.eslintrc.json, e2e/playwright/create-actions/src/tests/create-library.e2e.ts, projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/conditions/rule-simple-condition.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/options/rule-options.ui-component.spec.ts, projects/aca-content/folder-rules/src/services/folder-rule-sets.service.spec.ts, projects/aca-content/src/lib/components/toolbar/view-node/view-node.component.spec.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7311
Rule disallowing Angular …
=> [ACS-7311] add no-angular-material-selectors eslint rule

app/src/test.ts, package-lock.json, package.json, projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/conditions/rule-simple-condition.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/options/rule-options.ui-component.html, projects/aca-content/folder-rules/src/rule-details/options/rule-options.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/triggers/rule-triggers.ui-component.spec.ts, projects/aca-content/preview/src/test.ts, projects/aca-content/project.json, projects/aca-content/src/lib/components/context-menu/context-menu-item.component.html, projects/aca-content/src/lib/components/context-menu/context-menu-item.component.spec.ts, projects/aca-content/src/lib/components/context-menu/context-menu.component.html, projects/aca-content/src/lib/components/context-menu/context-menu.component.spec.ts, projects/aca-content/src/lib/components/toolbar/view-node/view-node.component.spec.ts, projects/aca-content/test.ts, projects/aca-content/viewer/src/test.ts, projects/aca-shared/test.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7368 …
=> [ACS-7368] - fix unit tests for ACA content

e2e/playwright/search/src/tests/search-filters-date.e2e.ts, projects/aca-playwright-shared/src/page-objects/components/search/search-filters/search-filters-date.component.ts, projects/aca-playwright-shared/src/page-objects/pages/search.page.ts, projects/aca-playwright-shared/src/utils/utils.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7334
Search filters - date - …
=> [ACS-7334] [E2E] Search filters - date - tests migrated to Playwright

app/src/app/app.module.ts, app/src/app/app.routes.ts, app/src/app/components/login/app-login.component.html, app/src/app/components/login/app-login.component.ts, docs/extending/custom-extension-loaders.md
> - [x] Bugfix
- rename LoginComponent to AppLoginComponent
- remove unsupported …
=> Fix LoginComponent naming conficts

projects/aca-content/src/lib/ui/theme.scss, projects/aca-content/src/lib/ui/variables/variables.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7560
Info notification has …
=> [ACS-7560] Corrected background color for info snackbar

projects/aca-content/folder-rules/src/mock/actions.mock.ts, projects/aca-content/folder-rules/src/mock/security-marks.mock.ts, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.ts
> - [ ] Bugfix
**What is the current behaviour?**
https://hyland.atlassian.net/browse/ACS-6595
Security Mark Id Action Parameter in Folder Rules has input in the form of textbox, no values are …
=> [ACS-6595] Add security marks for Folder Rules

projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.scss, projects/aca-content/folder-rules/src/rule-details/actions/rule-action-list.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.html, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.html, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.ts, projects/aca-content/folder-rules/src/rule-details/conditions/rule-simple-condition.ui-component.html, projects/aca-content/folder-rules/src/rule-details/conditions/rule-simple-condition.ui-component.ts, projects/aca-content/folder-rules/src/rule-details/options/rule-options.ui-component.html, projects/aca-content/folder-rules/src/rule-details/options/rule-options.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.html, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7573 …
=> [ACS-7573] folder rules fixes

app/src/app/app.module.ts, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.html, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.html, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss, projects/aca-content/src/lib/components/info-drawer/library-metadata-tab/library-metadata-form.component.html, projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.html, projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.scss, projects/aca-content/src/lib/components/search/search-input/search-input.component.html, projects/aca-content/src/lib/components/search/search-input/search-input.component.scss, projects/aca-content/src/lib/components/view-profile/view-profile.component.html, projects/aca-content/src/lib/components/view-profile/view-profile.component.scss, projects/aca-content/src/lib/components/view-profile/view-profile.component.ts, projects/aca-content/src/lib/dialogs/node-template/create-from-template.dialog.html
Reverts Alfresco/alfresco-content-app#3845
=> [ACS-7768] unify inputs and selects across the app - revert

projects/aca-content/folder-rules/src/rule-details/actions/rule-action-list.ui-component.html, projects/aca-content/folder-rules/src/rule-details/actions/rule-action-list.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.html, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.html, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/options/rule-options.ui-component.html, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.html, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8027 …
=> [ACS-8027] Inputs for create rules

e2e/playwright/search/src/tests/search-filters-date.e2e.ts, projects/aca-playwright-shared/src/page-objects/components/search/search-filters/search-filters-date.component.ts, projects/aca-playwright-shared/src/page-objects/components/search/search-filters/search-filters-properties.component.ts
> - [ ] Bugfix
> - [x] Other... Please describe: e2e fix
**What is the new behaviour?** e2e fix for angular 15 branch for search test
**Does this PR …
=> [ACS-8082] fix search e2e

projects/aca-content/src/lib/ui/theme.scss
> - [x] Bugfix
Long tag names were not getting word wrapped in ACA after angular upgrade. Tag delete X button was …
=> [ACS-8158] Resolved issue where long tag names were not getting word wrapped in ACA. Fixed alignment issue with tag chip cross button

projects/aca-content/folder-rules/src/mock/actions.mock.ts, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.spec.ts, projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/ACS-8190
Marking folders in Choose destination folder component …
=> [ACS-8190] Change node selection to single for rule actions

projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.html, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/conditions/rule-simple-condition.ui-component.html
=> [ACS-8101] [ACA] manage rule popup visual changes

projects/aca-content/folder-rules/src/manage-rules/manage-rules.smart-component.scss, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss, projects/aca-content/folder-rules/src/rule-set-picker/rule-set-picker.smart-component.scss, projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.scss, projects/aca-content/src/lib/components/search/search-input/search-input.component.scss, projects/aca-content/src/lib/ui/overrides/adf-about.theme.scss, projects/aca-content/src/lib/ui/theme.scss, projects/aca-shared/project.json, projects/aca-shared/src/lib/components/open-in-app/open-in-app.component.scss, projects/aca-shared/src/lib/components/toolbar/toolbar-menu-item/toolbar-menu-item.component.scss, projects/aca-shared/src/lib/components/toolbar/toolbar-menu-item/toolbar-menu-item.component.ts
> - [ ] Bugfix
A lot of the codebase was using hardcoded selectors for angular material classes …
=> [ACS-8191] Updated codebase to use variables from mat-selectors.scss file

projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/rules/src/app.rules.ts
> - [ ] Bugfix
In ADW we do not have the option to multi move/delete items in the result page …
=> [MNT-24334] from the search result page in ADW, we can not multi select result to delete or move

projects/aca-content/src/lib/store/effects/search.effects.spec.ts, projects/aca-content/src/lib/store/effects/search.effects.ts
> - [x] Bugfix
- support `%` for search terms within the browser url
- fixes: #3886 …
=> A percentage sign (%) in the search breaks the app

docs/tutorials/how-to-create-your-first-extension.md, projects/aca-shared/src/lib/components/document-base-page/document-base-page.spec.ts
> - [ ] Bugfix
remove any imports of the ADF `MaterialModule` (unit tests)
**Does this …
=> Remove MaterialModule import from ADF

projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.html, projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.scss, projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss, projects/aca-content/src/lib/ui/theme.scss
> - [ ] Bugfix
UI fixes - Inputs throughout the application appeared to have fill styling applied
Inputs throughout …
=> [ACS-8378] Fixed inputs having fill styling throughout ACA

projects/aca-content/src/lib/components/search/search-input/search-input.component.scss
> - [x] Bugfix
Icons in search input were misaligned after ng16 upgrade
Fixed …
=> [ACS-8377] Fixed alignment of icons in search input control

projects/aca-content/src/lib/components/sidenav/sidenav.component.scss
> - [ ] Bugfix
Sidenav labels were black after ng16 upgrade
Sidenav labels were black after ng16 upgrade
**What is …
=> [ACS-8415] Sidenav labels are now grey

projects/aca-content/src/lib/ui/theme.scss
> - [x] Bugfix
Icons inside menus were coming up as black after ng16 upgrade
Icons are …
=> [ACS-8379] Fixed issue where icons in menus were coming as black after ng16 upgrade

projects/aca-content/assets/app.extensions.json, projects/aca-content/folder-rules/src/folder-rules.module.ts, projects/aca-shared/src/lib/routing/plugin-enabled.guard.spec.ts, projects/aca-shared/src/lib/routing/plugin-enabled.guard.ts, projects/aca-shared/src/public-api.ts
> - [ ] Bugfix
User can open page for specific plugin by typing url even if plugin is disabled …
=> [ACS-6926] Fix plugins routing

app/src/app.config.json, app/src/app/app.module.ts, karma.conf.js, projects/aca-content/src/lib/components/details/details.component.spec.ts, projects/aca-content/src/lib/components/search/search-results/search-results.component.ts, projects/aca-content/src/lib/components/sidenav/components/sidenav-header.component.html, projects/aca-content/src/lib/components/sidenav/components/sidenav-header.component.ts, projects/aca-content/src/lib/services/content-management.service.ts, projects/aca-content/src/lib/store/initial-state.ts, projects/aca-content/src/lib/store/reducers/app.reducer.ts, projects/aca-content/src/lib/testing/app-testing.module.ts, projects/aca-shared/src/lib/components/document-base-page/document-base-page.component.ts, projects/aca-shared/src/lib/services/app-settings.service.ts, projects/aca-shared/src/lib/services/app.service.spec.ts, projects/aca-shared/src/lib/services/app.service.ts, projects/aca-shared/store/src/actions/app-action-types.ts, projects/aca-shared/store/src/actions/app.actions.ts, projects/aca-shared/store/src/selectors/app.selectors.ts, projects/aca-shared/store/src/states/app.state.ts
> - [ ] Bugfix
- ACS-8404: consolidate application settings
- remove useless …
=> ACS-8404: consolidate application settings

docs/extending/application-features.md, extension.schema.json
> - [ ] Bugfix
Extension schema has been reviewed, outdated code has been removed, …
=> [ACS-8410] Extension schema review

.github/workflows/pull-request.yml, app/src/app/app.component.html, app/src/app/app.components.ts, karma.conf.js, projects/aca-content/src/lib/components/common/user-info/user-info.component.ts, projects/aca-content/src/lib/components/sidenav/user-menu/user-menu.component.ts, projects/aca-content/src/lib/components/toolbar/toggle-join-library/toggle-join-library-button.component.ts, projects/aca-content/src/lib/components/trashcan/trashcan.component.ts, projects/aca-content/src/lib/store/reducers/app.reducer.ts, projects/aca-shared/src/lib/services/app.service.spec.ts, projects/aca-shared/src/lib/services/app.service.ts, projects/aca-shared/src/lib/services/user-profile.service.ts, projects/aca-shared/src/public-api.ts, projects/aca-shared/store/src/actions/app.actions.ts, projects/aca-shared/store/src/selectors/app.selectors.ts
> - [x] Bugfix
- fix GHA running same unit tests multiple times
- [ACS-8433]: …
=> [ACS-8433] ACA: User Profile Service

projects/aca-content/ms-office/src/effects/aos.effects.ts, projects/aca-content/src/lib/store/effects/app.effects.ts, projects/aca-content/src/lib/store/effects/contextmenu.effects.ts, projects/aca-content/src/lib/store/effects/download.effects.ts, projects/aca-content/src/lib/store/effects/favorite.effects.ts, projects/aca-content/src/lib/store/effects/library.effects.ts, projects/aca-content/src/lib/store/effects/node.effects.ts, projects/aca-content/src/lib/store/effects/search.effects.ts, projects/aca-content/src/lib/store/effects/template.effects.ts, projects/aca-content/src/lib/store/effects/upload.effects.ts, projects/aca-content/src/lib/store/effects/viewer.effects.ts, projects/aca-shared/store/src/effects/dialog.effects.ts, projects/aca-shared/store/src/effects/router.effects.ts, projects/aca-shared/store/src/effects/snackbar.effects.ts
=> refactor DI into inject() methods

e2e/playwright/create-actions/src/tests/create-file-from-template.e2e.ts, e2e/playwright/create-actions/src/tests/create-folder-from-template.e2e.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8185
[ACS-8185] [E2E] updated …
=> [ACS-8185] [E2E] updated type to fill

projects/aca-shared/src/lib/components/toolbar/toolbar-action/toolbar-action.component.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8446
Button looks like …
=> [ACS-8446] [ACA] Testing Angular 15 - Create button has no bolded text

projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.scss
> - [x] Bugfix
Dropdown arrow and close icon alignment in search input was broken after ng15 upgrade
**What is the …
=> [ACS-8449] Fixed alignment of close and dropdown icon in search input

extension.schema.json, projects/aca-content/assets/app.extensions.json, projects/aca-content/assets/i18n/en.json, projects/aca-content/src/lib/aca-content.module.ts, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.html, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.scss, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.spec.ts, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.ts, projects/aca-content/src/lib/components/search/search-results/search-results.component.html, projects/aca-content/src/lib/components/search/search-results/search-results.component.ts, projects/aca-content/src/lib/store/reducers/app.reducer.ts, projects/aca-shared/src/lib/components/document-base-page/document-base-page.component.ts, projects/aca-shared/src/lib/models/types.ts, projects/aca-shared/src/lib/services/app.extension.service.spec.ts, projects/aca-shared/src/lib/services/app.extension.service.ts, projects/aca-shared/store/src/actions/app.actions.ts, projects/aca-shared/store/src/selectors/app.selectors.ts, projects/aca-shared/store/src/states/app.state.ts
https://hyland.atlassian.net/browse/ACS-8325
> - [ ] Bugfix
Add dropdown to the search …
=> [ACS-8325] [Bulk Legal Hold] Create Bulk Actions Dropdown

projects/aca-content/src/lib/components/details/details.component.scss
> - [x] Bugfix
Reduce panel details button was  not aligned properly after ng15 upgrade …
=> [ACS-8453] Fixed alignment issue of reduce panel button in expanded file details

projects/aca-content/assets/app.extensions.json, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.html, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.spec.ts, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.ts, projects/aca-shared/src/lib/services/app.extension.service.spec.ts, projects/aca-shared/src/lib/services/app.extension.service.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8326
Actions are run on bulk …
=> [ACS-8326] enable running actions from bulk dropdown and resetting selection

projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.ts, projects/aca-content/src/lib/components/toolbar/view-node/view-node.component.ts, projects/aca-shared/src/lib/components/document-base-page/document-base-page.component.ts, projects/aca-shared/src/lib/services/aca-file-auto-download.service.spec.ts, projects/aca-shared/src/lib/services/app-settings.service.ts, projects/aca-shared/src/lib/services/auto-download.service.ts, projects/aca-shared/src/public-api.ts
> - [ ] Bugfix
- rename to `AutoDownloadService`
- break dependency on the …
=> [ACS-8508] Rework auto-download service

e2e/playwright/copy-move-actions/src/tests/destination-picker-dialog.e2e.ts, e2e/playwright/delete-actions/src/tests/delete-undo-delete.e2e.ts, e2e/playwright/delete-actions/src/tests/permanently-delete.e2e.ts, e2e/playwright/delete-actions/src/tests/restore.e2e.ts, e2e/playwright/edit-actions/src/tests/edit-folder.e2e.ts, e2e/playwright/edit-actions/src/tests/edit-offline.e2e.ts, e2e/playwright/favorite-actions/src/tests/mark-favorite.e2e.ts, e2e/playwright/folder-rules/src/tests/create-rules.e2e.ts, e2e/playwright/info-drawer/src/tests/comments.e2e.ts, e2e/playwright/info-drawer/src/tests/general.e2e.ts, e2e/playwright/share-action/src/tests/share/share-file.e2e.ts, e2e/playwright/share-action/src/tests/share/unshare-file-search-results.e2e.ts, e2e/playwright/special-permissions-actions-available/src/tests/folders-actions.e2e.ts, e2e/playwright/special-permissions-actions-available/src/tests/other-permissions.ts, e2e/playwright/upload-download-actions/src/tests/download.e2e.ts, e2e/playwright/upload-download-actions/src/tests/upload-new-version.e2e.ts, e2e/playwright/upload-download-actions/src/tests/version-actions.e2e.ts, projects/aca-playwright-shared/src/page-objects/components/dataTable/data-table.component.ts, projects/aca-playwright-shared/src/page-objects/pages/personal-files.page.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8561
[ACS-8561] [E2E] …
=> [ACS-8561] [E2E] Merge-selectItem-and-selectMultiItem-into-one-method

projects/aca-content/assets/app.extensions.json, projects/aca-content/src/lib/aca-content.module.ts, projects/aca-content/src/lib/components/search/search-results/search-results.component.scss, projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/rules/src/app.rules.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8371
- inline viewer correctly …
=> [ACS-8371] Fix viewer preview

projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.html, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.spec.ts, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.ts, projects/aca-content/src/lib/components/dl-custom-components/datatable-cell-badges/datatable-cell-badges.component.html, projects/aca-content/src/lib/components/dl-custom-components/datatable-cell-badges/datatable-cell-badges.component.spec.ts, projects/aca-content/src/lib/components/dl-custom-components/datatable-cell-badges/datatable-cell-badges.component.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8489
Added keyboard …
=> [ACS-8489] Legal Holds keyboard accessibility

extension.schema.json, projects/aca-content/assets/i18n/en.json, projects/aca-content/src/lib/aca-content.module.ts, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.html, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.scss, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.spec.ts, projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.ts, projects/aca-content/src/lib/components/dl-custom-components/datatable-cell-badges/datatable-cell-badges.component.html, projects/aca-content/src/lib/components/dl-custom-components/datatable-cell-badges/datatable-cell-badges.component.scss, projects/aca-content/src/lib/components/dl-custom-components/datatable-cell-badges/datatable-cell-badges.component.spec.ts, projects/aca-content/src/lib/components/dl-custom-components/datatable-cell-badges/datatable-cell-badges.component.ts, projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.html, projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.scss, projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.spec.ts, projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.ts, projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.html, projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.scss, projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.spec.ts, projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.ts, projects/aca-content/src/lib/components/search/search-results/search-results.component.html, projects/aca-content/src/lib/components/search/search-results/search-results.component.ts, projects/aca-content/src/lib/store/reducers/app.reducer.ts, projects/aca-shared/src/lib/components/document-base-page/document-base-page.component.ts, projects/aca-shared/src/lib/models/types.ts, projects/aca-shared/src/lib/services/app.extension.service.spec.ts, projects/aca-shared/src/lib/services/app.extension.service.ts, projects/aca-shared/store/src/actions/app-action-types.ts, projects/aca-shared/store/src/actions/app.actions.ts, projects/aca-shared/store/src/selectors/app.selectors.ts, projects/aca-shared/store/src/states/app.state.ts
https://hyland.atlassian.net/browse/ACS-8036
> - [ ] Bugfix …
=> [ACS-8036] [Bulk update] [Many files to 1 Hold flow] "Manage Holds" dialog with Manage Existing Holds/Apply New Hold tabs

e2e/playwright/library-actions/src/tests/library-actions.e2e.ts, e2e/playwright/list-views/src/tests/empty-list.e2e.ts, e2e/playwright/list-views/src/tests/permissions.e2e.ts, e2e/playwright/navigation/src/tests/sidebar.e2e.ts, e2e/playwright/search/src/tests/search-input.e2e.ts, e2e/playwright/search/src/tests/search-results-general.e2e.ts, e2e/playwright/share-action/src/tests/share/unshare-file-search-results.e2e.ts, e2e/playwright/upload-download-actions/src/tests/version-actions.e2e.ts, e2e/playwright/viewer/src/tests/viewer.e2e.ts, projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.html, projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.scss, projects/aca-content/src/lib/components/search/search-input/search-input.component.html, projects/aca-content/src/lib/components/search/search-input/search-input.component.scss, projects/aca-content/src/lib/components/search/search-input/search-input.component.spec.ts, projects/aca-playwright-shared/src/page-objects/components/aca-header.component.ts, projects/aca-playwright-shared/src/page-objects/components/search/search-input.component.ts, projects/aca-playwright-shared/src/page-objects/components/search/search-overlay.components.ts, projects/aca-playwright-shared/src/page-objects/pages/search.page.ts
> - [x] Bugfix
- cleanup and refine the Search Input layout
- grealy reduce the CSS …
=> ACS-8584: Fix for Search Input and icons

.github/workflows/upstream-adf.yml, scripts/gh/update/latest-version-of.js
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8659
ADF upstream now properly …
=> [ACS-8659] Refine ADF upstream to pick only 'alpha' versions

.github/workflows/upstream-adf.yml, scripts/gh/update/latest-version-of.js
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7970
When upstream is triggered …
=> [ACS-7970] Add the option to select a tag for ADF upstream

projects/aca-content/src/lib/components/dl-custom-components/thumbnail-column/thumbnail-column.component.html, projects/aca-content/src/lib/components/dl-custom-components/thumbnail-column/thumbnail-column.component.spec.ts, projects/aca-content/src/lib/components/dl-custom-components/thumbnail-column/thumbnail-column.component.ts
> - [x] Bugfix
- add support for material icons alongside image urls when rendering …
=> ACS-8658: fix search icon for lock files

scripts/gh/update/latest-version-of.js
Small fix adding the default value to the tag since GHA default value is not taken into account when it's being triggered via cron.
=> Upstream input fix

projects/aca-content/src/lib/services/content-management.service.spec.ts, projects/aca-content/src/lib/services/content-management.service.ts
https://hyland.atlassian.net/browse/ACS-8677
=> [ACS-8677] Refresh document list after file version restore

projects/aca-content/src/lib/components/view-profile/view-profile.guard.ts, projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.spec.ts, projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.ts, projects/aca-shared/src/lib/routing/plugin-enabled.guard.spec.ts, projects/aca-shared/src/lib/routing/plugin-enabled.guard.ts, projects/aca-shared/src/lib/routing/shared.guard.spec.ts, projects/aca-shared/src/lib/routing/shared.guard.ts
Move to functional route guards
https://hyland.atlassian.net/browse/ACS-8726
=> [ACS-8726] Use functional route guards

e2e/playwright/search/src/tests/search-highlighting.e2e.ts, projects/aca-playwright-shared/src/page-objects/components/dataTable/data-table.component.ts
https://hyland.atlassian.net/browse/ACS-7466
=> [ACS-7466] [E2E] Added e2e tests for search highlighting

docs/extending/rules.md
https://hyland.atlassian.net/browse/ACS-8693
Add missing documentation for visibility rules accepting arrays
=> [ACS-8693] Add docs for visibility rules accepting arrays

projects/aca-content/src/lib/components/favorites/favorites.component.spec.ts, projects/aca-content/src/lib/components/files/files.component.spec.ts, projects/aca-content/src/lib/components/recent-files/recent-files.component.spec.ts, projects/aca-content/src/lib/components/search/search-results/search-results.component.spec.ts, projects/aca-content/src/lib/components/shared-files/shared-files.component.spec.ts, projects/aca-content/src/lib/store/effects/search-ai.effects.spec.ts, projects/aca-content/src/lib/testing/document-base-page-utils.ts, projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/src/lib/components/document-base-page/document-base-page.spec.ts
https://hyland.atlassian.net/browse/ACS-8398
=> [ACS-8398] unit tests part 3

e2e/playwright/authentication/exclude.tests.json, e2e/playwright/copy-move-actions/exclude.tests.json, e2e/playwright/delete-actions/exclude.tests.json, e2e/playwright/edit-actions/exclude.tests.json, e2e/playwright/folder-rules/exclude.tests.json, e2e/playwright/list-views/exclude.tests.json, e2e/playwright/list-views/src/tests/trash-admin.e2e.ts, e2e/playwright/navigation/exclude.tests.json, e2e/playwright/search/exclude.tests.json, e2e/playwright/upload-download-actions/exclude.tests.json, projects/aca-playwright-shared/src/page-objects/components/dataTable/data-table.component.ts, projects/aca-playwright-shared/src/page-objects/components/manageRules/manage-rules-dialog.component.ts, projects/aca-playwright-shared/src/page-objects/components/sidenav.component.ts
https://hyland.atlassian.net/browse/ACS-8886
=> [ACS-8886] enable excluded test from ACA

e2e/playwright/info-drawer/src/tests/file-folder-properties.e2e.ts, projects/aca-playwright-shared/src/api/tags-api.ts, projects/aca-playwright-shared/src/page-objects/components/adf-info-drawer.component.ts
https://hyland.atlassian.net/browse/ACS-8951
=> [ACS-8951] [E2E] tags and categories e2es added in ACA

projects/aca-content/folder-rules/src/services/folder-rule-sets.service.spec.ts, projects/aca-content/folder-rules/src/services/folder-rule-sets.service.ts
https://hyland.atlassian.net/browse/ACS-8914
=> [ACS-8914] Fix error on manage rules page open

docs/features/README.md, docs/features/context-menu-actions.md, projects/aca-content/src/lib/components/context-menu/base-context-menu.component.ts, projects/aca-content/src/lib/components/context-menu/base-context-menu.directive.spec.ts, projects/aca-content/src/lib/components/context-menu/base-context-menu.directive.ts, projects/aca-content/src/lib/components/context-menu/context-menu.component.ts, projects/aca-content/src/lib/components/context-menu/context-menu.service.spec.ts, projects/aca-content/src/lib/components/context-menu/context-menu.service.ts, projects/aca-content/src/lib/components/context-menu/custom-context-menu-actions.token.ts, projects/aca-content/src/lib/components/context-menu/custom-context-menu.component.spec.ts, projects/aca-content/src/lib/components/context-menu/custom-context-menu.component.ts, projects/aca-content/src/lib/store/app-store.module.ts, projects/aca-content/src/lib/store/effects/contextmenu.effects.spec.ts, projects/aca-content/src/lib/store/effects/contextmenu.effects.ts, projects/aca-shared/src/lib/directives/contextmenu/contextmenu.directive.spec.ts, projects/aca-shared/src/lib/directives/contextmenu/contextmenu.directive.ts, projects/aca-shared/store/src/actions/contextmenu.actions.ts
https://hyland.atlassian.net/browse/ACS-8706
Context menu is split into separate components: base component, default context menu used in ACA and custom context menu, allowing to inject custom actions.
=> [ACS-8706] split context menu to allow injecting actions

projects/aca-content/src/lib/components/search/search-save/dialog/edit/saved-search-edit-dialog.component.ts, projects/aca-content/src/lib/components/search/search-save/dialog/save-search-dialog.component.ts, projects/aca-content/src/lib/components/search/search-save/dialog/saved-search-form.interface.ts
Form might be initialized https://hyland.atlassian.net/browse/ACS-9008, after the fix form is always initialized when the validator is injected.
=> [ACS-9008] Proper form initialization for Saved Searches

extension.schema.json, projects/aca-content/src/lib/components/search/search-save/dialog/unique-search-name-validator.spec.ts, projects/aca-content/src/lib/components/search/search-save/dialog/unique-search-name-validator.ts, projects/aca-content/src/lib/components/search/search-save/list/smart-list/saved-searches-list-schema.ts, projects/aca-content/src/lib/components/search/search-save/sidenav/save-search-sidenav.component.spec.ts, projects/aca-content/src/lib/components/search/search-save/sidenav/save-search-sidenav.component.ts, projects/aca-content/src/lib/components/sidenav/sidenav.component.scss
Add text truncation in saved searches description column, added missing docs in `extension.schema.json` and fixed one small bug in unique saved search name validator. 
https://hyland.atlassian.net/browse/ACS-9012
=> [ACS-9012] Truncate text in saved searches description

projects/aca-content/src/lib/services/content-management.service.ts, projects/aca-content/src/lib/store/effects/node.effects.spec.ts, projects/aca-content/src/lib/store/effects/node.effects.ts, projects/aca-shared/store/src/actions/node.actions.ts
Part of the changes required for https://hyland.atlassian.net/browse/ACS-8604
=> [ACS-8604] Add new param to control undo for deleting nodes

projects/aca-shared/src/lib/services/app.service.spec.ts, projects/aca-shared/src/lib/services/app.service.ts
https://hyland.atlassian.net/browse/ACS-8961
expandedSidenav is removed from local storage upon logout
=> [ACS-8961] Remove expandedSidenav from local storage upon logout

projects/aca-content/src/lib/components/toolbar/toggle-join-library/toggle-join-library-menu.component.ts
https://hyland.atlassian.net/browse/ACS-8902
Fixed issue where Join library option was showing incorrect icon in the context menu
=> [ACS-8902] Fixed incorrect icon for join library option

projects/aca-content/assets/app.extensions.json, projects/aca-content/assets/i18n/en.json, projects/aca-content/src/lib/dialogs/folder-details/folder-information.component.html, projects/aca-content/src/lib/dialogs/folder-details/folder-information.component.scss, projects/aca-content/src/lib/dialogs/folder-details/folder-information.component.spec.ts, projects/aca-content/src/lib/dialogs/folder-details/folder-information.component.ts, projects/aca-content/src/lib/services/content-management.service.spec.ts, projects/aca-content/src/lib/services/content-management.service.ts, projects/aca-content/src/lib/store/effects/node.effects.spec.ts, projects/aca-content/src/lib/store/effects/node.effects.ts, projects/aca-shared/store/src/actions/node.actions.ts
https://hyland.atlassian.net/browse/MNT-24575
Added new dialog accessible via context menu to display folder information such as folder location, size, file count etc
=> [MNT-24575] Added dialog to display folder information

projects/aca-content/folder-rules/src/rule-list/rule-list-item/rule-list-item.ui-component.ts, projects/aca-content/folder-rules/src/rule-list/rule-list/rule-list.ui-component.ts, projects/aca-content/src/lib/components/dl-custom-components/datatable-cell-badges/datatable-cell-badges.component.ts, projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.ts, projects/aca-content/src/lib/components/sidenav/components/button-menu.component.ts, projects/aca-content/src/lib/components/sidenav/components/expand-menu.component.ts, projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts, projects/aca-shared/src/lib/components/toolbar/toolbar.component.ts
https://hyland.atlassian.net/browse/ACS-8960
=> [ACS-8960] Review and apply required inputs where possible

.github/actions/run-e2e-playwright/action.yml, e2e/playwright/edit-actions/exclude.tests.json, e2e/playwright/info-drawer/src/tests/file-folder-properties.e2e.ts, e2e/playwright/info-drawer/src/tests/library-properties.e2e.ts, e2e/playwright/list-views/exclude.tests.json, e2e/playwright/search/exclude.tests.json, e2e/playwright/viewer/exclude.tests.json, e2e/playwright/viewer/src/tests/viewer-action.e2e.ts, projects/aca-playwright-shared/src/page-objects/components/dialogs/content-node-selector-dialog.ts, projects/aca-playwright-shared/src/page-objects/components/dialogs/link-rules.component.ts, projects/aca-playwright-shared/src/page-objects/components/manageRules/manage-rules.component.ts
https://hyland.atlassian.net/browse/ACS-9154
=> [ACS-9154] Fix unstable tests in ACA after migration to local ACS

projects/aca-content/src/lib/utils/aca-search-utils.ts
https://hyland.atlassian.net/browse/AAE-30880
Removing usage of a CommonJS module distributed package buffer, which prevents proper usage of ESModule based bundlers and tools
=> AAE-30880 Remove usage of commonjs buffer package

docs/extending/rules.md, projects/aca-content/assets/app.extensions.json, projects/aca-content/src/lib/aca-content.module.ts, projects/aca-content/src/lib/components/details/details.component.spec.ts, projects/aca-content/src/lib/components/details/details.component.ts, projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/rules/src/app.rules.ts, projects/aca-shared/rules/src/navigation.rules.spec.ts, projects/aca-shared/rules/src/navigation.rules.ts
https://hyland.atlassian.net/browse/ACS-9158
The "View Details" button has been removed from the Details page because the button's logic causes the page to redirect on refresh and the link cannot be accessed directly. At the same time "Reduce panel" button is retained and performs the same action.
=> [ACS-9158] Remove 'View Details' button from node Details page

projects/aca-content/src/lib/components/files/files.component.spec.ts, projects/aca-content/viewer/src/lib/components/preview/preview.component.spec.ts
[ACS-9536 Unit tests are randomly failing sometimes on ACA](https://hyland.atlassian.net/browse/ACS-9536)
- Reset overridden selectors affecting global store state
- Use correct testing module in other suite
- Run tests locally multiple times
- Run tests on PR workflow multiple times
[5 attempts of Test All step skipping cache](https://github.com/Alfresco/alfresco-content-app/actions/runs/14907556727)
=> [ACS-9536] fix failing unit tests

docs/extending/rules-list.md, projects/aca-content/assets/app.extensions.json, projects/aca-content/src/lib/aca-content.module.ts, projects/aca-content/src/lib/components/search/search-results/search-results.component.html, projects/aca-content/src/lib/components/search/search-results/search-results.component.spec.ts, projects/aca-content/src/lib/components/search/search-results/search-results.component.ts, projects/aca-content/src/lib/pipes/is-feature-supported.pipe.spec.ts, projects/aca-content/src/lib/pipes/is-feature-supported.pipe.ts, projects/aca-content/src/public-api.ts, projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/rules/src/app.rules.ts, projects/aca-shared/src/lib/services/app.extension.service.spec.ts, projects/aca-shared/src/lib/services/app.extension.service.ts
https://hyland.atlassian.net/browse/ACS-10035
25.08 UPD:
- utilizing existing rules/extensions mechanism for managing supported version;
- adds new evaluator with helper functions
- adds pipe as alternative approach for hiding components
- extends AppExtensionService to support manual evaluator call
introduces:
1. AcsVersionManagerService: checks minimal version with current
2. IsFeatureAvailablePipe
4. configuration-based approach adding "acs-version-manger" prop in app.config
=> [ACS-10035] Ensure ADW handles no PUT for preferences API method in ACS below 25.x v. [PoC]
