.editorconfig, .travis.yml
Pushes images to [Docker Hub](https://hub.docker.com/r/denysvuika/alfresco-content-app/tags/)
- uses "latest" tag for master branch
- user branch name tag for all branches and PRs
Example:
```sh
docker container run -p 3000:80 --rm denysvuika/alfresco-content-app:dev-denys-dockerhub
```
=> Docker Hub integration

.travis.yml, karma.conf.js
Use headless Chrome for local and CI runs.
=> headless chrome for unit tests

src/app/app.routes.ts, src/app/components/favorites/favorites.component.spec.ts, src/app/components/favorites/favorites.component.ts, src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts, src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.ts, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/recent-files/recent-files.component.ts, src/app/components/search/search.component.spec.ts, src/app/components/search/search.component.ts, src/app/components/shared-files/shared-files.component.spec.ts, src/app/components/shared-files/shared-files.component.ts
Reverts Alfresco/alfresco-content-app#170 due to the issues with opening files
=> Revert "[ACA] Preview files child route"

src/app/app.routes.ts, src/app/components/favorites/favorites.component.spec.ts, src/app/components/favorites/favorites.component.ts, src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts, src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.ts, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/recent-files/recent-files.component.ts, src/app/components/search/search.component.spec.ts, src/app/components/search/search.component.ts, src/app/components/shared-files/shared-files.component.spec.ts, src/app/components/shared-files/shared-files.component.ts
=> [ACA-1066] Improved files preview

README.md
developer readme gets a reference to JIRA board
=> [ACA-1064] readme update

src/app/common/services/node-actions.service.spec.ts, src/app/common/services/node-actions.service.ts, src/assets/i18n/en.json, src/assets/i18n/fr.json
translate title taking into consideration also multiple selections for copy/move action
=> [ACA-1091] Destination picker is not completely translated [ADF-2000]

package-lock.json, package.json, src/app/app.routes.ts, src/app/components/favorites/favorites.component.html, src/app/components/favorites/favorites.component.ts, src/app/components/files/files.component.html, src/app/components/files/files.component.ts, src/app/components/libraries/libraries.component.html, src/app/components/libraries/libraries.component.ts, src/app/components/page.component.ts, src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.spec.ts, src/app/components/preview/preview.component.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/recent-files/recent-files.component.ts, src/app/components/shared-files/shared-files.component.html, src/app/components/shared-files/shared-files.component.ts, src/app/components/trashcan/trashcan.component.html, src/app/components/trashcan/trashcan.component.ts, yarn.lock
- next/prev navigation for the Viewer
- fix issue with URL incorrectly changed when going back from the Viewer in the "root" of the personal files
- save and restore sorting settings
=> [ACA-1078] next/prev navigation for the Viewer

src/app/common/services/node-actions.service.ts
same changes as those for fixing [ADF-2077]
=> [ACA-1053] [Destination picker] User should not be able to copy / move items into a site outside of the documentLibrary

src/app/common/services/node-actions.service.ts
added a breadcrumbTransform function to customize the display of the breadcrumb as needed
used a similar approach as on page breadcrumb
=> [ACA-863][Destination picker] User can see the entire repository by using the breadcrumb instead of just his Personal Files

src/app/common/services/content-management.service.ts, src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.spec.ts, src/app/components/preview/preview.component.ts, src/app/ui/overrides/_alfresco-document-list.scss
- Favorite action
- Copy action
- Move action
- Delete action
=> [ACA-99] Viewer actions

src/app/components/trashcan/trashcan.component.html
=> [ACA-1161] Incorrect title for trashcan empty page

src/app/common/services/node-actions.service.spec.ts, src/app/common/services/node-actions.service.ts, src/assets/i18n/en.json
Fixed issue https://issues.alfresco.com/jira/browse/ACA-1162
=> [ACA-1162] Destination picker has incorrect title when opened for multiple selection of items

.travis.yml, docs/docker.md
- use port 8080 for public images
- update travis config
=> docker setup fixes for public images

src/app/common/services/node-actions.service.ts
fixes https://issues.alfresco.com/jira/browse/ACA-1146
=> [ACA-1146] The main node of the breadcrumb is not displayed in File Libraries

src/app/common/services/node-actions.service.ts
fix for https://issues.alfresco.com/jira/browse/ACA-1169
=> [ACA-1169] Default location of the copy/move file is not displayed

package-lock.json, package.json
To be able to test/move to 'Done' some of the issues dependent on recent ADF changes.
=> [ACA-1211] upgrade to latest ADF alpha

scripts/update-version.sh
This script can automatically update the version of ADF
=> update version script

scripts/update-version.sh
fix missing js-api update script
=> fix update script

src/tsconfig.app.json, src/tsconfig.spec.json, tsconfig.json
- remove node_modules from the typescript compilation
=> improved typescript configuration files

package-lock.json, package.json
- upgrade to latest ADF alpha that has AoT fixes needed for ACA
=> [ACA-1229] update to latest ADF alpha

src/app/components/adf-layout/layout-container.component.scss, src/app/components/adf-layout/sidenav-layout.component.scss, src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/libraries/libraries.component.html, src/app/components/recent-files/recent-files.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html, src/app/ui/_layout.scss, src/app/ui/application.scss, src/app/ui/mixins.scss, src/app/ui/overrides/_adf-login.scss, src/app/ui/overrides/_alfresco-document-list.scss, src/app/ui/overrides/_alfresco-upload-drag-area.scss
=> [ACA-1245] Document List - pagination is missing

CONTRIBUTING.md
initial contributing guide, based on the Angular one
=> [ACA-1218] contributing guide

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
- template for new issues
- template for new pull requests
=> [ACA-1281] templates for new issue/pr

src/app/common/directives/node-permanent-delete.directive.spec.ts, src/app/common/directives/node-permanent-delete.directive.ts, src/assets/i18n/en.json
- add confirmation dialog for permanent deletion from trash
=> [ACA-1270] confirm permanent deletion

src/app/ui/_layout.scss
=> [ACA-1284] layout style fixes

src/app/common/directives/node-versions.directive.ts
fix bug - made sure to always get the allowableOperations for selected node
=> [ACA-1308] User can't upload a new version for a document in "Favorites" view list from the drop down menu

Dockerfile, scripts/update-version.sh
- fix the upgrade script
- add maintainer/version labels for the dockerfile
=> upgrade script and dockerfile polishing

src/app/app.module.ts, src/app/common/directives/node-download.directive.ts, src/app/components/shared-files/shared-files.component.html
- workaround for node download directive
=> [ACA-1321] workaround for downloading shared files

src/assets/i18n/en.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> [ACA-1320] Metadata - edit fields actions tooltips text

src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/sidenav/sidenav.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> [ACA] New Folder - tooltip fix

e2e/suites/actions/toolbar-single-selection.test.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] E2E - Toolbar - wait for shared api

src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts, src/app/components/libraries/libraries.component.html, src/app/components/page.component.spec.ts, src/app/components/page.component.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html, src/app/ui/overrides/_alfresco-document-list.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> [ACA-1328] Use ADF Pagination in Personal Files and Libraries

e2e/suites/actions/toolbar-single-selection.test.ts, package-lock.json, package.json, src/app.config.json, src/app/components/search/search.component.html, src/app/components/search/search.component.ts
```
[ ] Bugfix
[ ] Feature
```
Upgrade to latest ADF (alpha)
```
[ ] Yes
[ ] No
```
=> upgrade to latest ADF alpha

src/app/ui/theme.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] fix font

src/app/components/favorites/favorites.component.html, src/app/components/libraries/libraries.component.html, src/app/components/recent-files/recent-files.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1369] Document List - empty state renders tooltip

src/app/components/files/files.component.html, src/app/components/recent-files/recent-files.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1359] Permissions - Consumer can't access "Manage versions" from toolbar

src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/page.component.spec.ts, src/app/components/page.component.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/recent-files/recent-files.component.ts, src/app/components/shared-files/shared-files.component.html
- [] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1370] Use permission service over component methods

src/app/components/files/files.component.html, src/app/components/recent-files/recent-files.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Metadata - node reference

package-lock.json, package.json, src/app/app.component.ts, src/app/app.module.ts, src/app/components/sidenav/sidenav.component.html, src/app/components/sidenav/sidenav.component.spec.ts, src/app/components/sidenav/sidenav.component.ts
```
[ ] Bugfix
[x] Feature
```
Lightweight integration with Electron:
- seamless integration with the Electron builds, does not require code changes anymore
- detects if running within Electron app shell and uses different "Upload Folder" technique (controlled by the app shell and direct file system access)
- allows to upload files coming from the app shell, Upload Dialog integration
- allows navigating to …
=> core electron integration

.gitignore, package.json, src/app/app.module.ts, src/app/app.routes.ts, src/app/common/services/hybrid-app-config.service.ts, src/app/components/settings/settings.component.html, src/app/components/settings/settings.component.scss, src/app/components/settings/settings.component.ts, src/assets/i18n/en.json
```
[ ] Bugfix
[x] Feature
```
Provides internal settings dialog that can be invoked from desktop apps,
and allows changing repository address without modifying application config.
```
[ ] Yes
[x] No
```
=> [desktop] settings dialog

.circleci/config.yml, .travis.yml, cspell.json, e2e/suites/actions/mark-favorite.test.ts, e2e/suites/actions/toolbar-single-selection.test.ts, e2e/suites/authentication/login.test.ts, e2e/suites/navigation/breadcrumb.test.ts, e2e/utilities/reporters/console/console-logger.ts, e2e/utilities/reporters/console/console.ts, package-lock.json, package.json, src/app/common/directives/node-delete.directive.ts, src/app/common/directives/node-restore.directive.ts, src/app/common/services/node-actions.service.spec.ts
```
[ ] Bugfix
[ ] Feature
```
- spellcheck step for the CI/CD
```
[ ] Yes
[x] No
```
=> [ACA-1390] add spellcheck for the typescript code

src/app/app.module.ts, src/app/components/layout/layout.component.html, src/app/components/layout/layout.component.spec.ts, src/app/components/layout/layout.component.ts, src/app/components/layout/sidenav-views-manager.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1401] Collapse Side Nav in Search

src/app/ui/_layout.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Info Panel - consisten width

src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/header/header.component.html, src/app/components/header/header.component.spec.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/sidenav/sidenav.component.html, src/app/ui/application.scss, src/app/ui/overrides/_toolbar.scss, src/assets/i18n/en.json, src/index.html
```
[ ] Bugfix
[ ] Feature
```
- remove workarounds for toolbar
- prepare the toolbar styles for future contribution to ADF
```
[ ] Yes
[x] No
```
=> cleanup toolbar styles

e2e/suites/navigation/breadcrumb.test.ts, package-lock.json, package.json, src/app/components/header/header.component.html
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
- upgrade to latest ADF alpha
- restore breadcrumb e2e tests
```
[ ] Yes
[x] No
```
=> upgrade libs

src/app/components/favorites/favorites.component.ts, src/app/components/libraries/libraries.component.spec.ts, src/app/components/libraries/libraries.component.ts, src/app/components/page.component.spec.ts, src/app/components/page.component.ts, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/recent-files/recent-files.component.ts, src/app/components/shared-files/shared-files.component.spec.ts, src/app/components/shared-files/shared-files.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Page component - remove fetchNodes

src/app.config.json, src/assets/i18n/en.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-118] Search - Filters

src/app/components/search/search.component.html, src/app/components/search/search.component.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Search - empty state

src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/libraries/libraries.component.html, src/app/components/recent-files/recent-files.component.html, src/app/components/search/search.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html, src/app/ui/overrides/_alfresco-document-list.scss
```
[ ] Bugfix
[ ] Feature
```
- remove styles that were previously moved to ADF
```
[ ] Yes
[x] No
```
=> [ACA] remove obsolete style style from document list

src/app/app.routes.ts, src/app/components/search/search.component.html, src/app/components/search/search.component.scss, src/app/components/search/search.component.ts, src/assets/i18n/en.json
```
[ ] Bugfix
[ ] Feature
```
covers some of the AC of https://issues.alfresco.com/jira/browse/ACA-117
```
[ ] Yes
[x] No
```
=> [ACA-1406] search results -  part 1

src/app/components/preview/preview.component.spec.ts, src/app/components/preview/preview.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1426] Search - back from preview breaks view

src/app/components/search/search.component.html, src/app/components/search/search.component.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1429] Search - chip list misaligned

src/app/app.module.ts, src/app/app.routes.ts, src/app/components/favorites/favorites.component.html, src/app/components/favorites/favorites.component.spec.ts, src/app/components/favorites/favorites.component.ts, src/app/components/files/files.component.html, src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts, src/app/components/libraries/libraries.component.html, src/app/components/libraries/libraries.component.spec.ts, src/app/components/libraries/libraries.component.ts, src/app/components/page.component.spec.ts, src/app/components/page.component.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/recent-files/recent-files.component.ts, src/app/components/shared-files/shared-files.component.html, src/app/components/shared-files/shared-files.component.spec.ts, src/app/components/shared-files/shared-files.component.ts, src/app/components/trashcan/trashcan.component.html, src/app/components/trashcan/trashcan.component.spec.ts, src/app/components/trashcan/trashcan.component.ts, src/app/directives/sorting-preference-key.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> imporove sorting management and reduce repetitive code

.circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
- merge `install` and `test` tasks
- `test` comes first now
```
[ ] Yes
[x] No
```
=> improved build workflow

src/app/common/directives/node-copy.directive.ts, src/app/common/directives/node-delete.directive.ts, src/app/common/directives/node-move.directive.ts, src/app/common/directives/node-permanent-delete.directive.spec.ts, src/app/common/directives/node-permanent-delete.directive.ts, src/app/common/directives/node-restore.directive.spec.ts, src/app/common/directives/node-restore.directive.ts, src/app/common/directives/node-versions.directive.ts
```
[ ] Bugfix
[ ] Feature
```
use instant translation where possible
```
[ ] Yes
[x] No
```
=> use instant translation

.circleci/config.yml, docker-compose.yml, e2e/suites/actions/delete.test.ts, package.json, protractor.conf.js
```
[ ] Bugfix
[ ] Feature
```
Use port 4000 for e2e runs. That allows the following features at the same time:
- run original app at port 4200 with 6.0 containers
- run demo shell at port 3000 with 6.0 containers
- run e2e tests at 4000 with 6.0 containers
```
[ ] Yes
[x] No
```
=> use port 4000 for e2e runs

src/app/common/directives/node-versions.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1438] Viewer - Manage version dialog is not displayed

package-lock.json, package.json, src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/libraries/libraries.component.html, src/app/components/recent-files/recent-files.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html
```
[x] Bugfix
[ ] Feature
```
Issue Number: ACA-1433
- update to latest ADF alpha (fixes issue with Viewer titles, ACA-1433)
- update include fields to use `isFavorite` if running against ACS 6.0 (rest is handled by the code in the latest ADF alpha)
```
[ ] Yes
[x] No
```
=> [ACA-1433] upgrade ADF libs and code

src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/page.component.spec.ts, src/app/components/page.component.ts, src/app/components/recent-files/recent-files.component.html
```
[x] Bugfix
[ ] Feature
```
Issue Number: ACA-1439
single selection items now require 1 selection only
```
[ ] Yes
[x] No
```
=> [ACA-1439] Resolve multi-select issues

src/app/components/info-drawer/info-drawer.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1446] Favorite List - upload new version disabled

src/app/app.module.ts, src/app/common/services/page-title.service.ts
```
[x] Bugfix
[ ] Feature
```
Fix Page Title service, add an extra monitor for language files changes to re-evaluate the title if translation is split into multiple json files and the one needed for the title is not yet loaded.
```
[ ] Yes
[x] No
```
=> [ACA-1372] fix page title service

src/app/app.module.ts, src/app/components/files/files.component.ts, src/app/components/search/search.component.html, src/app/components/search/search.component.ts, src/app/directives/download-nodes.directive.ts, src/app/store/actions/node.action.ts, src/app/store/actions/router.action.ts, src/app/store/effects/download.effects.ts, src/app/store/effects/router.effects.ts, src/app/ui/overrides/_alfresco-document-list.scss
```
[ ] Bugfix
[x] Feature
```
- new single/multi-select actions for search results
```
[ ] Yes
[x] No
```
=> [ACA-1379] Search Results Actions and Bulk Actions

src/app/common/directives/node-versions.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1446] Favorite - Version Manager dialog

src/app/components/location-link/location-link.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Location cell component - use navigation @effect

src/app/app.module.ts, src/app/components/favorites/favorites.component.spec.ts, src/app/components/favorites/favorites.component.ts, src/app/components/files/files.component.html, src/app/components/files/files.component.spec.ts, src/app/components/files/files.component.ts, src/app/components/libraries/libraries.component.ts, src/app/components/page.component.spec.ts, src/app/components/page.component.ts, src/app/components/preview/preview.component.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/recent-files/recent-files.component.ts, src/app/components/search/search.component.html, src/app/components/search/search.component.ts, src/app/components/shared-files/shared-files.component.html, src/app/components/shared-files/shared-files.component.spec.ts, src/app/components/shared-files/shared-files.component.ts, src/app/components/trashcan/trashcan.component.ts, src/app/store/actions/node.action.ts, src/app/store/actions/viewer.action.ts, src/app/store/effects/viewer.effects.ts
```
[x] Bugfix
[ ] Feature
```
- universal viewer effect to show file viewer from various places
- fix issues with missing viewer actions (toolbar)
- remove some of the tests addressing old behaviour
```
[ ] Yes
[x] No
```
=> [ACA-1455] universal Viewer @effect

src/app/components/search/search.component.html, src/app/components/search/search.component.ts
```
[x] Bugfix
[ ] Feature
```
- search results page has control over the query format
- support for changing query builder from code
```
[ ] Yes
[x] No
```
=> search result fixes

src/app.config.json, src/app/app.module.ts, src/app/components/custom-dl-row/custom-dl-row.component.html, src/app/components/custom-dl-row/custom-dl-row.component.scss, src/app/components/custom-dl-row/custom-dl-row.component.ts, src/app/components/location-link/location-link.component.ts, src/app/components/search/search.component.html, src/assets/i18n/en.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1437] Custom row for search results DL

src/app/components/custom-dl-row/custom-dl-row.component.html, src/app/components/custom-dl-row/custom-dl-row.component.ts, src/assets/i18n/en.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1437] Search - size data

src/app/components/search/search.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1437] Search - row db click navigation

src/app.config.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Search - enable repository search

src/app/components/page.component.ts, src/assets/i18n/en.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Upload - 500 error message

src/app/components/sidenav/sidenav.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1302] Sidenav - 'New' button tooltip

src/app/components/favorites/favorites.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1468] Favorite - unable to navigate into folder

src/app/app.component.ts, src/app/components/search-input/search-input.component.scss, src/app/ui/overrides/adf-document-list.theme.scss
```
[ ] Bugfix
[ ] Feature
```
- remove old workarounds for code/css related to old ADF versions
```
[ ] Yes
[ ] No
```
=> remove old workarounds

src/app/components/location-link/location-link.component.ts, src/app/components/search-input/search-input.component.spec.ts, src/app/components/search-input/search-input.component.ts, src/app/components/search/search.component.ts, src/app/store/actions.ts, src/app/store/actions/router.actions.ts, src/app/store/actions/search.actions.ts, src/app/store/actions/viewer.actions.ts, src/app/store/app-store.module.ts, src/app/store/effects/router.effects.ts, src/app/store/effects/search.effects.ts, src/app/store/effects/viewer.effects.ts, src/app/testing/app-testing.module.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: ACA-1473
- open double-clicked folder from search results
- extra actions/effects for navigating to folder or parent
- 'search by term' action and effect
- unit test updates
```
[ ] Yes
[x] No
```
=> [ACA-1473] fixes for navigation to searched folder

src/app/dialogs/node-versions/node-versions.dialog.theme.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1463-1464-1465] Version Manager - dialog style

src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/page.component.spec.ts, src/app/components/page.component.ts, src/app/components/preview/preview.component.html, src/app/components/recent-files/recent-files.component.html, src/app/components/search/search.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html, src/app/store/reducers/app.reducer.ts, src/app/store/selectors/app.selectors.ts, src/app/store/states/app.state.ts, src/app/store/states/selection.state.ts
```
[ ] Bugfix
[ ] Feature
```
Right now we need to calculate various selection-related properties in the base page component.
This approach does not scale when having multiple components/directives.
- unified selection state
- app reducer evaluates all the properties on the fly
```
[ ] Yes
[x] No
```
=> unified selection state

src/app/components/sidenav/sidenav.component.html, src/assets/i18n/en.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1302] Sidenav - New button tooltip

src/app/components/trashcan/trashcan.component.html, src/app/components/trashcan/trashcan.component.spec.ts, src/app/components/trashcan/trashcan.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-452] Trash - conditional Deleted By column

src/app/app.module.ts, src/app/components/search-input-control/search-input-control.component.html, src/app/components/search-input-control/search-input-control.component.scss, src/app/components/search-input-control/search-input-control.component.ts, src/app/components/search-input/search-input.component.html, src/app/components/search-input/search-input.component.ts, src/app/components/search/search.component.ts
```
[ ] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ACA-1451
```
[ ] Yes
[x] No
```
=> [ACA-1451] search input component

src/app/app.module.ts, src/app/material.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> extract material libs to a separate module

src/app/components/search/search.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1481] Search - toolbar actions missing on selections

src/app/components/custom-dl-row/custom-dl-row.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1480] Search - preview files redirects user

src/app/components/files/files.component.ts
```
[x] Bugfix
[ ] Feature
```
Apply debouncing for document list reloads 
```
[ ] Yes
[x] No
```
=> [ACA-1482] debounce list reloads upon upload

src/app/app.component.ts
```
[x] Bugfix
[ ] Feature
```
Redirect to Login if reloading the page with the expired ticket.
```
[ ] Yes
[x] No
```
=> redirect to login when reloading page with expired ticket

e2e/suites/actions/toolbar-single-selection.test.ts, src/app.config.json, src/app/common/directives/node-restore.directive.ts, src/app/common/services/content-management.service.ts, src/app/components/libraries/libraries.component.html, src/app/components/libraries/libraries.component.spec.ts, src/app/components/libraries/libraries.component.ts, src/app/store/actions/library.actions.ts, src/app/store/app-store.module.ts, src/app/store/effects.ts, src/app/store/effects/library.effects.ts, src/assets/i18n/en.json
```
[ ] Bugfix
[x] Feature
```
Effects and Actions for "Libraries":
- delete library (no undo for now)
- restore deleted library and navigate there
```
[ ] Yes
[x] No
```
=> library effects and actions

src/app/app.component.ts, src/app/components/current-user/current-user.component.html, src/app/components/current-user/current-user.component.ts, src/app/store/actions/app.actions.ts, src/app/store/app-store.module.ts, src/app/store/reducers/app.reducer.ts, src/app/store/selectors/app.selectors.ts, src/app/store/states.ts, src/app/store/states/app.state.ts
```
[ ] Bugfix
[ ] Feature
```
- simplify "current user" component code (use async pipes that know how to unsubscribe)
- simplify store selector definitions
```
[ ] Yes
[x] No
```
=> simplify user component

src/app/components/search/search.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Search - pagination options

src/app.config.json, src/app/components/libraries/libraries.component.html, src/app/components/settings/settings.component.html, src/app/components/settings/settings.component.ts, src/app/directives/experimental.directive.ts, src/assets/i18n/en.json
```
[ ] Bugfix
[x] Feature
```
- toggle "Language Picker" from the settings panel
- toggle "experimental libraries" from the settings panel
```
[ ] Yes
[x] No
```
=> settings enhancements

src/app/components/files/files.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> [ACA-1484] improve reload on upload

package-lock.json, package.json, src/app/app.component.ts, src/app/app.module.ts, src/app/components/sidenav/sidenav.component.html, src/app/components/sidenav/sidenav.component.spec.ts, src/app/components/sidenav/sidenav.component.ts, src/app/components/trashcan/trashcan.component.spec.ts, src/app/material.module.ts, src/app/testing/app-testing.module.ts
```
[ ] Bugfix
[ ] Feature
```
- remove old electron integration demo
```
[ ] Yes
[x] No
```
=> remove electron demo code

src/app/common/directives/node-copy.directive.spec.ts, src/app/common/directives/node-delete.directive.spec.ts, src/app/common/directives/node-move.directive.spec.ts, src/app/common/directives/node-move.directive.ts, src/app/common/directives/node-permanent-delete.directive.spec.ts, src/app/common/directives/node-restore.directive.spec.ts, src/app/components/favorites/favorites.component.spec.ts, src/app/components/files/files.component.spec.ts, src/app/components/header/header.component.spec.ts, src/app/components/layout/layout.component.spec.ts, src/app/components/libraries/libraries.component.spec.ts, src/app/components/login/login.component.spec.ts, src/app/components/preview/preview.component.spec.ts, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/shared-files/shared-files.component.spec.ts, src/app/components/sidenav/sidenav.component.spec.ts, src/app/components/trashcan/trashcan.component.spec.ts, src/app/testing/app-testing.module.ts, src/app/testing/translation.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> unit test cleanup

src/app.config.json, src/assets/i18n/en.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1476, ACA-1477]search sorting options

src/app/components/search-input-control/search-input-control.component.html, src/app/components/search-input/search-input.component.theme.scss
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ACA-1485
```
[ ] Yes
[x] No
```
=> [ACA-1485] use SearchTriggerDirective only when liveSearchEnabled

src/app/components/search-input/search-input.component.ts, src/app/components/search/search.component.html, src/app/components/search/search.component.scss, src/app/components/search/search.component.ts
```
[ ] Bugfix
[ ] Feature
```
Please see https://issues.alfresco.com/jira/browse/ACA-1489
```
[ ] Yes
[x] No
```
=> [ACA-1489] Handling cleared searches and searches with no results

src/app.config.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] App config - use correct file name to exclude

docs/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> documentation update

docs/getting-started.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> Documentation - fix broken links

src/app/components/search/search.component.ts
```
[x] Bugfix
[ ] Feature
```
Workaround for resetting the checkboxes in ADF 2.4.0
```
[ ] Yes
[x] No
```
=> [ACA-1495] workaround for search settings reset

src/app/components/search/search.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> hide filter panel when there is no search term in URL

docker-compose.yml, docker-compose/docker-compose.yml
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
upgrade docker setup to 6.0.7-ga (community)
```
[ ] Yes
[x] No
```
=> upgrade images to 6.0.7-ga (community)

src/app/ui/custom-theme.scss, src/app/ui/overrides/adf-content-node-selector.theme.scss, src/app/ui/overrides/adf-document-list.theme.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1501] Node Selector - DL cell flex alignment

src/app/ui/overrides/adf-content-node-selector.theme.scss
```
[x] Bugfix
[ ] Feature
```
Fix styles for breadcrumb when inside the destination picker
```
[ ] Yes
[x] No
```
=> [ACA-1504] fix node selector style for active item

e2e/components/data-table/data-table.ts, src/app/components/custom-dl-row/custom-dl-row.component.html, src/app/components/favorites/favorites.component.html, src/app/components/location-link/location-link.component.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html
```
[x] Bugfix
[ ] Feature
```
- fix sorting for location links
```
[ ] Yes
[x] No
```
=> fix location link sorting

src/app/common/directives/node-copy.directive.spec.ts, src/app/common/directives/node-copy.directive.ts, src/app/common/directives/node-move.directive.spec.ts, src/app/common/directives/node-move.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1500] Node Selector notification style

src/app/components/info-drawer/info-drawer.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1512] Favorite - edit metadata properties not available

cspell.json, src/app/components/info-drawer/info-drawer.component.ts, src/app/directives/document-list.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1513] Metadata - image EXIF option not rendering

src/app/components/about/about.component.html, src/app/components/about/about.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] About - display licence info if available

src/app.config.json
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ACA-1518
```
[ ] Yes
[x] No
```
=> [ACA-1518] search results - file size settings

src/app/common/directives/node-versions.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1523] Shared - User can't upload a new version for his file shared by admin

src/app/components/sidenav/sidenav.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1519] Action menu - ripple effect renders outside constrains 

src/app/components/shared-files/shared-files.component.html, src/app/store/reducers/app.reducer.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1523] Shared - file version manager 

src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/es.json, src/assets/i18n/fr.json, src/assets/i18n/it.json, src/assets/i18n/ja.json, src/assets/i18n/nb.json, src/assets/i18n/nl.json, src/assets/i18n/pt-BR.json, src/assets/i18n/ru.json, src/assets/i18n/zh-CN.json
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ACA-1521
```
[ ] Yes
[x] No
```
=> [ACA-1521] set upload version tooltip text

src/app.config.json, src/app/components/info-drawer/info-drawer.component.html, src/app/components/settings/settings.component.html, src/app/components/settings/settings.component.ts, src/app/directives/experimental.directive.ts, src/assets/i18n/en.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1491] Info Drawer - comments tab

cspell.json, src/app.config.json, src/app/components/favorites/favorites.component.html, src/app/components/favorites/favorites.component.spec.ts, src/app/components/files/files.component.html, src/app/components/files/files.component.spec.ts, src/app/components/libraries/libraries.component.html, src/app/components/page.component.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/settings/settings.component.html, src/app/components/settings/settings.component.ts, src/app/components/shared-files/shared-files.component.html, src/app/components/shared-files/shared-files.component.spec.ts, src/app/components/trashcan/trashcan.component.html, src/app/components/trashcan/trashcan.component.spec.ts, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Experimental feature
https://issues.alfresco.com/jira/browse/ACA-1490
```
[ ] Yes
[x] No
```
=> [ACA-1490] Enable CardView

src/app.config.json, src/app/app.component.ts, src/app/app.module.ts, src/app/app.routes.ts, src/app/common/services/experimental-guard.service.ts, src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/page.component.ts, src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.spec.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/settings/settings.component.html, src/app/components/settings/settings.component.ts, src/app/components/shared-link-view/shared-link-view.component.html, src/app/components/shared-link-view/shared-link-view.component.scss, src/app/components/shared-link-view/shared-link-view.component.ts, src/app/store/actions/app.actions.ts, src/app/store/reducers/app.reducer.ts, src/app/store/selectors/app.selectors.ts, src/app/store/states/app.state.ts, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1115] Quick Share

package-lock.json, package.json, src/app/components/current-user/current-user.component.html, src/app/components/settings/settings.component.html, src/app/components/settings/settings.component.ts, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[x] Feature
```
- settings: automatically edit all new experimental features (adding flag to json is enough)
- settings: only admins can change experimental flags
- admins see extra `About` and `Settings` items in the app menu (profile click)
```
[ ] Yes
[ ] No
```
=> [ACA-1488] admin actions and settings

src/app/components/page.component.ts, src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.ts, src/app/store/actions/node.actions.ts, src/app/store/reducers/app.reducer.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
- Fix the issue with missing `ngOnInit` call in the base class (missing event handlers)
- Use unified info drawer
- Use existing selection management for toolbar items
```
[ ] Yes
[ ] No
```
=> viewer enhancements

src/app.config.json, src/app/app.module.ts, src/app/common/directives/node-permissions.directive.ts, src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/page.component.ts, src/app/components/permission-manager/permissions-manager.component.html, src/app/components/permission-manager/permissions-manager.component.theme.scss, src/app/components/permission-manager/permissions-manager.component.ts, src/app/components/preview/preview.component.html, src/app/components/recent-files/recent-files.component.html, src/app/components/search/search-results/search-results.component.html, src/app/components/shared-files/shared-files.component.html, src/app/dialogs/node-permissions/node-permissions.dialog.html, src/app/dialogs/node-permissions/node-permissions.dialog.ts, src/app/ui/custom-theme.scss, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: experimental feature
```
https://issues.alfresco.com/jira/browse/ACA-1113
```
[ ] Yes
[x] No
```
=> [ACA-1113] Node Permissions - experimental

src/app.config.json, src/app/components/page.component.ts, src/app/components/search/search-input/search-input.component.spec.ts, src/app/components/search/search-input/search-input.component.ts, src/app/components/search/search-results-row/search-results-row.component.ts, src/app/store/actions/viewer.actions.ts, src/app/store/effects/viewer.effects.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: ACA-1532
- Action/Effect for the file Preview 
- example of the Preview command provided by extension (toolbar button)
```
[ ] Yes
[x] No
```
=> [ACA-1532] make Preview command available to extensions

src/app/common/services/experimental-guard.service.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1543] Quick Share - Non-logged user can't see the content of a shared file

src/app.config.json, src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/page.component.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/search/search-results/search-results.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html, src/app/extensions/components/toolbar-action/toolbar-action.component.html, src/app/extensions/components/toolbar-action/toolbar-action.component.ts, src/app/extensions/content-action.extension.ts, src/app/extensions/core.extensions.ts, src/app/extensions/extension.service.ts, src/app/extensions/utils.ts
```
```
```
[ ] Bugfix
[x] Feature
```
- toolbar: support for separators
- toolbar: support for custom menus (evaluate menu items based on targets)
- various code improvements
```
[ ] Yes
[ ] No
```
=> [ACA-1544] extensions: toolbar separators and menus

src/app/extensions/extension.service.spec.ts, src/app/extensions/extension.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
- support multiple selected nodes for permission checks
- code fixes
```
[ ] Yes
[x] No
```
=> extension api: permission fixes

package-lock.json, package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> [ACA-1545] upgrade to latest ADF alpha

src/app/dialogs/library/library.dialog.ts, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1570] Library - notify library ID conflict on create

src/app/common/services/content-management.service.ts, src/app/components/libraries/libraries.component.ts, src/app/dialogs/library/library.dialog.ts, src/app/services/content-api.service.ts, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1571] File library - navigate into library after create process

src/app/app.module.ts, src/app/extensions/actions/action-ref.ts, src/app/extensions/actions/action.service.spec.ts, src/app/extensions/actions/action.service.ts, src/app/extensions/core.extensions.module.ts, src/app/extensions/extension.config.ts, src/app/extensions/extension.service.spec.ts, src/app/extensions/extension.service.ts, src/app/extensions/route-ref.ts, src/app/testing/app-testing.module.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
- actions service to store actions
- allows having non-ngrx implementations if needed
```
[ ] Yes
[x] No
```
=> split extension actions into separate service

src/app/app.module.ts, src/app/app.routes.strategy.ts, src/app/app.routes.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: ACA-1590
- add custom route reuse strategy
- enable route reuse for the Search results
```
[ ] Yes
[x] No
```
https://issues.alfresco.com/jira/browse/ACA-1590
=> [ACA-1590] reuse search results route

src/app/ui/overrides/adf-toolbar.theme.scss
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1587] Viewer - toolbar theme

src/app/components/favorites/favorites.component.html, src/app/components/recent-files/recent-files.component.html, src/app/components/shared-files/shared-files.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1574] DocumentList - single click navigation

src/app/components/search/search-results-row/search-results-row.component.html, src/app/components/search/search-results-row/search-results-row.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1574] Search - DL single click for folders

extension.schema.json, src/app/extensions/extension.config.ts, src/app/extensions/extension.service.spec.ts, src/app/extensions/extension.service.ts, src/assets/app.extensions.json, src/assets/plugins/plugin1.json, src/assets/plugins/plugin2.json
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: ACA-1597
- support for overwriting objects and arrays (by `id` key)
- introduce support for metadata (properties starting with `$` are not merged, i.e. `$schema`)
```
[ ] Yes
[x] No
```
=> [ACA-1597] allow extensions overwrite existing settings 

.circleci/config.yml, .travis.yml, package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> CI settings

.travis.yml
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> travis jobs config

src/app/app.module.ts, src/app/app.routes.ts, src/app/components/about/about.module.ts, src/app/components/info-drawer/info.drawer.module.ts, src/app/components/preview/preview.module.ts, src/app/directives/directives.module.ts, src/app/extensions/core.extensions.module.ts, src/assets/plugins/plugin2.json
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: ACA-1608
- Loads Viewer (and PDF.js) on demand
- The chunks get cached by the browser and re-used later
Savings: development build
```
chunk {about.module} about.module.chunk.js () 30.8 kB  [rendered]
chunk {preview.module} preview.module.chunk.js () 2.72 MB  [rendered]
```
Savings: production build:
```
chunk {0} 1.29bf38e9627a33115347.chunk.js () 14.1 kB  [rendered]
chunk …
```
=> [ACA-1608] lazy loading support for Viewer and About screens

extension.schema.json, src/app/app.component.ts, src/app/extensions/core.extensions.module.ts, src/app/extensions/evaluators/app.evaluators.ts, src/app/extensions/evaluators/core.evaluators.ts, src/app/extensions/rule.extensions.ts, src/app/store/actions/app.actions.ts, src/app/store/effects/router.effects.ts, src/app/store/reducers/app.reducer.ts, src/app/store/states/navigation.state.ts, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[x] Feature
```
- allow chaining rules (parameters now can be other rules with own parameters)
- new "not" (ensures a list of params evaluates to FALSE) and "isTrashcan" evaluators
```
[ ] Yes
[x] No
```
=> chaining rules, "not" evaluator

src/app/app.component.ts, src/app/components/preview/preview.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
fix and issue with redirects back to the original page upon 401 in js-api
```
[ ] Yes
[x] No
```
=> [ACA-1589] fix auth redirects when ticket expires

src/app/components/search/search-results/search-results.component.html, src/app/components/search/search-results/search-results.component.ts, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[x] Feature
```
- Provide search progress indicator
- fix issue with empty search results localisation
```
[ ] Yes
[x] No
```
=> [ACA-1610] search progress indicator

src/app/services/content-api.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
remove extra 'isFavorite' check for 6.0
```
[ ] Yes
[x] No
```
=> fix issue with favorite check in Viewer

src/app/ui/overrides/adf-toolbar.theme.scss
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Viewer - Info Drawer theme thix

extension.schema.json, src/app/components/files/files.component.html, src/app/extensions/action.extensions.ts, src/app/extensions/components/custom-component/custom.component.ts, src/app/extensions/components/custom-component/demo.button.ts, src/app/extensions/components/toolbar-action/toolbar-action.component.html, src/app/extensions/core.extensions.module.ts, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[x] Feature
```
Allow projecting custom components as action elements
```
[ ] Yes
[x] No
```
=> support custom components as action elements

e2e/components/data-table/data-table.ts, e2e/suites/list-views/favorites.test.ts, e2e/suites/list-views/recent-files.test.ts, e2e/suites/list-views/shared-files.test.ts, src/app/components/location-link/location-link.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1595] Location link - reduce HTTP requests for tooltip

src/app/extensions/evaluators/core.evaluators.ts, src/app/extensions/extension.service.ts, src/app/extensions/rule.extensions.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Provide support for rule negation via the `!` prefix:
```
!app.navigation.isTrashcan
```
```
[ ] Yes
[x] No
```
=> support rule negation

src/app.config.json, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1647] Search - change filter facet label to Location

src/app/components/search/search-results-row/search-results-row.component.html, src/app/components/search/search-results-row/search-results-row.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1527] Search - don't show title if its the same with name

cspell.json, e2e/utilities/repo-client/apis/repo-api-new.ts, e2e/utilities/repo-client/apis/shared-links/shared-links-api.ts, e2e/utilities/repo-client/repo-client.ts, package-lock.json, package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-1638
```
[ ] Yes
[ ] No
```
=> [ACA-1638] refactor sharedLinksApi to use alfresco-js-api

src/app/context-menu/context-menu.component.html, src/app/context-menu/context-menu.component.scss, src/app/context-menu/context-menu.component.theme.scss, src/app/context-menu/context-menu.component.ts, src/app/context-menu/context-menu.directive.ts, src/app/context-menu/context-menu.module.ts, src/app/ui/custom-theme.scss
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1614] Context Menu theme

e2e/suites/actions/create-folder.test.ts, e2e/suites/actions/delete-undo-delete.test.ts, e2e/suites/actions/edit-folder.test.ts, e2e/suites/actions/mark-favorite.test.ts, e2e/suites/actions/permanently-delete.test.ts, e2e/suites/actions/restore.test.ts, e2e/suites/actions/toolbar-multiple-selection.test.ts, e2e/suites/actions/toolbar-single-selection.test.ts, e2e/suites/actions/upload-file.test.ts, e2e/suites/authentication/login.test.ts, e2e/suites/authentication/logout.test.ts, e2e/suites/list-views/empty-list.test.ts, e2e/suites/list-views/favorites.test.ts, e2e/suites/list-views/file-libraries.test.ts, e2e/suites/list-views/permissions.test.ts, e2e/suites/list-views/personal-files.test.ts, e2e/suites/list-views/recent-files.test.ts, e2e/suites/list-views/shared-files.test.ts, e2e/suites/list-views/tooltips.test.ts, e2e/suites/list-views/trash.test.ts, e2e/suites/navigation/breadcrumb.test.ts, e2e/suites/pagination/pag-favorites.test.ts, e2e/suites/pagination/pag-personal-files.test.ts, e2e/suites/pagination/pag-recent-files.test.ts, e2e/suites/pagination/pag-shared-files.test.ts, e2e/suites/pagination/pag-trash.test.ts, e2e/utilities/repo-client/apis/people/people-api-models.ts, e2e/utilities/repo-client/apis/people/people-api.ts, e2e/utilities/repo-client/repo-client.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-1634
```
[ ] Yes
[ ] No
```
=> [ACA-1634] update peopleApi to use alfresco-ja-api-node in e2e

e2e/utilities/repo-client/apis/search/search-api.ts, e2e/utilities/repo-client/repo-client.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-1637
```
[ ] Yes
[ ] No
```
=> [ACA-1637] Update searchApi to use alfresco-js-api-node

src/app/components/search/search-input/search-input.component.theme.scss
```
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: fix small styling issue
```
```
[ ] Yes
[x] No
```
=> [ACA-1572] center focus circle on search icon

e2e/utilities/repo-client/apis/search/search-api.ts, e2e/utilities/repo-client/apis/shared-links/shared-links-api.ts, e2e/utilities/repo-client/apis/trashcan/trashcan-api.ts, e2e/utilities/repo-client/repo-client.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-1640
```
[ ] Yes
[ ] No
```
=> [ACA-1640] use alfresco-js-api-node in e2e trashcanApi

e2e/suites/pagination/pag-file-libraries.test.ts, e2e/utilities/repo-client/apis/sites/sites-api.ts
```
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: 
e2e tests
```
Issue Number: ACA-1650
```
[ ] Yes
[ ] No
```
=> [ACA-1650] automate tests for pagination on File Libraries

src/app.config.json
```
```
```
[ ] Bugfix
[ ] Feature
```
facetFields were not displayed
```
[ ] Yes
[x] No
```
=> Show facetFields

cspell.json, docs/README.md, docs/extending.md, docs/getting-started.md, extension.schema.json, src/app/components/context-menu/context-menu.component.ts, src/app/components/page.component.ts, src/app/components/preview/preview.component.html, src/app/extensions/extension.config.ts, src/app/extensions/extension.service.spec.ts, src/app/extensions/extension.service.ts, src/assets/app.extensions.json, src/assets/extension.schema.json, src/assets/plugins/plugin1.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> extensibility docs update

docs/extending.md, extension.schema.json, src/app/components/preview/preview-extension.component.ts, src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.ts, src/app/components/preview/preview.module.ts, src/app/extensions/extension.service.ts, src/app/extensions/viewer.extensions.ts, src/assets/app.extensions.json, src/assets/extension.schema.json
```
```
```
[ ] Bugfix
[x] Feature
```
- viewer extensibility (content views)
- extra docs
```
[ ] Yes
[x] No
```
=> [ACA-1695] viewer extensions

src/app/components/current-user/current-user.component.theme.scss, src/app/ui/overrides/adf-layout-header.theme.scss, src/assets/fonts/muli/muli.css
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1691
```
[ ] Yes
[x] No
```
=> [ACA-1691] logo font fix

src/app/extensions/core.extensions.module.ts, src/app/extensions/extension-element.ts, src/app/extensions/extension-loader.service.ts, src/app/extensions/extension-utils.ts, src/app/extensions/extension.config.ts, src/app/extensions/extension.service.spec.ts, src/app/extensions/extension.service.ts, src/app/extensions/navbar.extensions.ts, src/app/extensions/sidebar.extensions.ts, src/app/testing/app-testing.module.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Refactor extension service, split out utils and loader.
```
[ ] Yes
[x] No
```
=> refactor extenstion layer to simplify testing and maintenance

docs/extending.md
```
```
```
[ ] Bugfix
[ ] Feature
```
- fix routing layout description
- add `Disabling content` section
```
[ ] Yes
[x] No
```
=> [ACA-1699] update extensibilty docs

src/app/components/info-drawer/info-drawer.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> [ADF-1549] add automation helper id

src/app/components/preview/preview.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> [ADF-1695] add automation helper id

e2e/suites/actions/mark-favorite.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1674] Automated tests for "Mark as Favorite" in FileLibraries list view

e2e/components/header/header.ts, e2e/suites/application/page-titles.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
This test was randomly failing: 
```
1) Page titles on Search query Search Results page - [C280413]
- Failed: invalid element state: Element is not currently interactable and may not be manipulated
```
```
[ ] Yes
[ ] No
```
=> e2e fix random failing test

Dockerfile, docker-compose.yml, src/app/components/context-menu/context-menu-outside-event.directive.ts, src/app/components/context-menu/context-menu.component.html, src/app/components/context-menu/context-menu.component.ts, src/app/components/context-menu/context-menu.directive.ts, src/app/components/context-menu/context-menu.module.ts, src/app/components/context-menu/context-menu.service.ts, src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/libraries/libraries.component.html, src/app/components/recent-files/recent-files.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1696] contextmenu

src/app/components/info-drawer/metadata-tab/metadata-tab.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1738] Metadata - edit permission

src/app/components/context-menu/context-menu-outside-event.directive.ts, src/app/components/context-menu/context-menu.directive.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] contextmenu - document click event breaks implementation in FF

src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1741] Viewer - 'Favorite' action on recent and shared files

src/app/components/toolbar/toggle-favorite/toggle-favorite.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1746] Preview - favorite action UI state does not change

src/app/ui/custom-theme.scss, src/app/ui/overrides/adf-version-manager.theme.scss
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1750] Version Manager - override styling

src/app/components/info-drawer/comments-tab/comments-tab.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1753] Comments - allow add comment based on permission

src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1755] Favorites - User can't unfavorite a file opened in viewer

src/app/services/content-management.service.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1749] Favorites - version manager

docker-compose.yml, docker-compose/docker-compose.yml, docker-compose/nginx.conf
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> change share port in docker-compose.yml

.travis.yml, angular.json, package.json, projects/aca-dev-tools/ng-package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
- fix coverage reports
- fix production mode for e2e
```
[ ] Yes
[x] No
```
=> run e2e in production mode

src/app/components/search/search-input-control/search-input-control.component.ts, src/app/components/search/search-input/search-input.component.html, src/app/components/search/search-input/search-input.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ACA-1715
```
[ ] Yes
[x] No
```
=> [ACA-1715] Search popup appears when navigating away from search results

src/app.config.json, src/assets/app.extensions.json
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1771
```
[ ] Yes
[x] No
```
=> [ACA-1771] Remove features that aren't experimental from settings

e2e/components/data-table/data-table.ts, e2e/suites/actions/single-click.test.ts, e2e/suites/actions/toolbar-single-selection.test.ts, protractor.conf.js
automate tests for Single click on item name
add specific methods for single click on item name link
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-1626
```
[ ] Yes
[ ] No
```
=> [ACA-1626] Add tests for Single click on item name

e2e/suites/actions/delete-undo-delete.test.ts
and change to use async / await
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> disable intermittent failing test

e2e/components/data-table/data-table.ts, e2e/suites/actions/context-menu-multiple-selection.test.ts, e2e/suites/actions/context-menu-single-selection.test.ts, e2e/suites/actions/special-permissions-available-actions.test.ts, e2e/suites/actions/toolbar-multiple-selection.test.ts, e2e/suites/actions/toolbar-single-selection.test.ts
- add tests for right click actions
- refactor toolbar actions tests
- move permissions related tests to a separate suite
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-870
```
[ ] Yes
[ ] No
```
=> [ACA-870] add tests for right click actions

e2e/suites/application/general.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
prevent failing test on Bamboo
```
[ ] Yes
[ ] No
```
=> [ACA-1569] wait for dialog to close

src/app/store/effects/node.effects.spec.ts, src/app/store/effects/node.effects.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
unit tests
```
[ ] Yes
[x] No
```
=> unit tests

extension.schema.json, src/app/components/page.component.ts, src/app/components/preview/preview.component.html, src/app/extensions/extension.service.ts, src/assets/app.extensions.json, src/assets/extension.schema.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1802
```
[ ] Yes
[ ] No
```
=> [ACA-1548][ACA-1802] add actions to viewer toolbar via extensions

src/app/app.module.ts, src/app/app.routes.ts, src/app/extensions/core.extensions.module.ts, src/app/guards/auth.guard.ts
```
```
```
[x] Bugfix
[ ] Feature
```
keep redirect url in the address bar so that application survives reloads
```
[ ] Yes
[x] No
```
=> [ACA-1811] redirect url for login

e2e/components/dialog/copy-move-dialog.ts, e2e/suites/viewer/viewer-actions.test.ts, e2e/utilities/repo-client/apis/nodes/nodes-api.ts, e2e/utilities/repo-client/apis/upload/upload-api.ts, e2e/utilities/utils.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-1767
```
[ ] Yes
[ ] No
```
=> [ACA-1767] add viewer actions tests in other list views

src/app.config.json, src/app/app.component.ts
```
```
```
[x] Bugfix
[x] Feature
```
optional configurable base url for shared links, resolves to `ecmHost` if not explicitly defined
```
[ ] Yes
[x] No
```
=> [ACA-1821] configurable base path for shared urls

docker-entrypoint.sh
```
```
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix #653 - fixing issue caused by missing \ in docker entrypoint

e2e/suites/actions/delete-undo-delete.test.ts, src/app.config.json, src/app/components/search/search-results.module.ts, src/app/components/search/search-results/search-results.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
- add additional filter queries
- add missing directives module (enables back the toolbar for selected items)
- add support for configurable search input fields, update default set of fields
```
[ ] Yes
[x] No
```
=> [ACA-1823] search fixes

e2e/suites/actions/delete-undo-delete.test.ts
```
```
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> disable flaky notification tests

package-lock.json, package.json, src/app/app.module.ts, src/app/components/context-menu/context-menu.module.ts, src/app/components/context-menu/context-menu.service.ts, src/app/components/favorites/favorites.module.ts, src/app/components/info-drawer/info.drawer.module.ts, src/app/components/recent-files/recent-files.module.ts, src/app/components/shared-files/shared-files.module.ts, src/app/components/toolbar/toolbar.module.ts, src/app/components/trashcan/trashcan.module.ts, src/app/extensions/core.extensions.module.ts, src/app/extensions/extension.service.ts, src/app/guards/auth.guard.ts, src/app/services/content-api.service.ts, src/app/services/content-management.service.ts, src/app/services/node-actions.service.ts, src/app/services/node-permission.service.ts, src/app/services/profile.resolver.ts, src/app/testing/app-testing.module.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
support for tree-shakable services (Angular 6 feature)
```
[ ] Yes
[x] No
```
=> tree-shakable services

cspell.json, docs/extending.md, e2e/suites/actions/delete-undo-delete.test.ts, extension.schema.json, src/app/app.module.ts, src/app/components/current-user/current-user.component.html, src/app/components/header/header.component.html, src/app/components/header/header.component.ts, src/app/components/header/header.module.ts, src/app/components/layout/layout.component.html, src/app/components/layout/layout.component.ts, src/app/components/toolbar/toolbar-action/toolbar-action.component.html, src/app/components/toolbar/toolbar-action/toolbar-action.component.ts, src/app/components/toolbar/toolbar-button/toolbar-button.component.html, src/app/components/toolbar/toolbar-button/toolbar-button.component.ts, src/app/components/toolbar/toolbar-menu/toolbar-menu.component.html, src/app/components/toolbar/toolbar-menu/toolbar-menu.component.ts, src/app/extensions/extension.service.ts, src/app/store/actions/app.actions.ts, src/app/store/app-store.module.ts, src/app/store/effects/app.effects.ts, src/assets/app.extensions.json, src/assets/extension.schema.json, src/assets/plugins/app.header.json
```
```
```
[ ] Bugfix
[x] Feature
```
- support app header extensions
- logout action
- custom menu example (`app.header.json` plugin)
```
[ ] Yes
[x] No
```
=> [ACA-1809] app header extensions

src/app/app.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
workaround for i18n issue with 3rd party lib
```
[ ] Yes
[x] No
```
=> [ACA-1812] i18n workaround for non-supported langs

e2e/components/menu/menu.ts, e2e/components/toolbar/toolbar.ts, e2e/resources/extensibility-configs/extensions-default.json, e2e/resources/extensibility-configs/viewer-ext.json, e2e/suites/extensions/ext-viewer.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-1797
```
[ ] Yes
[ ] No
```
=> [ACA-1797] add tests for viewer actions extension

e2e/suites/actions/context-menu-multiple-selection.test.ts, e2e/suites/actions/context-menu-single-selection.test.ts, e2e/suites/actions/create-folder.test.ts, e2e/suites/actions/delete-undo-delete.test.ts, e2e/suites/actions/edit-folder.test.ts, e2e/suites/actions/mark-favorite.test.ts, e2e/suites/actions/permanently-delete.test.ts, e2e/suites/actions/restore.test.ts, e2e/suites/actions/single-click.test.ts, e2e/suites/actions/toolbar-multiple-selection.test.ts, e2e/suites/actions/toolbar-single-selection.test.ts, e2e/suites/actions/upload-file.test.ts, e2e/suites/application/general.test.ts, e2e/suites/application/page-titles.test.ts, e2e/suites/authentication/login.test.ts, e2e/suites/authentication/logout.test.ts, e2e/suites/navigation/breadcrumb.test.ts, e2e/suites/navigation/sidebar.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-1759
```
[ ] Yes
[ ] No
```
=> [ACA-1759] use async / await in test suites

e2e/suites/list-views/empty-list.test.ts, e2e/suites/list-views/favorites.test.ts, e2e/suites/list-views/file-libraries.test.ts, e2e/suites/list-views/generic-errors.test.ts, e2e/suites/list-views/permissions.test.ts, e2e/suites/list-views/personal-files.test.ts, e2e/suites/list-views/recent-files.test.ts, e2e/suites/list-views/shared-files.test.ts, e2e/suites/list-views/tooltips.test.ts, e2e/suites/list-views/trash.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1760] use async / await in list-views suite

package-lock.json, package.json, src/app/components/search/search-input-control/search-input-control.component.ts, src/app/components/sidenav/sidenav.component.ts, src/app/store/effects/library.effects.ts, tslint.json
```
```
```
[ ] Bugfix
[ ] Feature
```
- add rxjs linting
- fix lint issues
```
[ ] Yes
[x] No
```
=> rxjs linting

src/app/store/effects/repository.effects.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Share - route permission noop catchError

docs/extending.md
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1550
```
[ ] Yes
[x] No
```
=> [ACA-1814] Documentation on extending the Content Metadata

docs/extending.md
```
```
```
[ ] Bugfix
[ ] Feature
```
minimalistic docs on Dialogs
```
[ ] Yes
[x] No
```
=> [docs] creating dialog actions

extension.schema.json, src/assets/extension.schema.json
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1849 sub-bug of [ACA-1550]
```
[ ] Yes
[x] No
```
=> [ACA-1849] fix json schema

src/app/store/states/app.state.ts
```
```
```
[x] Bugfix
[ ] Feature
```
enable quick share by default until disabled by settings
```
[ ] Yes
[x] No
```
=> [ACA-1857] enable share by default

src/app/components/search/search-results/search-results.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1856
reset skipCount on new search
```
[ ] Yes
[x] No
```
=> [ACA-1856] Pagination in search result is not reset correctly

package-lock.json, package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
update to latest dev tools
```
[ ] Yes
[x] No
```
=> update to latest dev tools extension

src/app/components/layout/layout.component.html, src/app/components/layout/sidenav-views-manager.directive.spec.ts, src/app/components/preview/preview.component.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1841] Hide app menu in preview

e2e/components/header/header.ts, e2e/components/menu/menu.ts, e2e/components/toolbar/toolbar.ts, e2e/configs.ts, e2e/resources/extensibility-configs/header-ext.json, e2e/suites/extensions/ext-header.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1827] add tests for header extension

src/app/components/common/common.module.ts, src/app/components/common/library-name-column/library-name-column.component.spec.ts, src/app/components/common/library-name-column/library-name-column.component.ts, src/app/components/common/library-status-column/library-status-column.component.spec.ts, src/app/components/common/library-status-column/library-status-column.component.ts, src/app/components/common/name-column/name-column.component.spec.ts, src/app/components/common/name-column/name-column.component.ts, src/app/components/common/trashcan-name-column/trashcan-name-column.component.spec.ts, src/app/components/common/trashcan-name-column/trashcan-name-column.component.ts, src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/libraries/libraries.component.html, src/app/components/libraries/libraries.component.spec.ts, src/app/components/libraries/libraries.component.ts, src/app/components/preview/preview.component.spec.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
move custom column templates to separate components
prerequisite for the document list extensibility
```
[ ] Yes
[x] No
```
=> separate column templates from doc list

src/app.config.json, src/assets/i18n/en.json, src/assets/i18n/fr.json
```
```
```
[ ] Bugfix
[ ] Feature
```
temporary change in order to fix ACA-1859
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1859
- facet fields labels are no longer translated - temporary - [ACA-1885](https://issues.alfresco.com/jira/browse/ACA-1885)
- changed some labels to Sentence case instead of Title Case
```
[ ] Yes
[x] No
```
=> [ACA-1859] remove translation for search facet field labels

cspell.json, src/app/app.module.ts, src/app/components/shared/shared.module.ts, src/app/components/shared/toggle-shared/toggle-shared.component.html, src/app/components/shared/toggle-shared/toggle-shared.component.spec.ts, src/app/components/shared/toggle-shared/toggle-shared.component.ts, src/app/components/shared/toggle-shared/toggle-shared.module.ts, src/app/components/toolbar/toolbar-action/toolbar-action.component.ts, src/app/extensions.module.ts, src/app/extensions/core.extensions.module.ts, src/assets/app.extensions.json, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-92] Context Menu - share settings action

src/app/components/about/about.component.html, src/app/components/about/about.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
- move ACA name/version to the top of the page
- remove "commits" link as it never worked before
```
[ ] Yes
[x] No
```
=> cleanup about page

docker-entrypoint.sh, src/app.config.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-174] added support for Docker variables to enable OAUTH for DBP

docker/tomcat/Dockerfile
```
```
```
[ ] Bugfix
[x] Feature
```
use tomcat 8.5 for e2e runs
```
[ ] Yes
[x] No
```
=> use tomcat 8.5 for e2e

docker-compose.yml
```
```
```
[ ] Bugfix
[x] Feature
```
upgrade ACS to 6.1.0-ea
upgrade Share to 6.0.c
upgrade Search Services to 1.2.0
```
[ ] Yes
[x] No
```
=> upgrade docker images

src/app/components/shared/content-node-share/content-node-share.dialog.html, src/app/components/shared/content-node-share/content-node-share.dialog.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Shared Link - date-time picker pass only date

src/app/components/create-menu/create-menu.component.scss, src/app/ui/overrides/adf-upload-button.theme.scss
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1902] styling - remove capitalisation

src/app/components/layout/layout.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1892] Sidenav - close when navigate on mobile

e2e/suites/actions/context-menu-single-selection.test.ts, e2e/suites/actions/special-permissions-available-actions.test.ts, e2e/suites/viewer/viewer-actions.test.ts, src/app/extensions/evaluators/app.evaluators.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Favorite - enable share action

e2e/configs.ts, e2e/resources/extensibility-configs/document-presets-ext.json, e2e/suites/extensions/ext-document-list.test.ts, e2e/suites/extensions/ext-metadata.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
e2e automation testing for document list presets extension
Issue Number: ACA-1900 subtask of https://issues.alfresco.com/jira/browse/ACA-1552
```
[ ] Yes
[x] No
```
=> [ACA-1900][ACA-1552]  Document List extension e2e

e2e/components/dialog/confirm-dialog.ts, e2e/components/dialog/share-dialog.ts, e2e/pages/page.ts, e2e/suites/actions/permanently-delete.test.ts, e2e/suites/actions/share-file.test.ts, e2e/suites/actions/unshare-file.test.ts, e2e/utilities/repo-client/apis/nodes/nodes-api.ts
small other changes
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-1800
```
[ ] Yes
[ ] No
```
=> [ACA-1800] add tests for unshare file

e2e/suites/actions/unshare-file.test.ts, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1913] Share update rules

src/app/extensions/extension.service.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Context Menu - remove extra type check for children

src/app/components/favorites/favorites.component.html, src/app/components/files/files.component.html, src/app/components/layout/layout.component.ts, src/app/components/libraries/libraries.component.html, src/app/components/page.component.ts, src/app/components/recent-files/recent-files.component.html, src/app/components/shared-files/shared-files.component.html, src/app/components/trashcan/trashcan.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
improve column rendering
```
[ ] Yes
[x] No
```
=> improve column rendering performance

src/app/components/layout/layout.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
remove memory leaks related to navigation and mobile screens
avoid spamming observables on each route change
```
[ ] Yes
[x] No
```
=> remove memory leak for mobile screens

e2e/components/dialog/share-dialog.ts, e2e/suites/actions/unshare-file.test.ts, src/app/components/shared/content-node-share/content-node-share.dialog.html, src/app/components/shared/content-node-share/content-node-share.dialog.spec.ts, src/app/components/shared/content-node-share/content-node-share.dialog.ts, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1911] Un-Share file - permission error notification

src/app/components/layout/layout.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1929] Sidenav - minimise on search refresh

cspell.json, e2e/components/dialog/share-dialog.ts, e2e/components/menu/menu.ts, e2e/configs.ts, e2e/resources/extensibility-configs/context-submenus-ext.json, e2e/suites/actions/unshare-file.test.ts, e2e/suites/extensions/ext-context-submenus.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1897] context submenu extension e2e

src/app.config.json
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1925 caused by non-unique 'key' identifiers
the sorting data sent in the request payload is now the correct one
```
[ ] Yes
[x] No
```
=> [ACA-1925] Search results are incorrectly sorted - fix

src/assets/i18n/de.json, src/assets/i18n/es.json, src/assets/i18n/fr.json, src/assets/i18n/it.json, src/assets/i18n/ja.json, src/assets/i18n/nb.json, src/assets/i18n/nl.json, src/assets/i18n/pt-BR.json, src/assets/i18n/ru.json, src/assets/i18n/zh-CN.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] - update localisation

src/app/app.routes.ts, src/app/components/header/header.component.ts, src/app/components/libraries/libraries.component.spec.ts, src/app/components/libraries/libraries.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
fix class imports
fix lazy loading paths
```
[ ] Yes
[x] No
```
=> fix imports

e2e/suites/actions/toolbar-single-selection.test.ts, src/app/components/libraries/libraries.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1956] Libraries - remove toolbar experimental flag

src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1959] [ACA-1960] Library metadata form action buttons state

e2e/components/datetime-picker/datetime-picker.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> e2e fix tomorrow date

e2e/components/info-drawer/info-drawer.ts, e2e/suites/info-drawer/library-properties.test.ts, e2e/utilities/repo-client/apis/queries/queries-api.ts, e2e/utilities/repo-client/repo-client.ts, e2e/utilities/utils.ts, protractor.conf.js
```
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: automated tests
```
Issue Number: ACA-1937
```
[ ] Yes
[x] No
```
=> [ACA-1937] automate tests for Library properties

e2e/suites/extensions/ext-info-drawer.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] trim expect and actual values

src/app/components/permissions/permission-manager/permission-manager.component.html, src/app/components/permissions/permission-manager/permission-manager.component.theme.scss, src/app/components/permissions/permission-manager/permission-manager.component.ts, src/assets/i18n/en.json
```
```
```
[x] Bugfix
[ ] Feature
```
- fir i18n for "add" button
- fix dialog layout (ADF issue workaround)
Before:
After:
```
[ ] Yes
[x] No
```
=> permission manager fixes

docs/extending.md
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] Documentation - isQuickShareEnabled evaluator

extension.schema.json, src/app/components/sidenav/sidenav.component.html, src/app/components/sidenav/sidenav.component.scss, src/app/components/sidenav/sidenav.component.theme.scss, src/app/extensions/extension.service.spec.ts, src/app/extensions/extension.service.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-20] Sidenav - submenu support

src/app/components/sidenav/sidenav.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-20] Sidenav- tooltip description

src/app.config.json
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1934
```
[ ] Yes
[x] No
```
=> [ACA-1934] Fix search facet fields translation

src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-20] Libraries - role column sort key

src/app/components/layout/app-layout/app-layout.component.spec.ts, src/app/components/layout/app-layout/app-layout.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> reset selection on navigation

e2e/components/sidenav/sidenav.ts, e2e/pages/browsing-page.ts, e2e/suites/navigation/breadcrumb.test.ts, src/app/components/libraries/libraries.component.html, src/app/components/sidenav/expansion-panel.directive.spec.ts, src/app/components/sidenav/expansion-panel.directive.ts, src/app/components/sidenav/sidenav.component.html, src/app/dialogs/library/library.dialog.html, src/assets/app.extensions.json, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-20] Sidenav - navigate to first child route when expanded for the first time

src/app/components/sidenav/sidenav.component.scss
```
```
```
[x] Bugfix
[ ] Feature
```
make menu items non-selectable
```
[ ] Yes
[x] No
```
=> css fixes for sidenav menu items

e2e/suites/actions/mark-favorite.test.ts, e2e/suites/actions/toolbar-single-selection.test.ts, e2e/utilities/repo-client/apis/favorites/favorites-api.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2008] tests for Favorite actions on a library

package-lock.json, src/app/components/search/search-input/search-input.component.ts, src/app/components/search/search-libraries-results/search-libraries-results.component.ts, src/app/components/search/search-results/search-results.component.ts, src/app/store/effects/search.effects.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1964
```
[ ] Yes
[x] No
```
=> [ACA-1964] Filter results by Files / Folders option

src/app/components/preview/preview.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
prevent double navigation for documents
```
[ ] Yes
[x] No
```
=> [ACA-1144] fix keyboard navigation

e2e/suites/search/search-results-libraries.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1943] add tests for Search results - libraries

src/app/components/favorite-libraries/favorite-libraries.component.ts, src/app/components/search/search-libraries-results/search-libraries-results.component.html, src/app/components/search/search-results.module.ts, src/app/components/toolbar/toggle-join-library/toggle-join-library.component.ts, src/assets/app.extensions.json, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2037 subtask of [[ACA-1607](https://issues.alfresco.com/jira/browse/ACA-1607)]
```
[ ] Yes
[x] No
```
=> [ACA-1607] context menu - join/cancel join actions

src/app/components/favorite-libraries/favorite-libraries.component.html, src/app/components/libraries/libraries.component.html, src/app/components/page.component.ts, src/app/ui/overrides/adf-document-list.theme.scss, src/assets/app.extensions.json, src/assets/images/baseline-library_books-24px.svg
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2039] Libraries - custom icon

src/app/components/shared/toggle-shared/toggle-shared.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] ToggleSharedComponent - isShared extra check

src/app/components/toolbar/toggle-join-library/toggle-join-library.component.ts, src/app/directives/library-membership.directive.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2045
```
[ ] Yes
[x] No
```
=> [ACA-2045] reset selection on toggle join action

e2e/suites/list-views/empty-list.test.ts, e2e/suites/list-views/permissions.test.ts, src/app/components/common/location-link/location-link.component.ts, src/app/store/effects/router.effects.ts, src/assets/i18n/en.json
```
```
```
[x] Bugfix
[ ] Feature
```
- navigate to shared folders within private libraries
- fix various app crashes for private libs and shared folders
- display private libraries as "unknown" locations (Search results)
- show snackbar errors when clicking the "unknown" locations
```
[ ] Yes
[x] No
```
=> [ACA-2022] navigation fixes

src/app/components/page.component.ts, src/app/components/search/search-libraries-results/search-libraries-results.component.html, src/app/components/trashcan/trashcan.component.html, src/app/components/trashcan/trashcan.component.ts, src/app/ui/overrides/adf-document-list.theme.scss, src/assets/app.extensions.json, src/assets/images/baseline-library_books-24px.svg
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2044] custom library icon consistency

src/app/app.routes.ts, src/app/components/search/search-input-control/search-input-control.component.html, src/app/components/search/search-input/search-input.component.html, src/app/components/search/search-input/search-input.component.ts, src/app/components/search/search-libraries-results/search-libraries-query-builder.service.ts, src/app/components/search/search-libraries-results/search-libraries-results.component.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1968
```
[ ] Yes
[ ] No
```
=> [ACA-1968] Trigger search on Enter

src/app/dialogs/library/library.dialog.html
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Create library dialog - autofocus on first input

src/app/services/content-management.service.spec.ts, src/app/services/content-management.service.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2047]  navigate to restored library content folder

src/app/app.component.spec.ts, src/app/app.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1057] Upload - snack-bar error messages

src/app/components/files/files.component.ts, src/app/store/selectors/app.selectors.ts
```
```
```
[ ] Bugfix
[x] Feature
```
- do not truncate breadcrumbs for "User Homes" for admins
```
[ ] Yes
[x] No
```
=> [ACA-1039] improved breadcrumbs for admins

src/app/components/upload-dialog/file-uploading-dialog.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2056] Upload - not able to cancel upload after upload fails due to No network connection

src/app/services/node-actions.service.spec.ts, src/app/services/node-actions.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1322
```
[ ] Yes
[x] No
```
=> [ACA-1322] Destination picker - Sites: only document library allowed as destination

src/app/app.module.ts, src/app/services/data.service.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Filter out various content types from Recent Files page.
```
[ ] Yes
[x] No
```
=> [ACA-1919] query improvements for recent files

cspell.json, src/app/extensions/extension.service.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1923] Extensions - sort children by order

src/assets/app.extensions.json
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2059
```
[ ] Yes
[x] No
```
=> [ACA-2059] remove header extension

cspell.json, src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.scss, src/app/components/preview/preview.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2060](https://issues.alfresco.com/jira/browse/ACA-2060)
```
[ ] Yes
[x] No
```
=> [ACA-2060] arrange viewer toolbar icons

src/app/components/favorite-libraries/favorite-libraries.component.html, src/app/components/favorite-libraries/favorite-libraries.component.spec.ts, src/app/components/favorite-libraries/favorite-libraries.component.ts, src/app/services/content-api.service.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1993] Favorite libraries - custom pagination

src/app/components/shared/content-node-share/content-node-share.dialog.scss, src/app/ui/application.scss, src/app/ui/custom-theme.scss
that appeared after upgrading material to 7.1.0
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2069
```
[ ] Yes
[x] No
```
=> [ACA-2069] fix blue slider issue

src/app/directives/library-membership.directive.spec.ts, src/app/directives/library-membership.directive.ts, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: 
Specific error message shown when the email address of sender/receiver is invalid on requesting to join a moderated site.
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2040
```
[ ] Yes
[x] No
```
=> [ACA-2040] handle invalid email cases on join request

src/app/directives/document-list.directive.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA] update selected rows without locked files

src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.scss, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2062
```
[ ] Yes
[x] No
```
=> [ACA-2062][ACA-2066] Update Viewer actions

src/app/directives/library-membership.directive.spec.ts, src/app/directives/library-membership.directive.ts, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2040
```
[ ] Yes
[x] No
```
=> [ACA-2040] show different email invalid error messages

src/app/dialogs/library/library.dialog.html, src/app/material.module.ts, src/app/services/content-management.service.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2075] Create Library dialog is not focused when opening it for the second time

src/app/dialogs/library/library.dialog.html, src/app/dialogs/library/library.dialog.spec.ts, src/app/dialogs/library/library.dialog.ts, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2074] Create Library - title & id validation

src/app/components/preview/preview.component.ts, src/app/services/data.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2077
```
[ ] Yes
[x] No
```
=> [ACA-2077] viewer - filter recent files

src/app/components/layout/app-layout/app-layout.component.spec.ts, src/app/components/layout/app-layout/app-layout.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2081] Search - toolbar not visible after viewer is closed

src/app.config.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-1904
```
[ ] Yes
[x] No
```
=> [ACA-1904] Language labels

e2e/suites/navigation/sidebar.test.ts, src/app/components/sidenav/sidenav.component.html, src/app/components/sidenav/sidenav.component.spec.ts, src/app/components/sidenav/sidenav.component.theme.scss
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2067] Side navigation - highlight element with children only when not expanded

src/app/components/search/search-results/search-results.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-1926] Search - context menu

package-lock.json, package.json, src/app/components/common/generic-error/generic-error.component.html, src/app/components/common/icon/icon.component.html, src/app/components/create-menu/create-menu.component.html, src/app/components/current-user/current-user.component.html, src/app/components/info-drawer/info-drawer.component.html, src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.html, src/app/components/layout/app-layout/app-layout.component.html, src/app/components/login/login.component.html, src/app/components/permissions/permission-dialog/node-permissions.dialog.html, src/app/components/permissions/permission-manager/permission-manager.component.html, src/app/components/preview/preview.component.html, src/app/components/search/search-input-control/search-input-control.component.html, src/app/components/search/search-input/search-input.component.html, src/app/components/search/search-results-row/search-results-row.component.html, src/app/components/search/search-results/search-results.component.html, src/app/components/settings/settings.component.html, src/app/components/shared-link-view/shared-link-view.component.html, src/app/components/shared/content-node-share/content-node-share.dialog.html, src/app/components/shared/toggle-shared/toggle-shared.component.html, src/app/components/sidenav/sidenav.component.html, src/app/components/toolbar/toolbar-action/toolbar-action.component.html, src/app/components/upload-dialog/file-uploading-dialog.component.html, src/app/components/upload-dialog/file-uploading-list-row.component.html, src/app/components/upload-dialog/file-uploading-list.component.html, src/app/dialogs/library/library.dialog.html, src/app/dialogs/node-versions/node-versions.dialog.html
```
```
```
[ ] Bugfix
[x] Feature
```
- add pre-commit hooks for staged files, run Prettier for modified files
- add `format:fix` script to auto-fix entire project
- add `.html` files to the Prettier check (`format:check`)
```
[ ] Yes
[x] No
```
=> [ACA-2122] automatic code formatting on commit

src/assets/app.extensions.json
```
```
```
[x] Bugfix
[ ] Feature
```
update library toolbar (leave icon and buttons order)
```
[ ] Yes
[x] No
```
=> [ACA-2120] update library toolbar

package-lock.json, package.json, protractor.conf.js, src/app/components/sidenav/sidenav.component.html, src/app/services/node-actions.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Support custom icons with the Navbar extensions
```
[ ] Yes
[x] No
```
=> [ACA-2162] allow custom icons with navbar

e2e/components/menu/menu.ts, e2e/components/search/search-input.ts, e2e/components/toolbar/toolbar.ts, e2e/suites/actions/context-menu-multiple-selection.test.ts, e2e/suites/actions/context-menu-single-selection.test.ts, e2e/suites/actions/delete-undo-delete.test.ts, e2e/suites/actions/edit-folder.test.ts, e2e/suites/actions/special-permissions-available-actions.test.ts, e2e/suites/actions/toolbar-multiple-selection.test.ts, e2e/suites/actions/toolbar-single-selection.test.ts, e2e/suites/list-views/tooltips.test.ts, e2e/suites/viewer/viewer-actions.test.ts, e2e/utilities/repo-client/apis/nodes/nodes-api.ts, src/app/extensions/core.extensions.module.ts, src/app/extensions/evaluators/app.evaluators.ts, src/app/extensions/evaluators/navigation.evaluators.ts, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: automated tests
```
Issue Number: ACA-2160, ACA-213
```
[ ] Yes
[x] No
```
=> [ACA-2160] add tests for Edit offline actions availability

src/app/components/layout/app-layout/app-layout.component.ts
* Added a check for mobile pages to prevent sidemenu opening
```
- [ X] The commit message follows our guidelines: https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
```
```
[X] Bugfix
[ ] Feature
```
[#927](https://github.com/Alfresco/alfresco-content-app/issues/927 …
=> #927 Search on mobile opens Sidemenu

e2e/suites/actions/copy.test.ts, e2e/suites/actions/move.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Some tests were temporarily disabled, see [ACA-2171](https://issues.alfresco.com/jira/browse/ACA-2171) for more details.
Enable back the skipped tests because of https://issues.alfresco.com/jira/browse/ACA-2171
```
[ ] Yes
[x] No
```
https://issues.alfresco.com/jira/browse/ACA-2171
=> [ACA-2171] enable copy and move to library tests

src/app/dialogs/node-version-upload/node-version-upload.dialog.html, src/app/dialogs/node-version-upload/node-version-upload.dialog.scss, src/assets/i18n/en.json
```
```
```
[x] Bugfix
[ ] Feature
```
**Buttons have incorrect text on Upload new version dialog**
See [ACA-2210](https://issues.alfresco.com/jira/browse/ACA-2210) for more details.
Wording update, use "Cancel" instead of "Close" for the cancel button.
```
[ ] Yes
[x] No
```
=> [ACA-2210] Version Dialog - update button text

src/app/components/node-version/node-version-form.component.spec.ts, src/app/components/node-version/node-version-form.component.ts, src/app/store/effects/upload.effects.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: [ACA-2206](https://issues.alfresco.com/jira/browse/ACA-2206)
Correctly pass the `boolean` flag for the major/minor version to Upload Service.
```
[ ] Yes
[x] No
```
=> [ACA-213] Upload Version - version options use boolean values

e2e/suites/actions/download.test.ts, e2e/utilities/utils.ts
```
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: automated tests
```
Issue Number: ACA-556
```
[ ] Yes
[x] No
```
=> [ACA-556] add tests for downloading a single file

src/assets/app.extensions.json
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2180](https://issues.alfresco.com/jira/browse/ACA-2180)
```
[ ] Yes
[x] No
```
=> [ACA-2180] Viewer - toolbar action separator

docs/features/search-results.md, src/app.config.json, src/app/components/search/search-results/search-results.component.spec.ts, src/app/components/search/search-results/search-results.component.ts, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: [ACA-2219](https://issues.alfresco.com/jira/browse/ACA-2219)
Support for more precise search queries that include conjunctions, disjunctions, and phrases.
See more details in the corresponding [ticket](https://issues.alfresco.com/jira/browse/ACA-2219)
```
[ ] Yes
[x] No
```
=> [ACA-2219] support more precise searching

e2e/components/header/header.ts, e2e/components/sidenav/sidenav.ts, e2e/suites/navigation/sidebar.test.ts, src/app/components/layout/app-layout/app-layout.component.html, src/app/components/sidenav/sidenav.component.html
```
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: automated tests
```
Issue Number: ACA-1259
```
[ ] Yes
[x] No
```
=> [ACA-1259] automate remaining tests for sidebar

Dockerfile, docker/entrypoint.sh, docker/nginx.conf
```
```
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
- fix the issue with app.config.json permissions
- revoke access to index.html (disables Base URL overrides as a side-effect) to prevent serving custom content
- enable access logging
```
[ ] Yes
[x] No
```
=> [ACA-2229] docker security fixes

src/app/components/info-drawer/info-drawer.component.spec.ts, src/app/components/info-drawer/info-drawer.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2194](https://issues.alfresco.com/jira/browse/ACA-2194), #923 
- an improved way to detect if aspects need to be loaded
- removes old code that restricted the display to image/exif aspects for certain scenarios
```
[ ] Yes
[x] No
```
=> [ACA-2194] better custom aspects in metadata tab

src/app/components/dl-custom-components/locked-by/locked-by.component.scss, src/app/components/dl-custom-components/name-column/name-column.component.scss, src/app/ui/overrides/adf-document-list.theme.scss
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2237](https://issues.alfresco.com/jira/browse/ACA-2237)
render document list cell with lockedby information properly 
```
[ ] Yes
[x] No
```
=> [ACA-2237] DocumentList - fix lockby position in IE

README.md, docs/README.md
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number:  [ACA-2203](https://issues.alfresco.com/jira/browse/ACA-2203)
closes #932
- add ADF/ACS compatibility matrix to docs
- minor readme fixes 
```
[ ] Yes
[x] No
```
=> [ACA-2203] compatibility matrix

src/app/components/favorite-libraries/favorite-libraries.component.spec.ts, src/app/components/favorites/favorites.component.spec.ts, src/app/components/files/files.component.spec.ts, src/app/components/libraries/libraries.component.spec.ts, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/shared-files/shared-files.component.spec.ts, src/app/components/trashcan/trashcan.component.spec.ts, src/app/testing/app-testing.module.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2228
- fixes unit tests after upgrade to 3.1.0-beta4+
```
[ ] Yes
[x] No
```
=> [ACA-2228] Add PipeModule to AppTestingModule

src/app/components/files/files.component.html
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: [ACA-2215](https://issues.alfresco.com/jira/browse/ACA-2215)
refs #926
Responsive breadcrumb mode for small screens
Large screens:
Small screens:
```
[ ] Yes
[x] No
```
=> [ACA-2215] responsive breadcrumb

src/app/app.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2195
```
[ ] Yes
[x] No
```
=> [ACA-2195] fix redirect on login after page reload

src/app/components/search/search-results/search-results.component.spec.ts, src/app/components/search/search-results/search-results.component.ts, src/assets/i18n/en.json
```
```
```
[x] Bugfix
[ ] Feature
```
Raise snackbar notification  when API call fails
```
[ ] Yes
[x] No
```
=> [ACA] Search - show error message on error

src/app/components/search/search-results/search-results.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2264
```
[ ] Yes
[x] No
```
=> [ACA-2264] fix loading on search

e2e/components/info-drawer/info-drawer.ts, e2e/suites/info-drawer/comments.test.ts, e2e/suites/info-drawer/general.test.ts, e2e/utilities/repo-client/apis/comments/comments-api.ts, e2e/utilities/repo-client/repo-client.ts, src/app.config.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-1627
- e2e tests for Comments
```
[ ] Yes
[x] No
```
=> [ACA-1627] add automated tests for Comments

projects/adf-office-services-ext/src/lib/aos-extension.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2260](https://issues.alfresco.com/jira/browse/ACA-2260)
```
[ ] Yes
[x] No
```
=> [ACA-2260] Open in Office - action breaks application in IE

src/app/components/info-drawer/comments-tab/comments-tab.component.spec.ts, src/app/components/info-drawer/comments-tab/comments-tab.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: fix regression [ACA-2270](https://issues.alfresco.com/jira/browse/ACA-2270)
```
[ ] Yes
[x] No
```
=> [ACA-2270] allow add comments on folder

projects/adf-office-services-ext/src/lib/evaluators.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2281](https://issues.alfresco.com/jira/browse/ACA-2281)
```
[ ] Yes
[x] No
```
=> [ACA-2281] Edit in Microsoft Office is displayed regardless of file type for Shared Files list

src/app.config.json
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2271](https://issues.alfresco.com/jira/browse/ACA-2271)
```
[ ] Yes
[x] No
```
=> [ACA-2271] Search - set default sort option ascending property same with option 

src/app/components/shared-link-view/shared-link-view.component.scss
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: small UI fix for shared link's view
```
```
[ ] Yes
[x] No
```
=> remove unneeded divider from toolbar

.travis.yml
```
```
```
[ ] Bugfix
[ ] Feature
```
use official Long-Term Support (LTS) version of Node.js in CI runs
```
[ ] Yes
[ ] No
```
=> use LTS node.js

src/app/components/search/search-results/search-results.component.spec.ts, src/app/components/search/search-results/search-results.component.ts, src/app/components/shared-link-view/shared-link-view.component.scss
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2299](https://issues.alfresco.com/jira/browse/ACA-2299)
Correctly fallback to generic error messages
```
[ ] Yes
[x] No
```
=> [ACA-2299] fix search error translation

src/app.config.json
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2236
Additional localisations into Arabic, Czech, Danish, Finnish, Polish and Swedish.
```
[ ] Yes
[x] No
```
=> [ACA-2236] Update language menu to include the new languages

src/app/services/node-actions.service.spec.ts, src/app/services/node-actions.service.ts
- remove ACA workaround
- testing is done on ADF component
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: remove workaround and use new 'excludeSiteContent' property from ADF
```
```
[ ] Yes
[x] No
```
=> [ACA-2137] Destination picker - use excludeSiteContent

src/app.config.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Filter facet field results using 'contains' instead of 'starts with'.
Filtering facet field results was done using 'starts with'.
```
[ ] Yes
[x] No
```
=> [ACA-2272] Search filter categories - with contains

src/app/components/preview/preview.component.html
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: removes old code that was part of a workaround.
```
```
[ ] Yes
[x] No
```
=> [ACA-2138] Viewer - remove old styling class

extension.schema.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add newly supported 'disabled' property for navbar to schema json file 
```
```
[ ] Yes
[x] No
```
=> add 'disabled' property for navBar to extension.schema.json

e2e/suites/search/search-results-libraries.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: makes sure that the 'my-site...' is created before running the tests
```
```
[ ] Yes
[x] No
```
=> fix random failing e2e test C290014

src/app.config.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: 
- removes language from menu. 
Arabic will be added back once the RTL support is added.
```
```
[ ] Yes
[x] No
```
=> [ACA-2236] remove Arabic from language-menu until RTL support is added

src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix column name width

e2e/components/data-table/data-table.ts, e2e/components/menu/menu.ts, e2e/components/pagination/pagination.ts, e2e/suites/pagination/pag-favorites.test.ts, e2e/suites/pagination/pag-file-libraries.test.ts, e2e/suites/pagination/pag-personal-files.test.ts, e2e/suites/pagination/pag-recent-files.test.ts, e2e/suites/pagination/pag-search-results.test.ts, e2e/suites/pagination/pag-shared-files.test.ts, e2e/suites/pagination/pag-trash.test.ts, protractor.conf.js
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-1766
```
[ ] Yes
[ ] No
```
=> [ACA-1766] disable selenium_promise_manager

src/app/components/dl-custom-components/document-list-custom-components.module.ts, src/app/components/dl-custom-components/name-column/name-column.component.html, src/app/components/dl-custom-components/name-column/name-column.component.ts, src/app/components/search/search-results-row/search-results-row.component.html, src/app/components/search/search-results-row/search-results-row.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
- upgrade name columns to reflect on name and metadata changes
```
[ ] Yes
[x] No
```
=> [ACA-1288] dynamic name cells

package-lock.json, package.json, src/app/components/search/search-results/search-results.component.ts, src/app/directives/library-membership.directive.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: ACA-2334
- upgrade to latest ADF alpha
- remove search error handling as it's not covered by ADF
```
[ ] Yes
[x] No
```
=> [ACA-2334] upgrade to latest adf, remove search workarounds

src/app/components/info-drawer/metadata-tab/metadata-tab.component.spec.ts, src/app/components/info-drawer/metadata-tab/metadata-tab.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2345](https://issues.alfresco.com/jira/browse/ACA-2345)
```
[ ] Yes
[x] No
```
=> [ACA-2345] Metadata - edit button is not displayed for folders

.github/plint.yml, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: [ACA-2367](https://issues.alfresco.com/jira/browse/ACA-2367)
- enable default menu actions so that we don't have to constantly explain how to get there
* Settings
* About
* Sign Out
```
[ ] Yes
[x] No
```
=> [ACA-2367] default header actions

e2e/suites/pagination/pag-file-libraries.test.ts, e2e/suites/viewer/viewer-actions.test.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> [ACA-2371] enable e2e tests

src/app/components/shared/content-node-share/content-node-share.dialog.scss, src/app/ui/custom-theme.scss, src/app/ui/overrides/adf-toolbar.theme.scss
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number:
- https://issues.alfresco.com/jira/browse/ACA-2111
- https://issues.alfresco.com/jira/browse/ACA-2147
```
[ ] Yes
[x] No
```
=> [ACA-2147] minor theme fixes

src/app.config.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Display a 'Reset all' button on top of search filters - this allows the end user, through one click, to reset all selections and filterings he had previously made on the search filters.
```
[ ] Yes
[x] No
```
=> [ACA-1623] enable Reset all filters button

src/app/components/layout/app-layout/app-layout.component.html, src/app/components/sidenav/sidenav.component.scss, src/app/components/sidenav/sidenav.component.spec.ts, src/app/components/sidenav/sidenav.component.theme.scss, src/app/components/sidenav/sidenav.component.ts
```
```
```
[ ] Bugfix
[x] Feature
```
[ACA-2374](https://issues.alfresco.com/jira/browse/ACA-2374)
- added app-sidenav direction input
- add app-sidenav-rtl class for RTL
```
[ ] Yes
[x] No
```
=> [ACA-2374] Sidenav - RTL support

src/app/components/context-menu/context-menu.component.html, src/app/components/context-menu/context-menu.component.ts, src/app/components/context-menu/context-menu.service.spec.ts, src/app/components/context-menu/context-menu.service.ts, src/app/components/context-menu/direction.token.ts
```
- [] Docs have been added / updated (for bug fixes / features)
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: [ACA-2375](https://issues.alfresco.com/jira/browse/ACA-2375)
```
[ ] Yes
[x] No
```
=> [ACA-2375] Contextmenu - RTL support

.github/plint.yml, src/app/components/info-drawer/info-drawer.component.html, src/app/components/info-drawer/metadata-tab/metadata-tab.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number:
https://issues.alfresco.com/jira/browse/ACA-2286
https://issues.alfresco.com/jira/browse/ACA-2377
- show popups on metadata errors
- use native ADF i18n support for info drawer
```
[ ] Yes
[x] No
```
=> [ACA-2286] handle metadata errors

docs/extending/rules.md, projects/aca-shared/rules/src/user.rules.spec.ts, projects/aca-shared/rules/src/user.rules.ts, src/app/extensions/core.extensions.module.ts
```
```
```
[ ] Bugfix
[x] Feature
```
[ACA-2390](https://issues.alfresco.com/jira/browse/ACA-2390)
```
[ ] Yes
[x] No
```
=> [ACA-2390] Evaluators - user is admin

package-lock.json, package.json, src/app.config.json, src/app/components/layout/app-layout/app-layout.component.html, src/app/components/layout/app-layout/app-layout.component.spec.ts, src/app/components/layout/app-layout/app-layout.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> 3.3.0 alpha update

src/app/ui/application.scss
```
```
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
[mat-icon](https://material.angular.io/components/icon/overview#bidirectionality) doesn't support directionality out of the box and manually adding proposed class to every icon and remembering to do this its an overload.
=> mirror mat-icon when direction is RTL

src/app.config.json, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
```
The data (from these titled & author aspects) is already displayed in the list of the basic default properties, so it has been decided not to display it again inside separate expansion panels.
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2415
```
[ ] Yes
[x] No
```
=> [ACA-2415] author & titled aspects should be excluded

package-lock.json, package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
use `husky` library for pre-commit hooks
```
[ ] Yes
[x] No
```
=> switch to husky for pre-commit hook

src/app.config.json, src/assets/app.extensions.json, src/assets/i18n/en.json
```
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: Please check description from issue https://issues.alfresco.com/jira/browse/ACA-2420
```
[ ] Yes
[x] No
```
=> [ACA-2420] exclude aspects and order effectivity properties

projects/aca-shared/src/lib/components/page-layout/page-layout.component.scss, src/app/components/sidenav/sidenav.component.scss
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: 
[ACA-2468](https://issues.alfresco.com/jira/browse/ACA-2468)
[ACA-2469](https://issues.alfresco.com/jira/browse/ACA-2469)
```
[ ] Yes
[x] No
```
=> [ACA-2468][ACA-2469] RTL styling

src/app.config.json, src/app/app.module.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix DatePipe missing locale data

.vscode/extensions.json, e2e/configs.ts, e2e/suites/info-drawer/file-folder-properties.test.ts, package-lock.json, package.json, src/app.config.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> latest ADF alpha

src/app.config.json, src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: do not display these aspects until ADF component supports correct display of properties there are currently displayed as ```[object Object]```
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2640
```
[ ] Yes
[x] No
```
=> [ACA-2640] Exclude problematic aspects

src/app/store/effects/upload.effects.spec.ts, src/app/store/effects/upload.effects.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2643](https://issues.alfresco.com/jira/browse/ACA-2643)
```
[ ] Yes
[x] No
```
=> [ACA-2643] Upload new version - refactoring

.github/CODEOWNERS
```
```
```
[ ] Bugfix
[x] Feature
```
setup GitHub code owners
```
[ ] Yes
[x] No
```
=> setup code owners and default reviewers

projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/rules/src/app.rules.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2645](https://issues.alfresco.com/jira/browse/ACA-2645)
```
[ ] Yes
[x] No
```
=> [ACA-2645] Shared - don't render shared settings action for multiple selection

src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: [ACA-2647](https://issues.alfresco.com/jira/browse/ACA-2647)
```
[ ] Yes
[x] No
```
=> [ACA-2647] Update the folder actions toolbar

src/assets/app.extensions.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: [ACA-2648](https://issues.alfresco.com/jira/browse/ACA-2648)
```
[ ] Yes
[x] No
```
=> [ACA-2648] Viewer - fix toolbar actions inconsistencies

e2e/configs.ts, src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.scss
```
```
```
[x] Bugfix
[ ] Feature
```
Each time the info drawer is opened/closed, the content from the viewer is reloaded.
Use CSS class to handle sidebar's width to avoid triggering reloading content on showRightSide toggle
```
[ ] Yes
[x] No
```
=> [ACA-2288] Music / video stops playing when opening the Info drawer in the viewer

projects/adf-office-services-ext/assets/aos.plugin.json
```
```
```
[x] Bugfix
[ ] Feature
[] Refactoring (no functional changes, no api changes)
```
Issue Number: [ACA-2649](https://issues.alfresco.com/jira/browse/ACA-2649)
```
[ ] Yes
[x] No
```
=> [ACA-2649] Edit in Office - context menu order

src/assets/i18n/ar.json, src/assets/i18n/cs.json, src/assets/i18n/da.json, src/assets/i18n/de.json, src/assets/i18n/es.json, src/assets/i18n/fi.json, src/assets/i18n/fr.json, src/assets/i18n/it.json, src/assets/i18n/ja.json, src/assets/i18n/nl.json, src/assets/i18n/pl.json, src/assets/i18n/pt-BR.json, src/assets/i18n/ru.json, src/assets/i18n/sv.json, src/assets/i18n/zh-CN.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: i18N update
```
Issue Number: [ACA-2460](https://issues.alfresco.com/jira/browse/ACA-2460)
```
[ ] Yes
[x] No
```
=> [ACA-2460] i18n update

src/assets/i18n/nb.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: i18n updates
```
```
[ ] Yes
[x] No
```
=> [ACA-2460] get translations for Norwegian

src/app/ui/overrides/adf-document-list.theme.scss, src/assets/app.extensions.json
```
```
```
[x] Bugfix
[ ] Feature
[x] Other... Please describe: UI changes
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2654
```
[ ] Yes
[x] No
```
=> [ACA-2654] show ellipsis for long Size column headers

src/assets/i18n/es.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: i18n updates
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2460
```
[ ] Yes
[x] No
```
=> [ACA-2460] es.json updated

src/assets/i18n/it.json
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: i18n update
```
```
[ ] Yes
[x] No
```
=> [ACA-2460] translation small update

projects/adf-office-services-ext/src/lib/evaluators.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: [ACA-2653](https://issues.alfresco.com/jira/browse/ACA-2653)
```
[ ] Yes
[ ] No
```
=> [ACA-2653] Disable the check for SSO when running AOS extension

src/assets/plugins/app.header.json
```
```
```
[ ] Bugfix
[ ] Feature
```
Issue Number: [ACA-2656](https://issues.alfresco.com/jira/browse/ACA-2656)
```
[ ] Yes
[x] No
```
=> [ACA-2656] remove sign out option from header extension

src/app/ui/application.scss
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2652
allow folder names from breadcrumb to shrink when path is too long to fit the screen
```
[ ] Yes
[x] No
```
=> [ACA-2652] ellipsis fix

docs/getting-started/prerequisites.md
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> Update app prerequisites section

projects/aca-shared/package.json
=> bump aca-shared version

projects/adf-office-services-ext/package.json
Issue Number: [ACA-2659](https://issues.alfresco.com/jira/browse/ACA-2659)
bump AOS extension version
=> [ACA-2659] bump AOS-extension version

src/app.config.json
Show the 1.9 future version on development About page
=> Update About version on Development branch

src/app/components/layout/app-layout/app-layout.component.spec.ts, src/app/components/layout/app-layout/app-layout.component.ts, src/app/components/search/search-results-row/search-results-row.component.html, src/app/components/search/search-results-row/search-results-row.component.ts, src/app/components/toolbar/toggle-favorite/toggle-favorite.component.spec.ts, src/app/components/toolbar/toggle-favorite/toggle-favorite.component.ts, src/app/components/toolbar/toolbar-menu/toolbar-menu.component.html, src/app/services/content-management.service.ts, src/assets/app.extensions.json
```
```
```
[x] Bugfix
[ ] Feature
```
Issue Number: [ACA-2651](https://issues.alfresco.com/jira/browse/ACA-2651)
```
[ ] Yes
[x] No
```
=> [ACA-2651] Viewer - toolbar disappears after marking / removing a specific file as favourite

angular.json
Issue Number: [ACA-2693](https://issues.alfresco.com/jira/browse/ACA-2693)
Introduce reasonable bundle budgets for production builds
=> [ACA-2693] setup bundle budgets

docs/getting-started/sso.md
=> Replace 'Alfresco Identity Service' with 'Identity Service'

package-lock.json, package.json
fix pdfjs version since the latest breaks the viewer
=> pdfjs fix version

package-lock.json, package.json, src/app/components/dl-custom-components/name-column/name-column.component.ts, src/app/components/info-drawer/metadata-tab/metadata-tab.component.spec.ts, src/app/directives/library-membership.directive.spec.ts
Issue Number: [ACA-2694](https://issues.alfresco.com/jira/browse/ACA-2694)
update to ADF 3.4.0-1108 alpha
=> [ACA-2694] update to ADF 3.4.0-1108

docs/extending/application-features.md, docs/features/document-list-layout.md, docs/features/header.md, docs/features/search-results.md, docs/features/side-navigation.md, docs/getting-started/configuration.md, docs/getting-started/internationalization.md, docs/getting-started/sso.md
Issue Number: #1176
Fixed links to incorrect official documents in Markdown documents.
=> Fixed invalid url link.

src/app/components/dl-custom-components/name-column/name-column.component.html, src/app/components/dl-custom-components/name-column/name-column.component.scss, src/app/components/dl-custom-components/name-column/name-column.component.ts, src/assets/i18n/en.json
Issue Number: [ACA-2499](https://issues.alfresco.com/jira/browse/ACA-2499)
added aria-role and aria-label for link purpose
=> [ACA-2499] DocumentList - custom name column link does not have a role

docs/getting-started/navigation.md, src/app/extensions/extension.service.spec.ts, src/app/extensions/extension.service.ts
Issue Number: [ACA-2746](https://issues.alfresco.com/jira/browse/ACA-2746)
Allow groups to be filter by visibility condition
=> [ACA-2746] Side Navigation - conditionally render group of items

src/app.config.json
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2644
* Needs latest alfresco-js-api in order to fix the top issue.
update app.config.json to defined sso public routes
=> [ACA-2644] SSO set publicUrls 

src/app/app.routes.ts
=> [ADF-4824] Add AuthGuard

package-lock.json, package.json
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2754
Upgrade to get the SSO fixes.
=> [ACA-2754] Upgrade ACA to latest ADF and latest js-api

src/assets/i18n/en.json
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2499
added accessibility text for custom document list icons
=> [ACA-2499] Document list - custom icons accessibility  text

src/app/components/search/search-results-row/search-results-row.component.html, src/app/components/search/search-results-row/search-results-row.component.scss
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2499
added role and tabindex for custom elements links
=> [ACA-2499] Document list - search results accessibility

src/app/ui/custom-theme.scss, src/app/ui/overrides/adf-style-fixes.theme.scss
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2742
Clear the no longer needed styles, as they are now part of ADF. 
Keep the adf-style-fixes.theme.css file for possible future style overrides.
=> [ACA-2742] remove not needed style fixes - already moved to ADF 3.5.0

src/app/components/viewer/viewer.component.html, src/app/components/viewer/viewer.component.ts
use displayName property of adf-viewer to be used for accessibility
=> Viewer - set image name

src/app/components/toolbar/document-display-mode/document-display-mode.component.ts, src/app/components/toolbar/toggle-info-drawer/toggle-info-drawer.component.ts, src/app/components/toolbar/toolbar-button/toolbar-button.component.html, src/app/components/toolbar/toolbar-menu/toolbar-menu.component.html, src/app/components/toolbar/view-node/view-node.component.ts, src/assets/i18n/en.json
Issue Number: [ACA-2766](https://issues.alfresco.com/jira/browse/ACA-2766)
added aria labels for icon actions
=> [ACA-2766] Toolbar actions accessibility

package-lock.json, package.json
=> [ACA-2765] Upgrade to latest ADF alpha

src/app/components/toolbar/toggle-info-drawer/toggle-info-drawer.component.ts
Issue Number: [ACA-2490](https://issues.alfresco.com/jira/browse/ACA-2490)
=> [ACA-2490] Info drawer - Expanded/collapsed state incompletely exposed via ARIA

src/app/services/content-management.service.ts
Issue Number: [ACA-2486](https://issues.alfresco.com/jira/browse/ACA-2486)
=> [ACA-2486] Share link - when modal is closed focus is not returned to trigger

e2e/components/data-table/data-table.ts, e2e/components/info-drawer/info-drawer.ts, e2e/components/login/login.ts, e2e/components/menu/menu.ts, e2e/components/viewer/viewer.ts, e2e/suites/actions-available/test-util.ts, e2e/utilities/repo-client/apis/favorites/favorites-api.ts, e2e/utilities/repo-client/apis/shared-links/shared-links-api.ts, e2e/utilities/repo-client/apis/sites/sites-api.ts, package-lock.json, package.json, src/app/components/layout/app-layout/app-layout.component.spec.ts, src/app/components/search/search-results/search-results.component.ts, src/app/services/content-management.service.spec.ts, tsconfig.json
Issue Number: AAE-622
- enable `noImplicitReturns` rule
- upgrade to latest JS-API, fix issues
https://issues.alfresco.com/jira/browse/AAE-622
=> [AAE-622] enable noImplicitReturns rule

src/app/app.component.html, src/app/app.component.scss, src/app/app.component.ts
Issue Number: [ACA-2130](https://issues.alfresco.com/jira/browse/ACA-2130)
added heading for accessibility
=> [ACA-2130] App - page must contain a level-one heading

src/app/components/current-user/current-user.component.html
Give Avatar button aria label and role button
Issue Number: ACA-2506
=> [ACA-2506] Header - Button does not have a role

src/app/components/current-user/current-user.component.html
added back https://github.com/Alfresco/alfresco-content-app/commit/322cd27111e9c3411ea86c1fa6dcf47d7da09001
=> fix revert

src/app/components/preview/preview.component.html, src/app/components/preview/preview.component.spec.ts, src/app/components/preview/preview.component.ts, src/app/components/viewer/viewer.component.html, src/app/components/viewer/viewer.component.ts
Issue Number: [ACA-2526](https://issues.alfresco.com/jira/browse/ACA-2526)
don't trigger keyboard navigation for specified html containers
https://github.com/Alfresco/alfresco-content-app/pull/1233 should be merged first
=> [ACA-2526] Info Drawer - When user selects or inputs value a substantial change occurs

src/app/components/preview/preview.component.spec.ts, src/app/components/preview/preview.component.ts, src/app/components/viewer/viewer.component.ts
Issue Number: [ACA-2489](https://issues.alfresco.com/jira/browse/ACA-2489)
don't navigate to next or previous node if image is being drag with keyboard
=> [ACA-2489] - Drag and Drop is not operable with keyboard alone

src/app/components/search/search-results/search-results.component.scss
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2601
Fix the display for mat-form-field legacy style label that overlaps error message.
=> [ACA-2601] Search-date-range - fix content overlap

e2e/utilities/repo-client/apis/sites/sites-api.ts, projects/aca-shared/src/lib/routing/shared.guard.ts, src/app/components/context-menu/context-menu.service.spec.ts, src/app/components/favorite-libraries/favorite-libraries.component.spec.ts, src/app/components/files/files.component.ts, src/app/components/layout/app-layout/app-layout.component.spec.ts, src/app/components/preview/preview.component.ts, src/app/components/search/search-libraries-results/search-libraries-results.component.ts, src/app/components/viewer/viewer.component.ts, src/app/services/content-management.service.ts, tslint.json
Issue Number: ACA-2822
add no-duplicate-imports rule and fix the few lint issues discovered by this rule
=> [ACA-2822] add no-duplicate-imports rule

package-lock.json, package.json
=> upgrade js-api version to latest

src/assets/i18n/ar.json, src/assets/i18n/cs.json, src/assets/i18n/da.json, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/es.json, src/assets/i18n/fi.json, src/assets/i18n/fr.json, src/assets/i18n/it.json, src/assets/i18n/ja.json, src/assets/i18n/nb.json, src/assets/i18n/nl.json, src/assets/i18n/pl.json, src/assets/i18n/pt-BR.json, src/assets/i18n/ru.json, src/assets/i18n/sv.json, src/assets/i18n/zh-CN.json
Issue Number: ACA-2670
added new translation files
=> [ACA-2670] i18N update

src/app/ui/custom-theme.scss, src/app/ui/overrides/adf-style-fixes.theme.scss
Issue Number: [ACA-2830](https://issues.alfresco.com/jira/browse/ACA-2830)
Hide `modified` and `modifier` columns in the Node Selector for Copy/Move operations
Temporary fixes issue with corrupted layout for Sites
=> [ACA-2830] hide node selector columns

src/app.config.json, src/app/components/viewer/viewer.component.html
Issue Number: [ACA-2085](https://issues.alfresco.com/jira/browse/ACA-2085)
- make Viewer.maxRetries configurable
- set default retry to 1 (10 seconds before retry and 10 after, 20 seconds waiting)
=> [ACA-2085] configurable viewer retries

projects/aca-shared/package.json, projects/adf-office-services-ext/package.json
Issue Number: ACA-2676
Bump extension version to prepare for release
=> [ACA-2676] prepare extension versions

src/app/components/files/files.component.ts, src/app/components/page.component.ts, src/app/directives/document-list.directive.ts
Issue Number: ACA-2832
- fix selection on reload
=> [ACA-2832] Select node after reload

projects/adf-office-services-ext/assets/aos.plugin.json, projects/adf-office-services-ext/package.json, projects/adf-office-services-ext/src/lib/evaluators.spec.ts, projects/adf-office-services-ext/src/lib/evaluators.ts
Hide the "Edit in Office" action if the node is an Record
=> Hid AOS if record

e2e/suites/actions/share-file.test.ts
Allows builds like ADW to specify /workspace for the affected test
=> Allow other base urls like localhost:8080/workspace

package-lock.json, package.json, src/app.config.json
Issue Number: [ACA-2778](https://issues.alfresco.com/jira/browse/ACA-2778)
validate app.config json based on schema
=> [ACA-2778] App config validation schema

src/app/components/dl-custom-components/name-column/name-column.component.html, src/app/components/dl-custom-components/name-column/name-column.component.spec.ts, src/app/components/dl-custom-components/name-column/name-column.component.ts
Issue Number: [ACA-2835](https://issues.alfresco.com/jira/browse/ACA-2835)
=> [ACA-2835] Favorites list - incorrect viewer actions when opened via link

package-lock.json, package.json
=> upgrade puppeteer version to work with Chrome 79

src/app/app.module.ts, src/app/dialogs/node-templates/create-from-template.dialog.html, src/app/dialogs/node-templates/create-from-template.dialog.scss, src/app/dialogs/node-templates/create-from-template.dialog.spec.ts, src/app/dialogs/node-templates/create-from-template.dialog.ts, src/app/services/create-file-from-template.service.ts, src/app/store/effects/template.effects.spec.ts, src/app/store/effects/template.effects.ts, src/app/ui/custom-theme.scss, src/assets/i18n/en.json
Issue Number: [ACA-2860](https://issues.alfresco.com/jira/browse/ACA-2860)
after template selection from list open a dialog to change template proprieties before copy
=> [ACA-2860] Create file from a template

docs/extending/rules.md, extension.schema.json, projects/aca-shared/rules/src/app.rules.spec.ts, projects/aca-shared/rules/src/app.rules.ts, src/app/components/common/common.module.ts, src/app/components/common/language-picker/language-picker.component.ts, src/app/components/common/logout/logout.component.spec.ts, src/app/components/common/logout/logout.component.ts, src/app/components/current-user/current-user.component.html, src/app/components/current-user/current-user.component.spec.ts, src/app/components/current-user/current-user.component.ts, src/app/components/current-user/current-user.module.ts, src/app/components/current-user/user-menu-item.component.html, src/app/components/current-user/user-menu-item.component.spec.ts, src/app/components/current-user/user-menu-item.component.ts, src/app/extensions/core.extensions.module.ts, src/app/extensions/extension.service.spec.ts, src/app/extensions/extension.service.ts, src/assets/plugins/app.header.json
Issue Number: [ACA-2867](https://issues.alfresco.com/jira/browse/ACA-2867)
use extensibility to declare current user menu actions
=> [ACA-2867] User - actions menu extensibility

.travis.yml, e2e/components/data-table/data-table.ts, e2e/components/search/filters/created-date-filter.ts, e2e/components/search/filters/facet-filter.ts, e2e/components/search/filters/generic-filter-panel.ts, e2e/components/search/filters/size-filter.ts, e2e/components/search/search-filters.ts, e2e/components/search/search-input.ts, e2e/components/search/search-sorting-picker.ts, e2e/pages/search-results-page.ts, e2e/suites/list-views/empty-list.test.ts, e2e/suites/search/search-filters.test.ts, e2e/suites/search/search-input.test.ts, e2e/suites/search/search-results-files-folders.test.ts, e2e/suites/search/search-results-libraries.test.ts, e2e/suites/search/search-sorting.test.ts, e2e/utilities/repo-client/apis/upload/upload-api.ts, e2e/utilities/utils.ts
=> [ACA-2841] Automate tests for Search results filters and sorting

src/app/dialogs/node-templates/create-from-template.dialog.scss
Issue Number: [ACA-2866](https://issues.alfresco.com/jira/browse/ACA-2866)
=> [ACA-2866] Create file from template - dialog actions styling

src/app/dialogs/node-templates/create-from-template.dialog.ts
Issue Number: [ACA-2868](https://issues.alfresco.com/jira/browse/ACA-2868)
=> [ACA-2868] Create File from template - trim name value on submit

src/app/services/create-file-from-template.service.spec.ts, src/app/services/create-file-from-template.service.ts
Issue Number: [ACA-2871](https://issues.alfresco.com/jira/browse/ACA-2871)
=> [ACA-2871] Create File from template - filter link files

src/assets/app.extensions.json, src/assets/i18n/en.json
Issue Number: [ACA-2865](https://issues.alfresco.com/jira/browse/ACA-2865)
=> [ACA-2865] Create File from template - action disabled state tooltip

src/app/services/node-template.service.ts
Issue Number: [ACA-2878](https://issues.alfresco.com/jira/browse/ACA-2878)
=> [ACA-2878] Folder from template - Filter out the links to folders from the templates list

src/app/dialogs/node-template/create-from-template.dialog.ts
Issue Number: [ACA-2881](https://issues.alfresco.com/jira/browse/ACA-2881)
=> [ACA-2881] Create from template - dialog error if selected node doesn't have properties

e2e/suites/actions/create-file-from-template.test.ts, src/assets/i18n/en.json
Issue Number: [ACA-2882](https://issues.alfresco.com/jira/browse/ACA-2882)
=>  [ACA-2882] Create from template - generic form errors

e2e/components/menu/menu.ts, e2e/components/sidenav/sidenav.ts, e2e/suites/actions/create-file-from-template.test.ts, e2e/suites/actions/create-folder-from-template.test.ts, e2e/suites/actions/new-menu.test.ts, e2e/suites/actions/upload-file.test.ts, e2e/utilities/admin-actions.ts, e2e/utilities/repo-client/apis/nodes/nodes-api.ts, protractor.conf.js, src/app/services/node-template.service.spec.ts
automate tests for Create folder from template
added unit test for exclusion of folder links
Issue Number: ACA-1921, ACA-2877
=> [ACA-1921] automate tests for Create folder from template

src/app/components/layout/app-layout/app-layout.component.ts
Issue Number: [ACA-2883](https://issues.alfresco.com/jira/browse/ACA-2883)
hideConditions, which some checks depend on by doing  'url.includes(el)' might get confused about `url?q=prerview` and `url/preview/path`
=> [ACA-2883] Main page disappears when searching for "preview"

src/app/services/node-template.service.ts, src/app/ui/overrides/adf-style-fixes.theme.scss
Issue Number: [ACA-2870](https://issues.alfresco.com/jira/browse/ACA-2870)
=> [ACA-2870] Create from template - extra unnecessary call is performed when opening the dialog

projects/adf-office-services-ext/src/lib/aos-extension.service.ts
Issue Number: [ACA-2909](https://issues.alfresco.com/jira/browse/ACA-2909)
=> [ACA-2909] Edit in Microsoft Office doesn't work on shared files

src/app/components/page.component.spec.ts, src/app/components/page.component.ts
Issue Number: [ACA-2910](https://issues.alfresco.com/jira/browse/ACA-2910)
=> [ACA-2910] Viewer - Info Drawer action triggers parent side panel

package-lock.json, package.json
=> upgrade puppeteer to use the latest chrome

src/app/components/permissions/permission-dialog/node-permissions.dialog.html
Issue Number: [ACA-2564](https://issues.alfresco.com/jira/browse/ACA-2564)
=>  [ACA-2564] - Manage Permissions - Visual heading text is not marked as a heading

src/app/components/favorite-libraries/favorite-libraries.component.html, src/app/components/favorite-libraries/favorite-libraries.component.ts
Issue Number: [ACA-2280](https://issues.alfresco.com/jira/browse/ACA-2280)
=>  [ACA-2280] Favorite Libraries - Previous page is not loaded when deleting all items from current page

src/app/ui/overrides/adf-style-fixes.theme.scss
Issue Number: [ACA-2916](https://issues.alfresco.com/jira/browse/ACA-2916)
=>  [ACA-2916] Share dialog - hide floating label

e2e/suites/actions-available/files-folders/favorites.ts, e2e/suites/actions-available/files-folders/personal-files.ts, e2e/suites/actions-available/files-folders/recent-files.ts, e2e/suites/actions-available/files-folders/search-results.ts, e2e/suites/actions-available/files-folders/shared-files.ts, e2e/suites/actions-available/files-folders/viewer.ts, e2e/suites/actions-available/libraries/library.test.ts, e2e/suites/actions-available/special-permissions/favorites.ts, e2e/suites/actions-available/special-permissions/my-libraries.ts, e2e/suites/actions-available/special-permissions/search-results.ts, e2e/suites/actions-available/special-permissions/shared-files.ts, e2e/suites/actions-available/special-permissions/viewer.ts
add TestRail IDs to some tests that didn't have one
=> add TestRail IDs

e2e/components/data-table/data-table.ts, e2e/components/dialog/password-dialog.ts, e2e/suites/actions-available/files-folders/shared-files.ts, e2e/suites/actions-available/files-folders/test-data.ts, e2e/suites/actions-available/special-permissions/favorites.ts, e2e/suites/actions-available/special-permissions/other-permissions.ts, e2e/suites/actions-available/special-permissions/test-data-permissions.ts, e2e/suites/actions/edit-offline.test.ts, e2e/suites/actions/unshare-file.test.ts, e2e/suites/viewer/viewer-protected-file.test.ts, projects/aca-shared/rules/src/app.rules.ts, projects/adf-office-services-ext/src/lib/evaluators.ts, src/app/components/favorites/favorites.component.html, src/app/components/search/search-results/search-results.component.html, src/app/components/shared-files/shared-files.component.html
Issue Number: 
[ACA-2174](https://issues.alfresco.com/jira/browse/ACA-2174)
[ACA-2173](https://issues.alfresco.com/jira/browse/ACA-2173)
=> [ACA-2174][ACA-2173] Shared / Favorites - edit offline

README.md
Updating the what's new section, compatibility and feature sections
=> Updates for 1.10 release

package-lock.json, package.json, src/app.config.json
=> bump 1.10.0

projects/aca-shared/package.json, projects/adf-office-services-ext/assets/aos.plugin.json, projects/adf-office-services-ext/package.json
=> bump ng libraries version

src/assets/i18n/ar.json, src/assets/i18n/cs.json, src/assets/i18n/da.json, src/assets/i18n/de.json, src/assets/i18n/es.json, src/assets/i18n/fi.json, src/assets/i18n/fr.json, src/assets/i18n/it.json, src/assets/i18n/ja.json, src/assets/i18n/nb.json, src/assets/i18n/nl.json, src/assets/i18n/pl.json, src/assets/i18n/pt-BR.json, src/assets/i18n/ru.json, src/assets/i18n/sv.json, src/assets/i18n/zh-CN.json
=> LOC-191: Localised UI files for ADW 1.4

e2e/components/breadcrumb/breadcrumb.ts, e2e/components/datetime-picker/datetime-picker.ts, e2e/components/dialog/confirm-dialog.ts, e2e/components/dialog/content-node-selector-dialog.ts, e2e/components/dialog/create-edit-folder-dialog.ts, e2e/components/dialog/create-from-template-dialog.ts, e2e/components/dialog/create-library-dialog.ts, e2e/components/dialog/generic-dialog.ts, e2e/components/dialog/manage-versions-dialog.ts, e2e/components/dialog/password-dialog.ts, e2e/components/dialog/select-template-dialog.ts, e2e/components/dialog/share-dialog.ts, e2e/components/dialog/upload-new-version-dialog.ts, e2e/suites/actions/share-file.test.ts
- create a generic-dialog class to remove some duplicated code
- add return types
=> e2e refactorings

src/assets/i18n/es.json
=> SPANISH: fixed string for typos

e2e/utilities/repo-client/apis/nodes/node-body-create.ts, e2e/utilities/repo-client/apis/nodes/nodes-api.ts, e2e/utilities/utils.ts
=> add workaround needed in ADW due to REPO-4772

package-lock.json, package.json, projects/aca-shared/src/lib/services/content-api.service.ts, projects/adf-office-services-ext/src/lib/aos-extension.service.ts
=> [MNT-21394] Edit in Microsoft Office opens MS Excel documents then immediately prompts that a newer version exists

package-lock.json, package.json, projects/aca-shared/package.json, projects/adf-office-services-ext/assets/aos.plugin.json, projects/adf-office-services-ext/package.json, src/app.config.json
=> 1.9.1 bump

projects/aca-shared/src/lib/services/content-api.service.ts, projects/adf-office-services-ext/src/lib/aos-extension.service.ts
MNT-21394 - Edit in Microsoft Office opens MS Excel documents… then immediately prompts that a newer version exists
=> fix for [MNT-21394]

package-lock.json, package.json, projects/aca-shared/package.json, projects/adf-office-services-ext/assets/aos.plugin.json, projects/adf-office-services-ext/package.json, src/app.config.json
bump versions - preparing to release
=> bump versions

projects/aca-shared/src/lib/components/page-layout/page-layout.component.scss, src/app/components/sidenav/sidenav.component.theme.scss, src/app/ui/custom-theme.scss, src/app/ui/theme.scss
Reverts Alfresco/alfresco-content-app#1368
=> Revert "[ACA-2125] Update sidenav colors and font-size"

src/app/components/create-menu/create-menu.component.scss
Reverts Alfresco/alfresco-content-app#1367
=> Revert "[ACA-2124] New bg-color and font style for "New" button"

projects/aca-shared/rules/src/app.rules.ts, projects/aca-shared/store/src/actions/app.actions.ts, projects/aca-shared/store/src/selectors/app.selectors.ts, projects/aca-shared/store/src/states/app.state.ts, src/app.config.json, src/app/app.component.ts, src/app/components/settings/settings.component.html, src/app/components/settings/settings.component.theme.scss, src/app/components/settings/settings.component.ts, src/app/extensions/core.extensions.module.ts, src/app/extensions/extension.service.ts, src/app/store/initial-state.ts, src/app/store/reducers/app.reducer.ts
Issue Number: https://issues.alfresco.com/jira/browse/ACA-2948
=> [ACA-2948] Add process services extension in settings page

src/app/components/layout/layout.theme.scss
=> ACA - Fix import

src/app/components/sidenav/sidenav.component.theme.scss
> - [ ] Bugfix
Styling
**What is the current behaviour?** 
Contrast issues on the sidenav for AA accessibility.
With those changes and the update of the theme of …
=> [ACA-2125] Update sidenav colors to meet design spec

.travis.yml, package.json, scripts/ci/job_hooks/before_install.sh, scripts/ci/utils/artifact-from-s3.sh, scripts/ci/utils/artifact-to-s3.sh, src/app/components/layout/layout.theme.scss, tsconfig.json
=> Fix the scss import and save the build on S3

.travis.yml, scripts/trigger-travis.sh
> - [ ] Bugfix
trigger DW build after merge in development or master
**Does this PR …
=> trigger DW build after merge in development or master

src/app/components/login/login.component.html, src/assets/images/Wallpaper-BG-generic.svg
> - [ ] Bugfix
Styling
The general background image is used for ACA login's page. …
=> [ACA-2959] Add new login background

src/app/components/header/header.component.scss, src/assets/images/mastHead-bg-shapesPattern.svg
> - [ ] Bugfix
Styling
No background image or shadow for the header.
Add the …
=> [ACA-2960] Add background image and elevation to header

.travis.yml
> - [ ] Bugfix
Remove duplicated builds …
=> Trigger build only on branches

package-lock.json, package.json, src/app/components/context-menu/context-menu.component.html, src/app/components/dl-custom-components/name-column/name-column.component.html, src/app/components/search/search-results-row/search-results-row.component.html, src/app/directives/library-favorite.directive.spec.ts, src/app/directives/lock-node.directive.spec.ts, tslint.json
> - [ ] Bugfix
- upgrade to latest codelyzer
- enable a11y rules
**Does this PR …
=> upgrade codelyzer and enable a11y rules

src/app/components/header/header.component.scss
=> Fix: Use the absolute path

src/app/components/info-drawer/info-drawer.component.ts, src/app/components/viewer/viewer.component.html, src/app/components/viewer/viewer.component.ts
Issues:  
-  https://issues.alfresco.com/jira/browse/ACA-2368
-  https://issues.alfresco.com/jira/browse/ACA-1144
Intention of this PR :-
1. Viewer file name is not updating when changing the name
2. https://issues.alfresco.com/jira/browse/ACA-1144
=> [ACA-2368] UI Issues while editing Metadata in the Preview Page

e2e/components/dialog/password-dialog.ts, e2e/components/viewer/viewer.ts, e2e/suites/viewer/viewer-protected-file.test.ts
> - [ ] Bugfix
viewer-protected-file suite has one weird flaky test, that fails once in a while …
=> [E2E] try to fix one weird flaky test

extension.schema.json, src/app/components/settings/settings.component.ts, src/app/extensions/extension.service.ts, src/app/types.ts, src/assets/app.extensions.json
> - [ ] Bugfix
- add "rules" support to setting categories
- fix a bug with saving …
=> [ACA-1743] improved settings api

.travis.yml, package-lock.json, package.json, scripts/postinstall.sh
> - [x] Bugfix
- use the same `config.chromeDriver` field as AMA and APA
- use same …
=> unified puppeteer setup

projects/aca-shared/rules/src/app.rules.ts, src/app/extensions/core.extensions.module.ts, src/assets/app.extensions.json
> - [ ] Bugfix
- remove settings that are not relevant to the application (will be …
=> [ACA-2948] Remove process services and AI extension from settings page

src/app/components/search/search-results/search-results.component.scss
> - [X] Bugfix
chips are hitting on the underline layout
more spaces for the search …
=> [ACA-3015] - fixed style for chips

package-lock.json, package.json, projects/aca-shared/rules/src/app.rules.spec.ts, src/app/components/context-menu/context-menu.service.ts, src/app/components/favorite-libraries/favorite-libraries.component.spec.ts, src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.spec.ts, src/app/components/preview/preview.component.spec.ts, src/app/components/recent-files/recent-files.component.spec.ts, src/app/components/search/search-libraries-results/search-libraries-query-builder.service.spec.ts, src/app/components/search/search-results/search-results.component.spec.ts, src/app/extensions/extension.service.spec.ts, src/app/extensions/extension.service.ts, src/app/services/content-management.service.spec.ts, src/app/services/content-management.service.ts, src/app/services/node-actions.service.spec.ts, src/app/services/node-actions.service.ts, src/app/services/node-template.service.spec.ts, src/app/store/effects/contextmenu.effects.spec.ts, src/app/store/effects/template.effects.spec.ts, src/app/store/effects/upload.effects.spec.ts
> - [ ] Bugfix
[ACA-3081](https://issues.alfresco.com/jira/browse/ACA-3081)
**Does …
=> [ACA-3081] upgrade @types/jasmine to latest

protractor.conf.js
> - [ ] Bugfix
some tests were forgotten by mistake to be enabled on travis
enable …
=> [e2e] enable tests

src/assets/i18n/fr.json, src/assets/i18n/nl.json
> - [x ] Tests for the changes have been added (for bug fixes / features)
> - [ NA] Docs have been added / updated (for bug fixes / features)
> - [x ] Bugfix
Fixes to shorten strings in French and Dutch
**Does this PR …
=> LOC-129 -fixes for UI strings in French and Dutch

cspell.json, projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.spec.ts, projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.ts, projects/aca-shared/src/public-api.ts, src/app/app.routes.ts
https://issues.alfresco.com/jira/browse/ACA-3131
=> [ACA-3131] Add extension loader guard

package-lock.json, package.json
> - [x] Bugfix
PR to update ADF on ACA and fix issues if present
**Does this PR …
=> Update to latest ADF libraries

package-lock.json, package.json, src/app.config.json
> - [ ] Bugfix
Bump application version to 1.11.0 …
=> [ACA-3153] bump version to 1.11.0

README.md
=> Updating Readme for release 1.11.0

.travis.yml, projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.ts, scripts/travis/release/release-npm.sh
> - [ ] Bugfix
- automatically publish to NPM on merges to master
- fix the production …
=> [ACA-3238] automatically publish libraries on release

projects/aca-shared/package.json, projects/adf-office-services-ext/package.json
> - [ ] Bugfix
- bump the shared libraries versions
- align the library versions with …
=> bump and align lib versions with the app

.travis.yml, scripts/travis/release/git-tag.sh
> - [x] Bugfix
Add tag end release …
=> Add tag end release

package-lock.json, package.json
> - [ ] Bugfix
- upgrade to ADF 3.8.0 release …
=> upgrade to ADF 3.8.0 final

README.md, docs/extending/creating-custom-evaluators.md, docs/features/file-viewer.md, docs/features/version-manager.md, docs/ja/extending/creating-custom-evaluators.md, docs/ja/features/version-manager.md, extension.schema.json, scripts/travis/release/release-npm.sh
=> Rename branch to develop

.travis.yml, .vscode/settings.json, docs/extending/README.md, docs/extending/custom-extension-loaders.md, projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.ts, scripts/ci/job_hooks/before_install.sh, scripts/install.sh, scripts/update-version.sh
=> Add missing documentation for extension loader callbacks

e2e/components/search/search-input.ts, e2e/suites/actions/edit-folder.test.ts, e2e/suites/actions/library-actions.test.ts, e2e/utilities/utils.ts, protractor.conf.js
> - [ ] Bugfix
- fix flaky methods: add missing await, set correct return type, add extra beforeEach for safety
- separate declarations for a few variables
- improve log messages in case of …
=> [e2e] fix flaky tests

src/app/components/header/header.component.spec.ts, src/app/components/toolbar/toolbar-action/toolbar-actions.component.scss, src/app/ui/custom-theme.scss
> - [x] Bugfix
[ACA-3278](https://issues.alfresco.com/jira/browse/ACA-3278)
**Does …
=> [ACA-3278] Header - extension actions not visible

docker/entrypoint.sh
> - [ ] Bugfix
use unified `APP_CONFIG_BPM_HOST` and `APP_CONFIG_ECM_HOST` variables …
=> [AAE-2603] unified env variables for ecm/bpm hosts

projects/aca-shared/src/lib/testing/lib-testing-module.ts
> - [ ] Bugfix
fixed dw prod build issue …
=> [ACA-3251] DW prod build  issue

package-lock.json, package.json, src/app/components/toolbar/toggle-favorite/toggle-favorite.component.ts, src/assets/app.extensions.json
=> Favorite remove the route evaluation

package-lock.json, package.json, scripts/update-commit-sha.sh, src/app/components/about/about.component.html, src/app/components/about/about.component.ts, src/proxy.conf.js
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3317
It now displays the …
=> [ACA-3317] Show app current deployed commit in About Page

docs/getting-started/building-from-source.md, protractor.conf.js, scripts/app-config-replace.js, src/proxy.conf.js
=> [ACA-3342] Rename API_HOST to API_CONTENT_HOST

package-lock.json, package.json, projects/aca-shared/src/lib/directives/pagination.directive.spec.ts, src/app/components/context-menu/context-menu.service.spec.ts, src/app/components/dl-custom-components/name-column/name-column.component.spec.ts, src/app/components/node-version/node-version-form.component.spec.ts, src/app/components/search/search-results/search-results.component.spec.ts, src/app/components/toolbar/toggle-edit-offline/toggle-edit-offline.component.spec.ts, src/app/components/toolbar/toggle-favorite-library/toggle-favorite-library.component.spec.ts, src/app/components/toolbar/toggle-favorite/toggle-favorite.component.spec.ts, src/app/components/toolbar/view-node/view-node.component.spec.ts, src/app/dialogs/node-template/create-from-template.dialog.spec.ts, src/app/dialogs/node-version-upload/node-version-upload.dialog.spec.ts, src/app/directives/library-favorite.directive.spec.ts, src/app/directives/library-membership.directive.spec.ts, src/app/directives/lock-node.directive.spec.ts
=> Use latest adf to fix issue 3252

docs/extending/routes.md, projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.spec.ts, projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.ts, src/app/extensions/core.extensions.module.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3315
Added new predefined …
=> [ACA-3315] - add predefined extension guard

docs/extending/routes.md
> - [X] Docs have been added / updated (for bug fixes / features)
> - [ ] Bugfix
> - [X] Documentation
https://issues.alfresco.com/jira/browse/ACA-3450
**Does this PR …
=> [ACA-3450] Add missing documentation about parentRoute

package-lock.json, package.json, src/app/dialogs/node-versions/node-versions.dialog.html, src/app/dialogs/node-versions/node-versions.dialog.spec.ts, src/app/dialogs/node-versions/node-versions.dialog.theme.scss
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3266
Imported the ADF …
=> [ACA-3266] Improve version upload component

e2e/resources/extensibility-configs/info-drawer-ext.json, e2e/resources/extensibility-configs/viewer-ext.json, e2e/suites/list-views/file-libraries.test.ts, e2e/suites/search/search-results-libraries.test.ts, projects/aca-testing-shared/src/components/data-table/data-table.ts, src/assets/app.extensions.json, src/assets/i18n/en.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACS-180
This PR brings the …
=> [ACS-180] Add Description column to My libraries / Favorites

projects/adf-office-services-ext/src/lib/utils.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/MNT-18448
Edit Online MS Visio files
Supported file extensions: vsd, vss, vst, vsdx, …
=> MNT-18448 - Edit Online for MS Visio files

projects/adf-office-services-ext/src/lib/utils.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/MNT-19466
Edit online RTF files …
=> MNT-19466 - Edit Online for RTF files

src/assets/app.extensions.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3468
The description is not shown in the library
**What is …
=> [ACA-3469] Description in Document library Site

package-lock.json, package.json
=> Use the latest adf

src/assets/i18n/fr.json
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3471
The translation has …
=> [ACA-3471] too long french translation doesn't fit in the UI

src/app/components/search/search-results/search-results.component.scss
> - [x] Bugfix
Fix the layout of the search result DL …
=> [ACA-3538] Fix search result layout
